### PR TITLE
 [configgrpc] update ClientConfig to allow custom grpc resolver schemes

### LINKED ISSUE #14990: configgrpc: No way to control gRPC resolver scheme, causing IPv6 connection failures in IPv4-only environments
### Component(s)

config/configgrpc

### What happened?

 **Describe the bug**
  After the migration from `grpc.DialContext` to `grpc.NewClient` in #13663 (shipped in v0.144.0), the default gRPC resolver scheme changed from `passthrough` to `dns`. Combined
  with grpc-go's new `pick_first` load balancer (mandatory since grpc-go v1.77.0), which implements RFC 8305 Happy Eyeballs with IPv4/IPv6 address interleaving, this causes
  connection failures or 250ms+ latency penalties in IPv4-only environments when the target hostname has AAAA DNS records.

  There is currently no way for users or component authors to control the resolver scheme used by `configgrpc.ClientConfig`. The `passthrough:///` scheme cannot be specified in the
   `endpoint` field because `Validate()` passes it through `sanitizedEndpoint()` (which doesn't recognize it) and then to `net.SplitHostPort()`, which rejects it with "too many
  colons in address". There is also no `scheme` or `resolver` configuration field.

  **Steps to reproduce**
  1. Deploy an OTel Collector (v0.144.0+) in an IPv4-only environment
  2. Configure a gRPC exporter with an endpoint hostname that has both A and AAAA DNS records (e.g., a dual-stack NLB)
  3. Observe that the collector attempts IPv6 connections first, which fail, adding latency or causing connection errors

  **What did you expect to see?**
  Users should have a way to control the gRPC resolver scheme, or at minimum the collector should gracefully handle environments where IPv6 is not available. Prior to v0.144.0,
  `grpc.DialContext` used the `passthrough` scheme by default, which delegated address selection to the OS networking stack and worked correctly.

  **What did you see instead?**
  The `dns` resolver returns both AAAA and A records. grpc-go's `pick_first` balancer interleaves them per RFC 8305 with IPv6 first (due to Go's RFC 6724 sorting giving IPv6
  precedence 40 vs IPv4's 35). In IPv4-only environments, the IPv6 attempt fails, and after a 250ms Happy Eyeballs timer, IPv4 is attempted. In some cases connections fail
  entirely.

### Collector version

v0.145.0

### Environment information

  OS: Linux (IPv4-only Kubernetes pods connecting to dual-stack NLBs)
  Compiler: go 1.24
  grpc-go: v1.79.1 (issue exists with any version >= v1.77.0 when paired with grpc.NewClient)

### OpenTelemetry Collector configuration

```yaml
exporters:
    otlp:
      endpoint: "my-dual-stack-nlb.example.com:4317"
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        exporters: [otlp]
```

### Log output

```shell

```

## Root Cause Analysis

  Two upstream changes compound to cause this:

  1. **OTel Collector v0.144.0** (#13663) — migrated from `grpc.DialContext` (default scheme: `passthrough`) to `grpc.NewClient` (default scheme: `dns`)
  2. **grpc-go v1.77.0** (grpc/grpc-go#8672) — removed the old `pick_first` LB entirely; the new implementation with Happy Eyeballs address interleaving is now mandatory

  The `configgrpc.sanitizedEndpoint()` function only recognizes `http://`, `https://`, and `dns://` schemes. The `passthrough://` scheme is not handled, and there is no
  configuration field to specify the resolver scheme.

  ## Proposed Solutions (any of the following)

  1. Add a `resolver_scheme` field to `ClientConfig` allowing users to specify `passthrough`, `dns`, or other registered resolver schemes
  2. Recognize `passthrough://` in `sanitizedEndpoint()` and `Validate()` so it can be specified in the `endpoint` field
  3. Add an `ip_version` or `prefer_ip_version` field that filters resolved addresses by address family before passing them to the load balancer

  ## Related Issues

  - #13663 — Move from DialContext to NewClient
  - #14372 — dns:/// scheme treated as passthrough since v0.141.0
  - #14090 — gRPC balancer default behavior in OTLP exporter
  - grpc/grpc-go#7429 — localhost connection fails (IPv6 resolved first)
  - grpc/grpc-go#3982 — Missing ipv4/ipv6 scheme support

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by Erog38**
#### Description

  After #13663 migrated from `grpc.DialContext` to `grpc.NewClient`, the default gRPC resolver scheme changed from `passthrough` to `dns`. Combined with grpc-go v1.77.0+
  making the new `pick_first` load balancer mandatory (which implements RFC 8305 Happy Eyeballs with IPv4/IPv6 address interleaving), this causes connection failures or
  250ms+ latency penalties in IPv4-only environments when the target hostname has AAAA DNS records.

  There was no way for users to work around this — `passthrough:///host:port` couldn't be specified in the endpoint field because `Validate()` rejected it via
  `net.SplitHostPort`, and no dedicated config field existed.

  This PR relaxes endpoint validation to accept any gRPC resolver scheme URI directly in the `endpoint` field (e.g. `passthrough:///host:port`, `dns:///host:port`,
  `xds:///service`). This aligns with the [OTLP specification](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#endpoint-urls-for-otlpgrpc) which states the
  endpoint SHOULD accept any form allowed by the underlying gRPC client implementation.

  **How it works:**

  - `sanitizedEndpoint()` now uses a generic regex to strip any `scheme://[authority]/` prefix for host:port validation, instead of only recognizing `http://`,
  `https://`, and `dns://`
  - A new `grpcDialTarget()` method passes gRPC scheme URIs through to `grpc.NewClient` as-is, only stripping `http://` and `https://` (which are not gRPC resolver
  schemes)
  - No new config fields — users just set their endpoint to `passthrough:///host:port`

  #### Link to tracking issue

  Fixes #14990

  #### Testing

  - `TestSanitizeEndpoint` — verifies scheme stripping for dns, passthrough, xds, and edge cases
  - `TestGrpcDialTarget` — verifies http/https are stripped while gRPC schemes (dns, passthrough, xds) are preserved
  - `TestValidateGrpcSchemeEndpoint` — verifies validation accepts passthrough and dns scheme endpoints
  - `TestToClientConnWithPassthroughEndpoint` — end-to-end: creates a client connection with a passthrough endpoint
  - Full configgrpc test suite passes with no regressions

  #### Documentation

  - Updated `config/configgrpc/README.md` endpoint documentation to describe gRPC scheme URI support
  - No schema changes needed — the endpoint field already accepts strings

### CODE REVIEW

**Comment by Erog38** [comment]
How can I help this gain traction? I'm more than happy to solve this issue in other ways if preferred.

File: config/configgrpc/configgrpc_test.go [hunk 1]
```diff
@@ -41,6 +42,27 @@ var (
 	_ extensionauth.Server = (*mockAuthServer)(nil)
 )
 
+func init() {
+	// Register a custom resolver scheme for testing the custom scheme validation
+	// and dialTarget code paths.
+	resolver.Register(&nopResolverBuilder{scheme: "custom-test"})
+}
```
Comment (mx-psi) [inline config/configgrpc/configgrpc_test.go]: could we do this outside of an init function? (to avoid interfering with other tests)

**Comment by mx-psi** [comment]
I confirmed with an OpenTelemetry Go maintainer that we pass the endpoint directly to `grpc.NewClient` in the OpenTelemetry Go SDK OTLP/gRPC exporters so I think we should do that here

File: config/configgrpc/configgrpc_test.go (hunk 1 above)
Comment (Erog38) [reply config/configgrpc/configgrpc_test.go]: Done

**Comment by Erog38** [comment]
@mx-psi updated, I relaxed validation but added a regex to still be able to best-effort grab the endpoint when wanting the sanitized endpoint

File: .chloggen/configgrpc-resolver-scheme.yaml [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+# (Optional) One or more lines of additional information to render under the primary note.
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext: |
+  After the migration from grpc.DialContext to grpc.NewClient, the default resolver
+  scheme changed from "passthrough" to "dns". Combined with grpc-go v1.77.0+ making
+  Happy Eyeballs (RFC 8305) mandatory, this causes IPv6 connection attempts first in
+  dual-stack DNS environments. The endpoint field now accepts any gRPC resolver scheme
+  URI (e.g. passthrough:///host:port, dns:///host:port, xds:///service), aligned with
+  the OTLP specification which states the endpoint SHOULD accept any form allowed by
```
Comment (mx-psi) [inline .chloggen/configgrpc-resolver-scheme.yaml]:
```suggestion
  the SDK OTLP exporter specification which states the endpoint SHOULD accept any form allowed by
```

File: config/configgrpc/README.md [hunk 3]
```diff
@@ -17,7 +17,7 @@ README](../configtls/README.md).
 
 - [`balancer_name`](https://github.com/grpc/grpc-go/blob/master/examples/features/load_balancing/README.md): Default before v0.103.0 is `pick_first`, default for v0.103.0 is `round_robin`. See [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/10298). To restore the previous behavior, set `balancer_name` to `pick_first`.
 - `compression`: Compression type to use among `gzip`, `snappy`, `zstd`, and `none`.
-- `endpoint`: Valid value syntax available [here](https://github.com/grpc/grpc/blob/master/doc/naming.md)
+- `endpoint`: Valid value syntax available [here](https://github.com/grpc/grpc/blob/master/doc/naming.md). The endpoint accepts any form allowed by the underlying gRPC client implementation, including gRPC resolver scheme URIs such as `dns:///host:port`, `passthrough:///host:port`, or `xds:///service`. The `passthrough` scheme bypasses gRPC's DNS resolution and passes the address directly to the OS networking stack via `net.Dial`, which is useful in IPv4-only environments where dual-stack DNS records (AAAA + A) cause the [Happy Eyeballs](https://datatracker.ietf.org/doc/html/rfc8305) algorithm to attempt IPv6 connections first.
```
Comment (mx-psi) [inline config/configgrpc/README.md]: I don't think this adds much, the previous doc is roughly the current behavior

Comment (Erog38) [reply config/configgrpc/README.md]: fair point, reverted

File: config/configgrpc/configgrpc.go [hunk 4]
```diff
@@ -254,16 +254,41 @@ func (cc *ClientConfig) Validate() error {
...
 
-// sanitizedEndpoint strips the prefix of either http:// or https:// from configgrpc.ClientConfig.Endpoint.
+// grpcSchemeRE matches a gRPC target URI with a scheme and optional authority:
+//
+//	scheme://[authority]/endpoint
+//
+// It captures the endpoint portion after the authority separator.
+var grpcSchemeRE = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9+.-]*://[^/]*/(.*)$`)
+
+// sanitizedEndpoint strips the URI scheme prefix from the endpoint to extract
```
Comment (mx-psi) [inline config/configgrpc/configgrpc.go]: Can we document on the godoc for this function that it also strips the authority ?

File: config/configgrpc/configgrpc.go [hunk 5]
```diff
@@ -254,16 +254,41 @@ func (cc *ClientConfig) Validate() error {
...
 		return strings.TrimPrefix(cc.Endpoint, "http://")
 	case cc.isSchemeHTTPS():
 		return strings.TrimPrefix(cc.Endpoint, "https://")
-	case strings.HasPrefix(cc.Endpoint, "dns://"):
-		r := regexp.MustCompile(`^dns:///?`)
-		return r.ReplaceAllString(cc.Endpoint, "")
+	default:
+		// Strip gRPC URI scheme and authority (e.g. "dns:///", "passthrough:///",
+		// "dns://authority/") to extract the endpoint for validation.
+		if m := grpcSchemeRE.FindStringSubmatch(cc.Endpoint); m != nil {
```
Comment (jade-guiton-dd) [inline config/configgrpc/configgrpc.go]: Nitpick: Instead of a hard-to-verify regex, maybe it would be more reliable if we used proper parsing, the same way grpc-go does it? It seems to call `url.Parse` ([link](https://github.com/grpc/grpc-go/blob/1c132b9bfcd929e2c4ffbe48d2c2436608191f07/clientconn.go#L1879)), then [this exported function](https://github.com/grpc/grpc-go/blob/397e45edaa68f8763773bbaaf539cf7894169cd2/resolver/resolver.go#L279) to extract the endpoint.

(The checks for HTTP and HTTPS could also similarly be done more cleanly using `URL.Scheme`)

File: .chloggen/configgrpc-resolver-scheme.yaml [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext: |
+  After the migration from grpc.DialContext to grpc.NewClient, the default resolver
+  scheme changed from "passthrough" to "dns". Combined with grpc-go v1.77.0+ making
+  Happy Eyeballs (RFC 8305) mandatory, this causes IPv6 connection attempts first in
+  dual-stack DNS environments. The endpoint field now accepts any gRPC resolver scheme
+  URI (e.g. passthrough:///host:port, dns:///host:port, xds:///service), aligned with
+  the SDK OTLP exporter specification which states the endpoint SHOULD accept any form allowed by
+  the underlying gRPC client implementation.
```
Comment (jade-guiton-dd) [inline .chloggen/configgrpc-resolver-scheme.yaml]: Nitpick: I think this is probably a bit too much technical detail for the changelog, maybe limit it to something like:
> After version X, some gRPC client components such as the OTLP exporter experienced connection issues in dual-stack DNS environments. This can now be fixed by using the passthrough:/// gRPC resolver.

**Comment by Erog38** [comment]
Thank you @jade-guiton-dd and @mx-psi ! I'm working through your nitpicks and will have one more commit for you to look through shortly if you're willing to re-approve afterward

**Comment by Erog38** [comment]
Should be good to go here 😄
