### PR TITLE
Copy AggregationTemporality and IsMonotonic to new metric batches

### LINKED ISSUE #4388: Batch processor not setting metric descriptor correctly when splitting batches of metrics.
**Describe the bug**
When a batch of metrics is split, the metric descriptor isn't correctly set for some of the metrics.  Some cumulative metrics end up with:
```
     -> IsMonotonic: false
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_UNSPECIFIED
```

**Steps to reproduce**
I'm using the prometheus receiver with a random helm chart (https://artifacthub.io/packages/helm/presslabs/mysql-operator).  The particular endpoint doesn't matter, it just needs a lot of metrics, with some of them being cumulative.

Otel collector config:
```
receivers:
  prometheus:
    config:
      ... point prometheus at the mysql exporter...
processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200
exporters:
  logging:
    logLevel: debug
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [logging]
```
**What did you expect to see?**
The correct descriptor for the first point is:
```
Metric #0
Descriptor:
     -> Name: mysql_global_status_commands_total
     -> Description: Total number of executed MySQL commands.
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
Data point attributes:
     -> command: STRING(admin_commands)
     -> gke_kubernetes_container_name: STRING(metrics-exporter)
     -> gke_kubernetes_namespace: STRING(fake/mysql-podmonitor/0)
     -> gke_kubernetes_pod_name: STRING(my-cluster-mysql-0)
StartTimestamp: 2021-11-10 05:45:31.385 +0000 UTC
Timestamp: 2021-11-10 05:45:31.385 +0000 UTC
Value: 60979.000000
```

**What did you see instead?**
```
Metric #45
Descriptor:
     -> Name: mysql_global_status_commands_total
     -> Description: Total number of executed MySQL commands.
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_UNSPECIFIED
NumberDataPoints #0
Data point attributes:
     -> command: STRING(admin_commands)
     -> gke_kubernetes_container_name: STRING(metrics-exporter)
     -> gke_kubernetes_namespace: STRING(fake/mysql-podmonitor/0)
     -> gke_kubernetes_pod_name: STRING(my-cluster-mysql-0)
StartTimestamp: 2021-11-10 05:45:31.385 +0000 UTC
Timestamp: 2021-11-10 05:45:31.385 +0000 UTC
Value: 60446.000000
...
Metric #0
Descriptor:
     -> Name: mysql_global_status_commands_total
     -> Description: Total number of executed MySQL commands.
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
Data point attributes:
     -> command: STRING(change_db)
     -> gke_kubernetes_container_name: STRING(metrics-exporter)
     -> gke_kubernetes_namespace: STRING(fake/mysql-podmonitor/0)
     -> gke_kubernetes_pod_name: STRING(my-cluster-mysql-0)
StartTimestamp: 2021-11-10 05:45:31.385 +0000 UTC
Timestamp: 2021-11-10 05:45:31.385 +0000 UTC
Value: 1.000000
```

**What version did you use?**
Version: v0.38.0

**What config did you use?**
```
receivers:
  prometheus:
    config:
      ... point prometheus at the mysql exporter...
processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200
exporters:
  logging:
    logLevel: debug
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [logging]
```

Based on my testing, the regression appears to be introduced between v0.29.0 and v0.30.0.  Looking at [changes in June/July](https://github.com/open-telemetry/opentelemetry-collector/commits/7983af7be0d36988fb18732dc3c0f53cbd163439/processor/batchprocessor) to the batch processor, https://github.com/open-telemetry/opentelemetry-collector/pull/3573 seems a possible candidate.

### PR DESCRIPTION
**Pull request by dashpole**
**Description:**
Fix a regression in which metric batches do not have aggregation temporality and IsMonotonic set for cumulative metrics.  The issue was introduced in #3573, where we changed to having to copy each field from the old metric to the new one.  These fields were missed, and thus get their default value when new batches of metrics were created.

I looked at the implementation of [CopyTo](https://github.com/open-telemetry/opentelemetry-collector/blob/main/model/pdata/generated_metrics.go#L716) that is used for copying metrics elsewhere to make sure I fix all issues of this type.  For Sum, we are missing AggregationTemporality and IsMonotonic.  We were also missing [AggregationTemporality](https://github.com/open-telemetry/opentelemetry-collector/blob/main/model/pdata/generated_metrics.go#L768) for histograms, so I added that as well.  Both summary and gauges only copy data points, so the status quo is correct.

**Link to tracking Issue:**
Fixes #4388

**Testing:**

Unit testing.  The test changes I made fail without the corresponding changes to metric splitting.  I haven't had a chance to e2e test it yet to show that it fixes the issue I was seeing, but it seems fairly obvious that this is the correct fix for my problems.

cc @Aneurysm9

### CODE REVIEW

File: processor/batchprocessor/splitmetrics.go [hunk 1]
```diff
@@ -133,8 +133,11 @@ func splitMetric(ms, dest pdata.Metric, size int) (int, bool) {
 	case pdata.MetricDataTypeGauge:
 		return splitNumberDataPoints(ms.Gauge().DataPoints(), dest.Gauge().DataPoints(), size)
 	case pdata.MetricDataTypeSum:
+		dest.Sum().SetAggregationTemporality(ms.Sum().AggregationTemporality())
+		dest.Sum().SetIsMonotonic(ms.Sum().IsMonotonic())
 		return splitNumberDataPoints(ms.Sum().DataPoints(), dest.Sum().DataPoints(), size)
 	case pdata.MetricDataTypeHistogram:
+		dest.Histogram().SetAggregationTemporality(ms.Histogram().AggregationTemporality())
```
Comment (mx-psi) [inline processor/batchprocessor/splitmetrics.go:140]: It would help to add a testcase for this, to avoid further regressions

**Review by mx-psi — COMMENTED** [review]
We should add a changelog note for this

File: processor/batchprocessor/splitmetrics.go (hunk 1 above)
Comment (bogdandrutu) [reply processor/batchprocessor/splitmetrics.go:140]: +1

**Review by bogdandrutu — APPROVED** [review]

File: processor/batchprocessor/splitmetrics.go (hunk 1 above)
Comment (bogdandrutu) [reply processor/batchprocessor/splitmetrics.go:140]: @dashpole please do a followup PR.
