### PR TITLE
receiver/prometheus: glue and complete staleness marking for disappearing metrics

### LINKED ISSUE #2961: exporter/prometheusremotewrite: failing Up metric export for Prometheus compliance tests
**Describe the bug**
Coming here from Prometheus compliance tests, TestRemoteWrite/otelcollector/Up fails

**Steps to reproduce**
Run the compliance tests at https://github.com/prometheus/compliance/tree/main/remote_write by
```shell
go test --tags=compliance -v ./
```

**What did you expect to see?**
PASS

**What did you see instead?**
10 out of 14 test failures
```shell
        --- PASS: TestRemoteWrite/otelcollector/Headers (48.87s)
        --- FAIL: TestRemoteWrite/otelcollector/Up (48.95s)
        --- FAIL: TestRemoteWrite/otelcollector/Invalid (48.95s)
        --- FAIL: TestRemoteWrite/otelcollector/Staleness (48.97s)
        --- FAIL: TestRemoteWrite/otelcollector/JobLabel (48.98s)
        --- FAIL: TestRemoteWrite/otelcollector/Counter (48.98s)
        --- PASS: TestRemoteWrite/otelcollector/Timestamp (48.99s)
        --- FAIL: TestRemoteWrite/otelcollector/Summary (48.99s)
        --- FAIL: TestRemoteWrite/otelcollector/RepeatedLabels (10.01s)
        --- FAIL: TestRemoteWrite/otelcollector/NameLabel (10.01s)
        --- PASS: TestRemoteWrite/otelcollector/EmptyLabels (10.01s)
        --- FAIL: TestRemoteWrite/otelcollector/Histogram (10.01s)
        --- PASS: TestRemoteWrite/otelcollector/Gauge (10.02s)
        --- PASS: TestRemoteWrite/otelcollector/SortedLabels (10.02s)
        --- FAIL: TestRemoteWrite/otelcollector/InstanceLabel (10.02s)
```

Here is the listing of failures

- [ ] TestRemoteWrite/otelcollector/Up (48.95s)
- [X] TestRemoteWrite/otelcollector/Headers (48.87s)
- [ ] TestRemoteWrite/otelcollector/Invalid (48.95s)
- [ ] TestRemoteWrite/otelcollector/Staleness (48.97s)
- [ ] TestRemoteWrite/otelcollector/JobLabel (48.98s)
- [ ] TestRemoteWrite/otelcollector/Counter (48.98s)
- [x] TestRemoteWrite/otelcollector/Timestamp (48.99s)
- [ ] TestRemoteWrite/otelcollector/Summary (48.99s)
- [ ] TestRemoteWrite/otelcollector/RepeatedLabels (10.01s)
- [ ] TestRemoteWrite/otelcollector/NameLabel (10.01s)
- [x] TestRemoteWrite/otelcollector/EmptyLabels (10.01s)
- [ ] TestRemoteWrite/otelcollector/Histogram (10.01s)
- [x] TestRemoteWrite/otelcollector/Gauge (10.02s)
- [x] TestRemoteWrite/otelcollector/SortedLabels (10.02s)
- [ ] TestRemoteWrite/otelcollector/InstanceLabel (10.02s)

and the full failure print out is at
```shell
=== CONT  TestRemoteWrite/otelcollector/Up
    up.go:23: 
        	Error Trace:	up.go:23
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/Up
        	Messages:   	found zero samples for up{job="test"}
=== CONT  TestRemoteWrite/otelcollector/NameLabel
=== CONT  TestRemoteWrite/otelcollector/Invalid
    up.go:39: 
        	Error Trace:	up.go:39
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/Invalid
        	Messages:   	found zero samples for up{job="test"}
=== CONT  TestRemoteWrite/otelcollector/EmptyLabels
=== CONT  TestRemoteWrite/otelcollector/Staleness
    staleness.go:43: 
        	Error Trace:	staleness.go:43
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/Staleness
        	Messages:   	found no staleness markers for stale{job="test"}
=== CONT  TestRemoteWrite/otelcollector/Histogram
=== CONT  TestRemoteWrite/otelcollector/JobLabel
    job_label.go:23: 
        	Error Trace:	job_label.go:23
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/JobLabel
        	Messages:   	found zero samples for gauge{job="test"}
=== CONT  TestRemoteWrite/otelcollector/Counter
    counter.go:35: 
        	Error Trace:	counter.go:35
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/Counter
        	Messages:   	found zero samples for {__name__="counter"}
=== CONT  TestRemoteWrite/otelcollector/SortedLabels
=== CONT  TestRemoteWrite/otelcollector/Gauge
=== CONT  TestRemoteWrite/otelcollector/InstanceLabel
=== CONT  TestRemoteWrite/otelcollector/Summary
    helpers.go:30: 
        	Error Trace:	helpers.go:30
        	            				helpers.go:41
        	            				helpers.go:52
        	            				helpers.go:40
        	            				helpers.go:29
        	            				summary.go:30
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Not equal: 
        	            	expected: 6
        	            	actual  : 0
        	Test:       	TestRemoteWrite/otelcollector/Summary
=== CONT  TestRemoteWrite/otelcollector/RepeatedLabels
    labels.go:58: 
        	Error Trace:	labels.go:58
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/RepeatedLabels
        	Messages:   	found zero samples for up{job="test"} = 0
=== CONT  TestRemoteWrite/otelcollector/NameLabel
    labels.go:108: 
        	Error Trace:	labels.go:108
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/NameLabel
        	Messages:   	found zero samples for up{job="test"} = 0
=== CONT  TestRemoteWrite/otelcollector/Histogram
    helpers.go:30: 
        	Error Trace:	helpers.go:30
        	            				helpers.go:41
        	            				helpers.go:52
        	            				helpers.go:40
        	            				helpers.go:29
        	            				histogram.go:25
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestRemoteWrite/otelcollector/Histogram
=== CONT  TestRemoteWrite/otelcollector/InstanceLabel
    helpers.go:21: 
        	Error Trace:	helpers.go:21
        	            				helpers.go:52
        	            				helpers.go:13
        	            				instance_label.go:26
        	            				main_test.go:101
        	            				main_test.go:65
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/InstanceLabel
        	Messages:   	label 'instance' not found
```
 
**What version did you use?**
The latest release [v0.24.0](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.24.0)

**What config did you use?**
N/A

**Environment**
N/A

**Additional context**

### LINKED ISSUE #3413: receiver/prometheus: emit staleness markers on missing metrics after scrapes
Coming here from #2961 and then from the Prometheus RemoteWrite exporter test failures, which set up a Prometheus receiver and then request a scrape then transmit the retrieved scrapes to the pipeline then eventually to the remote write endpoint. When metrics disappear, we need to emit staleness markers aka a special NaN per https://github.com/prometheus/prometheus/blob/39d79c3cfb86c47d6bc06a9e9317af582f1833bb/pkg/value/value.go#L28 of value whose bits from float64 have a value of `StaleNaN uint64 = 0x7ff0000000000002`

### PR DESCRIPTION
**Pull request by odeke-em**
Adds the staleness store to the metricsBuilder and transaction to track when metrics
disappear between scrapes.

Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/3414
Fixes #3413
Fixes #2961

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

File: receiver/prometheusreceiver/internal/metricsbuilder.go [hunk 1]
```diff
@@ -105,6 +108,16 @@ func (b *metricBuilder) AddDataPoint(ls labels.Labels, t int64, v float64) error
 		return fmt.Errorf("invalid sample: non-unique label names: %q", dupLabels)
 	}
 
+	defer func() {
+		if rerr == nil {
+			// Only mark this data point as in the current scrape
+			// iff it isn't a stale metric.
+			if !value.IsStaleNaN(v) {
```
Comment (dashpole) [inline receiver/prometheusreceiver/internal/metricsbuilder.go:115]: nit: you could combine these if-statements to reduce nesting.

**Review by dashpole — APPROVED** [review]

File: receiver/prometheusreceiver/internal/metricsbuilder.go (hunk 1 above)
Comment (odeke-em) [reply receiver/prometheusreceiver/internal/metricsbuilder.go]: Done, thank you @dashpole!

**Comment by odeke-em** [comment]
The test failures were from an exported struct whose name was changed in the past 21 hours from "service.AppSettings" to "service.CollectorSettings" per https://github.com/open-telemetry/opentelemetry-collector/pull/3268

**Comment by odeke-em** [comment]
Kindly /cc-ing @tigrannajaryan @bogdandrutu

**Comment by odeke-em** [comment]
The receiver/prometheusreceiver TestEndToEnd test is quite rigid from 2 years ago, so that'll require me digging as I figure out what it does then retrofit with NaNs for values.

**Comment by tigrannajaryan** [comment]
The build is failing and there are merge conflicts. Please fix.

**Comment by alolita** [comment]
@odeke-em the tests for Windows, Unit tests and build are still failing. Can you please fix?

**Comment by odeke-em** [comment]
@alolita the Windows test failure is unrelated to this change and it is as follows
```shell
--- FAIL: TestDefaultReceivers (0.01s)
    --- FAIL: TestDefaultReceivers/jaeger (0.00s)
        default_receivers_test.go:126: 
            	Error Trace:	default_receivers_test.go:126
            	            				default_receivers_test.go:92
            	Error:      	Received unexpected error:
            	            	failed to bind to gRPC address ":14250": listen tcp :14250: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
            	Test:       	TestDefaultReceivers/jaeger
```

**Comment by odeke-em** [comment]
@tigrannajaryan @bogdandrutu @alolita please take a look.

**Comment by odeke-em** [comment]
@tigrannajaryan @bogdandrutu @alolita please take a look. I skipped one rigid check that was wired into the up metric code and didn't consider staleness markers (they didn't know about them) but it'll be fixed later on by the up metric authors or by myself. The first priority is getting the feature in and then fixing rigid tests after.

File: receiver/prometheusreceiver/internal/staleness_store.go [hunk 2]
```diff
@@ -66,24 +78,40 @@ func (ss *stalenessStore) refresh() {
...
+	_, inPrev := ss.previousHashes[hash]
+	_, inCurrent := ss.currentHashes[hash]
+	return inPrev && !inCurrent
 }
 
 // markAsCurrentlySeen adds lbl to the manifest of labels seen in the current scrape.
 // This method should be called before refresh, but during a scrape whenever labels are encountered.
-func (ss *stalenessStore) markAsCurrentlySeen(lbl labels.Labels) {
-	ss.currentHashes[lbl.Hash()] = true
+func (ss *stalenessStore) markAsCurrentlySeen(lbl labels.Labels, at int64) {
```
Comment (tigrannajaryan) [inline receiver/prometheusreceiver/internal/staleness_store.go:92]: The `at` argument is unclear. Please document or use a more narrow/specialized type to make the intent clear.

File: receiver/prometheusreceiver/internal/staleness_store.go [hunk 3]
```diff
@@ -66,24 +78,40 @@ func (ss *stalenessStore) refresh() {
...
+	ss.mu.Lock()
+	defer ss.mu.Unlock()
+
+	ss.currentHashes[lbl.Hash()] = at
 	ss.current = append(ss.current, lbl)
 }
 
+type staleEntry struct {
+	labels labels.Labels
+	at     int64
```
Comment (tigrannajaryan) [inline receiver/prometheusreceiver/internal/staleness_store.go:102]: Same here, `at` is not clear.

File: receiver/prometheusreceiver/internal/staleness_store.go [hunk 4]
```diff
@@ -66,24 +78,40 @@ func (ss *stalenessStore) refresh() {
...
+}
+
 // emitStaleLabels returns the labels that were previously seen in
 // the prior scrape, but are not currently present in this scrape cycle.
-func (ss *stalenessStore) emitStaleLabels() (stale []labels.Labels) {
+func (ss *stalenessStore) emitStaleLabels() (stale []*staleEntry) {
```
Comment (tigrannajaryan) [inline receiver/prometheusreceiver/internal/staleness_store.go:107]: Nit: this possibly will have better performance due to lower number of allocations.
```suggestion
func (ss *stalenessStore) emitStaleLabels() (stale []staleEntry) {
```

File: receiver/prometheusreceiver/internal/transaction.go [hunk 5]
```diff
@@ -76,6 +76,8 @@ type transaction struct {
 	externalLabels       labels.Labels
 	logger               *zap.Logger
 	obsrecv              *obsreport.Receiver
+	stalenessStore       *stalenessStore
+	startTime            int64
```
Comment (tigrannajaryan) [inline receiver/prometheusreceiver/internal/transaction.go:80]: What is the unit of time? Is this seconds, nanoseconds? Since when? Perhaps use time.Time or a different stronger type?

**Review by tigrannajaryan — COMMENTED** [review]
I am not familiar with the expected logic for staleness markers so did superficial review of the code only. I trust Prometheus SIG experts to ensure the logic is right.

File: receiver/prometheusreceiver/internal/staleness_store.go (hunk 2 above)
Comment (odeke-em) [reply receiver/prometheusreceiver/internal/staleness_store.go:92]: `at` is the `time at which the point was obtained` but perhaps let me use `timeMs`

File: receiver/prometheusreceiver/internal/staleness_store.go (hunk 4 above)
Comment (odeke-em) [reply receiver/prometheusreceiver/internal/staleness_store.go:107]: The opposite happens though, as these entries are moved around, a pointer is kept around while values will be copied, which will cause more allocations.

File: receiver/prometheusreceiver/internal/transaction.go (hunk 5 above)
Comment (odeke-em) [reply receiver/prometheusreceiver/internal/transaction.go:80]: No need for a stronger type given the internal type that Prometheus uses. I'll modify the variable name to startTimeMs.

File: receiver/prometheusreceiver/internal/staleness_store.go (hunk 3 above)
Comment (odeke-em) [reply receiver/prometheusreceiver/internal/staleness_store.go]: Done, thanks

File: receiver/prometheusreceiver/internal/staleness_store.go (hunk 4 above)
Comment (tigrannajaryan) [reply receiver/prometheusreceiver/internal/staleness_store.go:107]: I was curious so did a quick benchmark :-)

```go
type staleEntry struct {
	labels   labels.Labels
	seenAtMs int64
}

func emitStaleLabelsByPtr() (stale []*staleEntry) {
	var labels labels.Labels
	for i := 0; i < 10; i++ {
		stale = append(stale, &staleEntry{seenAtMs: int64(i), labels: labels})
	}
	return stale
}

func emitStaleLabelsByVal() (stale []staleEntry) {
	var labels labels.Labels
	for i := 0; i < 10; i++ {
		stale = append(stale, staleEntry{seenAtMs: int64(i), labels: labels})
	}
	return stale
}

func BenchmarkByPtr(b *testing.B) {
	for i := 0; i < b.N; i++ {
		emitStaleLabelsByPtr()
	}
}

func BenchmarkByVal(b *testing.B) {
	for i := 0; i < b.N; i++ {
		emitStaleLabelsByVal()
	}
}
```

Results:
```
$ go test -bench . --benchmem
goos: darwin
goarch: amd64
pkg: github.com/tigrannajaryan/gotest
cpu: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
BenchmarkByPtr-8         2093342               618.8 ns/op           568 B/op         15 allocs/op
BenchmarkByVal-8         2512652               403.6 ns/op           992 B/op          5 allocs/op
PASS
ok      github.com/tigrannajaryan/gotest        5.652s
```

I tried to approximate the code in this PR as best as I could while keeping it minimal, so hopefully it the results are representative.

It appears by value is a bit faster with less allocations, but the difference is negligible unless it is in some hot path.

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Status checks don't finish, can't merge. Will close/open to see if it helps.

**Review by rakyll — APPROVED** [review]

File: receiver/prometheusreceiver/internal/staleness_store.go (hunk 4 above)
Comment (odeke-em) [reply receiver/prometheusreceiver/internal/staleness_store.go:107]: Thanks @tigrannajaryan! The copying that happens is when for example any of those values is passed into a function or moved into a new scope; by value they'll ALWAYS be copied byte by byte which is something we don't want to happen and cause memory bloat. Actually one time while doing an inspection I noticed that the collector has a whole bunch of these patterns e.g.
```go
package main

type st struct {
   id int
   name string
   bloat [1024]byte
}

func foo(s st) {
    // Do something with s.
    ...
}

func fooPtr(s *st) {
    // Do something with s.
    ...
}

func main() {
     sl := []st{{id: 0, name: "a"}, {id: 1, name: "b"}}
    for i := 0; i < 10; i++ {
          for _, s := range sl {
             foo(s) // Copy byte by byte will ALWAYS happen here.. If the struct is big, lots of memory bloat.
          }
     }

    slp := []*st{{id: 0, name: "a"}, {id: 1, name: "b"}}
    for i := 0; i < 10; i++ {
          for _, s := range slp {
              fooPtr(s) // No need to copy over memory here
          }
     }
}
```

**Comment by odeke-em** [comment]
Thanks @tigrannajaryan and @rakyll! The Windows test is spurious but the other failure let me examine what's tripping it. Should shortly pass.

**Comment by odeke-em** [comment]
> Thanks @tigrannajaryan and @rakyll! The Windows test is spurious but the other failure let me examine what's tripping it. Should shortly pass.

Yup it was a data race from code unrelated to this PR, that existed because Prometheus's code would modify pReceiver concurrently with pReceiver.Start being invoked.

**Comment by odeke-em** [comment]
Alright @tigrannajaryan @rakyll @alolita now all the related code and tests pass 🎉! The contrib failure is unrelated to this change

File: receiver/prometheusreceiver/internal/staleness_store.go (hunk 4 above)
Comment (tigrannajaryan) [reply receiver/prometheusreceiver/internal/staleness_store.go:107]: Yes, it depends on size of the struct. For sufficiently small structs copying can overall be faster since individual allocations are expensive. We see it in the benchmark I posted.

**Comment by odeke-em** [comment]
Thank you all for the patient reviews and for your time!
