### PR TITLE
receiver/prometheus: reject datapoints with duplicate label keys

### LINKED ISSUE #3407: receiver/prometheus: data points with duplicate label keys MUST be rejected
Coming here from https://github.com/open-telemetry/wg-prometheus/issues/44, the Prometheus Remote Write compliance tests were failing, but that was a red herring about exporter/prometheusremotewrite because it setups a Prometheus receiver on the otelcollector and then waits for the Prometheus Remote Write exporter to push metrics.

@brian-brazil and @roidelapluie let me know that newer Prometheus rejects these data types. This issue is to track that we need to reject such data points. PR coming up soon.

### PR DESCRIPTION
**Pull request by odeke-em**
As of Prometheus 2.16.0 (released on 2020-02-13), datapoints with
duplicate label keys MUST be rejected and the Prometheus RemoteWrite
exporter tests were failing, but that was a red herring as the
real issue was really in the receiver.

Fixes https://github.com/open-telemetry/wg-prometheus/issues/44
Fixes #3407

### CODE REVIEW

**Comment by odeke-em** [comment]
And the Prometheus RemoteWrite Exporter RepeatedLabels test now passes :-)
```shell
$ go test --tags=compliance -v ./
=== RUN   TestRemoteWrite
=== RUN   TestRemoteWrite/otelcollector
=== RUN   TestRemoteWrite/otelcollector/RepeatedLabels
=== PAUSE TestRemoteWrite/otelcollector/RepeatedLabels
=== CONT  TestRemoteWrite/otelcollector/RepeatedLabels
--- PASS: TestRemoteWrite (10.02s)
    --- PASS: TestRemoteWrite/otelcollector (0.00s)
        --- PASS: TestRemoteWrite/otelcollector/RepeatedLabels (10.01s)
PASS
ok  	github.com/prometheus/compliance/remote_write	11.025s
```

**Comment by dashpole** [comment]
Would updating our imported version of prometheus fix this?  Or is this validation done outside of the prom libraries we use?

**Comment by odeke-em** [comment]
>Would updating our imported version of prometheus fix this? Or is this validation done outside of the prom libraries we use?

I don't think that would change much; the burden is on us who have a custom .AddPoint method, to perform this validation when the Prometheus receiver gets a datapoint sent into it.

**Comment by dashpole** [comment]
Yep, you are correct.  The logic in prometheus is within in the Appender implementation, so we need to implement it ourselves.

File: receiver/prometheusreceiver/internal/metricsbuilder.go [hunk 1]
```diff
@@ -87,6 +88,23 @@ func (b *metricBuilder) matchStartTimeMetric(metricName string) bool {
...
+	dupLabels := make([]string, 0, len(ls))
+	for _, label := range ls {
+		if _, ok := seen[label.Name]; ok {
+			dupLabels = append(dupLabels, label.Name)
+		}
+		seen[label.Name] = true
+	}
+	if len(dupLabels) != 0 {
+		sort.Strings(dupLabels)
+		return fmt.Errorf("invalid sample: non-unique label names: %q", dupLabels)
```
Comment (dashpole) [inline receiver/prometheusreceiver/internal/metricsbuilder.go:105]: nit: it might be nice to seek the label keys and values, instead of just the name for debugging.

**Review by dashpole — APPROVED** [review]

File: receiver/prometheusreceiver/internal/metricsbuilder.go (hunk 1 above)
Comment (odeke-em) [reply receiver/prometheusreceiver/internal/metricsbuilder.go:105]: Good idea, I debated that too, but Prometheus doesn't print out the values though hence just tried to mirror what they do; Also printing out the Name:Value after printing out a list of keys, might make for huge errors. The Label values might be long, which sure would require newlines, but lots of rabbit holes to go into. Perhaps we can consider this in the future if someone asks for it?

Comment (dashpole) [reply receiver/prometheusreceiver/internal/metricsbuilder.go:105]: Works for me.  Thanks for investigating.

Comment (odeke-em) [reply receiver/prometheusreceiver/internal/metricsbuilder.go:105]: Thanks for raising it!

File: receiver/prometheusreceiver/internal/metricsbuilder.go [hunk 2]
```diff
@@ -87,6 +88,23 @@ func (b *metricBuilder) matchStartTimeMetric(metricName string) bool {
...
 func (b *metricBuilder) AddDataPoint(ls labels.Labels, t int64, v float64) error {
+	// Any datapoint with duplicate labels MUST be rejected per:
+	// * https://github.com/open-telemetry/wg-prometheus/issues/44
+	// * https://github.com/open-telemetry/opentelemetry-collector/issues/3407
+	// as Prometheus rejects such too as of version 2.16.0, released on 2020-02-13.
+	seen := make(map[string]bool)
+	dupLabels := make([]string, 0, len(ls))
+	for _, label := range ls {
+		if _, ok := seen[label.Name]; ok {
+			dupLabels = append(dupLabels, label.Name)
```
Comment (Aneurysm9) [inline receiver/prometheusreceiver/internal/metricsbuilder.go:99]: Do we need to include the full list of duplicate labels in the error returned or can we simply short circuit here once we know there is at least one duplicate label?

**Comment by odeke-em** [comment]
I becomes a UX debugging nightmare if you have to clear one duplicate,
redeploy your process then onto the next one. It is trivial  for us to list
all the duplicate label names, and get a much better user experience.

File: receiver/prometheusreceiver/internal/metricsbuilder.go (hunk 2 above)
Comment (odeke-em) [reply receiver/prometheusreceiver/internal/metricsbuilder.go:99]: I becomes a UX debugging nightmare if you have to clear one duplicate, redeploy your process then onto the next one. It is trivial for us to list all the duplicate label names, and get a much better user experience.

**Review by Aneurysm9 — APPROVED** [review]

**Review by rakyll — APPROVED** [review]

**Comment by odeke-em** [comment]
Kindly cc-ing @tigrannajaryan.

**Review by bogdandrutu — APPROVED** [review]
