### PR TITLE
Fix --set flag

### LINKED ISSUE #1907: Fix --set flag
Support for `--set` flag has been reverted in https://github.com/open-telemetry/opentelemetry-collector/issues/1897. 

The referenced issue should be fixed and support for `--set` flag added back.

### PR DESCRIPTION
**Pull request by joe-elliott**
**Description:** 
Re-adds the --set parameter in a way that works with `{}` being used in configs.

**Link to tracking Issue:** <Issue number if applicable>
Fixes #1907 

**Testing:**
The original tests were added along with the addition of the following:

```
extensions:
  health_check: {}
```

This failed the previous tests, but now passes.

**Documentation:**

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@pavolloffay can you review please?

**Comment by pavolloffay** [comment]
Here is the revert https://github.com/open-telemetry/opentelemetry-collector/pull/1905 and the original PR https://github.com/open-telemetry/opentelemetry-collector/pull/1640/files

**Comment by pavolloffay** [comment]
@joe-elliott could you highlight what fixed the issue?

**Comment by joe-elliott** [comment]
@pavolloffay 
Previously it was iterating through `.AllKeys()` in the config file viper and calling `.Set()` on each one to force them into viper's config "override".  This allowed the `--set` values to nicely merge with the config values.  However, `.AllKeys()` just failed to return a key with an empty object like :  `healthcheck: {}` and so it was never set.

By iterating through all keys and only calling `.Set` on the root keys we are preserving the entire viper config object faithfully.
https://github.com/open-telemetry/opentelemetry-collector/pull/2162/files#diff-2a9451c3c8352620ac89fc278d2e47f08ce3fa76d427cb1694ff8119003caa9fR68-R77

I also attempted other changes like `.MergeConfig()` and can confirm they will not work for this.

**Comment by joe-elliott** [comment]
To continue this conversation.  If your file looks like this:

```
a: {}
b:
  c: 2
  d:
```

If you load this with viper and run `AllSettings()` you will get the following structure back:
```
b:
  c: 2
```

If you run `AllKeys()` and log each one you get the following keys:
```
b.c
b.d
```

Viper does not enumerate keys that are empty objects but it will enumerate nil keys.  By calling `Get()` on the root keys only we are able to faithfully reconstruct the original config in the viper overrides so it will nicely merge with the `--set` params.

@pavolloffay thoughts?

**Comment by joe-elliott** [comment]
@jpkrohling do you mind taking a look?

**Comment by tigrannajaryan** [comment]
> @pavolloffay
> Previously it was iterating through `.AllKeys()` in the config file viper and calling `.Set()` on each one to force them into viper's config "override". This allowed the `--set` values to nicely merge with the config values. However, `.AllKeys()` just failed to return a key with an empty object like : `healthcheck: {}` and so it was never set.
> 
> By iterating through all keys and only calling `.Set` on the root keys we are preserving the entire viper config object faithfully.
> https://github.com/open-telemetry/opentelemetry-collector/pull/2162/files#diff-2a9451c3c8352620ac89fc278d2e47f08ce3fa76d427cb1694ff8119003caa9fR68-R77
> 
> I also attempted other changes like `.MergeConfig()` and can confirm they will not work for this.



> To continue this conversation. If your file looks like this:
> 
> ```
> a: {}
> b:
>   c: 2
>   d:
> ```
> 
> If you load this with viper and run `AllSettings()` you will get the following structure back:
> 
> ```
> b:
>   c: 2
> ```
> 
> If you run `AllKeys()` and log each one you get the following keys:
> 
> ```
> b.c
> b.d
> ```
> 
> Viper does not enumerate keys that are empty objects but it will enumerate nil keys. By calling `Get()` on the root keys only we are able to faithfully reconstruct the original config in the viper overrides so it will nicely merge with the `--set` params.
> 
> @pavolloffay thoughts?

@joe-elliott these ^^^^ are very nice explanations. Would you be able to add them as comments to the relevant parts of the code? Perhaps drop the "previously" part and keep the part that describes how it works now and most importantly why it works correctly.

File: service/service_test.go [hunk 1]
```diff
@@ -137,7 +144,7 @@ func TestApplication_StartAsGoRoutine(t *testing.T) {
 
 	params := Parameters{
 		ApplicationStartInfo: componenttest.TestApplicationStartInfo(),
-		ConfigFactory: func(v *viper.Viper, factories component.Factories) (*configmodels.Config, error) {
+		ConfigFactory: func(v *viper.Viper, command *cobra.Command, factories component.Factories) (*configmodels.Config, error) {
```
Comment (jpkrohling) [inline service/service_test.go:147]:
```suggestion
		ConfigFactory: func(_ *viper.Viper, _ *cobra.Command, factories component.Factories) (*configmodels.Config, error) {
```

You don't seem to require `v` nor `command` there.

File: service/service_test.go [hunk 2]
```diff
@@ -412,7 +419,7 @@ func createExampleApplication(t *testing.T) *Application {
 
 	app, err := New(Parameters{
 		Factories: factories,
-		ConfigFactory: func(v *viper.Viper, factories component.Factories) (c *configmodels.Config, err error) {
+		ConfigFactory: func(v *viper.Viper, cmd *cobra.Command, factories component.Factories) (c *configmodels.Config, err error) {
```
Comment (jpkrohling) [inline service/service_test.go:422]:
```suggestion
		ConfigFactory: func(_ *viper.Viper, _ *cobra.Command, factories component.Factories) (c *configmodels.Config, err error) {
```

File: service/testdata/otelcol-config.yaml [hunk 3]
```diff
@@ -17,7 +17,7 @@ processors:
   batch:
 
 extensions:
-  health_check:
```
Comment (jpkrohling) [inline service/testdata/otelcol-config.yaml:20]: From what I understood, it's still OK to have nil here instead of empty. If that's the case, keep this as nil, as a proof that this change didn't break compat with previous versions.

File: testbed/testbed/otelcol_runner.go [hunk 4]
```diff
@@ -104,7 +105,7 @@ func (ipp *InProcessCollector) Start(args StartParams) error {
 			Version:  version.Version,
 			GitHash:  version.GitHash,
 		},
-		ConfigFactory: func(v *viper.Viper, factories component.Factories) (*configmodels.Config, error) {
+		ConfigFactory: func(v *viper.Viper, cmd *cobra.Command, factories component.Factories) (*configmodels.Config, error) {
```
Comment (jpkrohling) [inline testbed/testbed/otelcol_runner.go:108]: Same here :-)

File: service/set_flag.go [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+	if err := viperFlags.ReadConfig(b); err != nil {
+		return fmt.Errorf("failed to read set flag config: %v", err)
+	}
+
+	// Viper implementation of v.MergeConfig(io.Reader) or v.MergeConfigMap(map[string]interface)
+	// does not work properly.  This is b/c if it attempts to merge into a nil object it will fail here
+	// https://github.com/spf13/viper/blob/3826be313591f83193f048520482a7b3cf17d506/viper.go#L1709
+
+	// The workaround is to call v.Set(string, interface) on all root properties from the config file
+	// this will correctly preserve the original config and set them up for viper to overlay them
```
Comment (jpkrohling) [inline service/set_flag.go:67]: @tigrannajaryan I think this is the explanation you asked for, right?

**Review by jpkrohling — APPROVED** [review]
LGTM. There are a couple of minor improvements that could be made, but those can be safely ignored...

File: service/testdata/otelcol-config.yaml (hunk 3 above)
Comment (joe-elliott) [reply service/testdata/otelcol-config.yaml:20]: Yes, nil is fine here as well as empty object.  The problem is that empty object was not working and was not being tested for.  With my changes this file now tests both empty object and nil object:

```

**Review by jpkrohling — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

File: service/set_flag.go (hunk 5 above)
Comment (joe-elliott) [reply service/set_flag.go]: I have improved the explanation with some more details about why we are specifically extracting and setting the root keys.

**Comment by joe-elliott** [comment]
I believe I've addressed all comments and improved the in code comments regarding the behavior of viper and why we are setting the root keys.

I am getting a failed contribtest:

```
--- FAIL: TestNewLogsExporter (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbde2df]
```
Could this be due to changes I made?  should I dig into this?

File: service/set_flag.go (hunk 5 above)
Comment (tigrannajaryan) [reply service/set_flag.go]: Looks good, thank you.

**Comment by tigrannajaryan** [comment]
> I am getting a failed contribtest:
> 
> ```
> --- FAIL: TestNewLogsExporter (0.00s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbde2df]
> ```
> 
> Could this be due to changes I made? should I dig into this?

Unlikely that your change could cause this. Looks like a bug in TestNewLogsExporter.

**Comment by tigrannajaryan** [comment]
@joe-elliott please rebase from latest master.

File: service/service.go [hunk 6]
```diff
@@ -103,26 +103,37 @@ type Parameters struct {
...
 }
 
 // ConfigFactory creates config.
-type ConfigFactory func(v *viper.Viper, factories component.Factories) (*configmodels.Config, error)
-
-// FileLoaderConfigFactory implements ConfigFactory and it creates configuration from file.
-func FileLoaderConfigFactory(v *viper.Viper, factories component.Factories) (*configmodels.Config, error) {
+// The ConfigFactory implementation should call AddSetFlagProperties to enable configuration passed via `--set` flag.
+// Viper and command instances are passed from the Application.
+// The factories also belong the Application and are equal to the factories passed via Parameters.
```
[the remark this answers is not in the document]
Comment (joe-elliott) [reply service/service.go:117]: This comment was from @pavolloffay 's original PR, but I believe you are correct.  Fixing!

**Comment by joe-elliott** [comment]
Rebased but now getting a build error on contrib:
```
# github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/translator [github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/translator.test]
translator/segment_test.go:743:6: val1.InitEmpty undefined (type pdata.AttributeValue has no field or method InitEmpty)
translator/segment_test.go:746:6: val2.InitEmpty undefined (type pdata.AttributeValue has no field or method InitEmpty)
```

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
> Rebased but now getting a build error on contrib:
> 
> ```
> # github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/translator [github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/translator.test]
> translator/segment_test.go:743:6: val1.InitEmpty undefined (type pdata.AttributeValue has no field or method InitEmpty)
> translator/segment_test.go:746:6: val2.InitEmpty undefined (type pdata.AttributeValue has no field or method InitEmpty)
> ```

This is expected, ignore it.
