### PR TITLE
exporter/prometheusremotewriter: sort Sample by Timestamp to avoid out of order errors

### LINKED ISSUE #2315: Prometheus remote write exporter is failing with "out of order samples" under load
The Prometheus remote writer exporter is failing with the following errors under load:

* out of order samples
* duplicate sample for timestamp

These issues can be potentially caused by the concurrent writes at https://github.com/open-telemetry/opentelemetry-collector/blob/a16c599d26b6db7a95489568ca890b06380463cc/exporter/prometheusremotewriteexporter/exporter.go and/or samples produced for the same metric type at the same replica of the target without pod labels.

I'm consistently able to reproduce the problem in a Kubernetes cluster. To reproduce, run a single replica of the collector and try to collect from 50/60 targets or more and produce 40-50 metrics at each target .

### PR DESCRIPTION
**Pull request by odeke-em**
Ensures that before a prompb.WriteRequest is created, that the
TimeSeries contained have their Sample values sorted chronologically
by Prometheus to avoid out of order errors reported by Prometheus
barfing.

Thanks to @rakyll for a reproducer and for diagnosing the problem, which
helped distill the issue from a very complex setup that required super
expensive Kubernetes clusters with many replicas, but essentially the problem
became more apparently when the number of TimeSeries grew.

It is important to note that the presence of such a bug signifies that
with a large number of replicas are being scraped from, this stalls
scraping and takes a long time which means that targets scraped in a
round-robin fashion experience staleness when many. This might be even
more reasons for setups to adopt a push model as opposed to scrape
endpoints.

Fixes #2315
Fixes https://github.com/open-telemetry/wg-prometheus/issues/10

### CODE REVIEW

File: exporter/prometheusremotewriteexporter/helper.go [hunk 1]
```diff
@@ -476,10 +476,26 @@ func addSingleDoubleSummaryDataPoint(pt *otlp.DoubleSummaryDataPoint, metric *ot
...
+	return tsArray
+}
+
 func convertTimeseriesToRequest(tsArray []prompb.TimeSeries) *prompb.WriteRequest {
 	// the remote_write endpoint only requires the timeseries.
 	// otlp defines it's own way to handle metric metadata
 	return &prompb.WriteRequest{
-		Timeseries: tsArray,
+		// First things first, we need to ensure that the samples per time series are sorted by Timestamp.
+		// This ensures that we don't produce out of order problems
```
Comment (bogdandrutu) [inline exporter/prometheusremotewriteexporter/helper.go:495]: I think it is better to avoid comments like "we do x":

// Prometheus required time series to be sorted, in order to ensure no out of order data.
// See:
// ...

**Review by bogdandrutu — APPROVED** [review]

File: exporter/prometheusremotewriteexporter/helper.go (hunk 1 above)
Comment (odeke-em) [reply exporter/prometheusremotewriteexporter/helper.go]: Done, thank you @bogdandrutu!

File: exporter/prometheusremotewriteexporter/helper.go [hunk 2]
```diff
@@ -476,10 +476,25 @@ func addSingleDoubleSummaryDataPoint(pt *otlp.DoubleSummaryDataPoint, metric *ot
 	}
 }
 
+func orderBySampleTimestamp(tsArray []prompb.TimeSeries) []prompb.TimeSeries {
+	for i := range tsArray {
+		sL := tsArray[i].Samples
+		sort.Slice(sL, func(i, j int) bool {
+			return sL[i].Timestamp < sL[j].Timestamp
+		})
+		tsArray[i].Samples = sL
```
Comment (bogdandrutu) [inline exporter/prometheusremotewriteexporter/helper.go:485]: Unnecessary, sort does sorting inplace so the slice does not change. (ptr, len, cap will be the same)

Comment (odeke-em) [reply exporter/prometheusremotewriteexporter/helper.go]: Thank you. Indeed, unnecessary overkill after a prior change that I forgot to remove. Please take a look again.

**Comment by rakyll** [comment]
I've been testing the exporter with this change and can't reproduce the bug anymore. I'm using relabel_configs to have pod name in the samples to avoid the duplicates that might be potentially coming from the replicas of my app.

**Comment by rakyll** [comment]
I spoke too soon, filed https://github.com/open-telemetry/opentelemetry-collector/issues/2949 for a follow up.
