### PR TITLE
Replace log.Fatal with returning errors to be handled by caller

### LINKED ISSUE #619: log.Fatal vs returning errors
Collector codebase currently extensively uses `log.Fatal` calls at any stage of the startup. 
e.g. [service.go](https://github.com/open-telemetry/opentelemetry-collector/blob/master/service/service.go) currently contains 12 such calls.

While there is nothing wrong with terminating application when it fails to initialize properly, the number of points triggering termination should be limited.

One particular case where this can cause issues is if at any stage of application startup we use `defer` statement, which doesn't get called upon `os.Exit()` (see https://golang.org/pkg/os/#Exit) invoked by `log.Fatal`.

Also, if someone is using Collector's code programmatically (see #601 for example), they may prefer to handle fatal errors themselves and decide if their application requires immediate termination.

I suggest a rule that `log.Fatal` (or other means of terminating application) should not be used outside the `main` package (and tests).

This can easily be fixed via replacing `log.Fatal` calls with returning errors in https://github.com/open-telemetry/opentelemetry-collector/blob/ea761567bdb475ef86e89416312db1df9db7e809/service/service.go#L145 and similar places.

---

See https://dave.cheney.net/2015/11/05/lets-talk-about-logging
> Don’t log at fatal level, prefer instead to return an error to the caller. If the error bubbles all the way up to main.main then that is the right place to handle any cleanup actions before exiting.

### PR DESCRIPTION
**Pull request by nilebox**
**Description:** 
Fixes #619 - Replacing usages of `log.Fatal` with returning errors in `Application`, to be handled by the caller of `Application.Start()`.

**Link to tracking Issue:** #619

**Testing:** No tests failing

**Documentation:** Updated `CONTRIBUTING.md` to document the rules for process termination.

### CODE REVIEW

File: service/service.go [hunk 1]
```diff
@@ -322,10 +346,15 @@ func (app *Application) shutdownPipelines() {
 	app.builtReceivers.StopAll()
 
 	app.logger.Info("Stopping processors...")
-	app.builtPipelines.ShutdownProcessors(app.logger)
+	err := app.builtPipelines.ShutdownProcessors(app.logger)
+	if err != nil {
```
Comment (nilebox) [inline service/service.go]: This one is tricky: we previously ignored the error, which means that we proceeded to `ShutdownAll`.
What would be the correct behavior?

File: service/service.go [hunk 2]
```diff
@@ -367,12 +407,18 @@ func (app *Application) execute() {
 	app.logger.Info("Starting shutdown...")
 
 	app.notifyPipelineNotReady()
-	app.shutdownPipelines()
+
+	err = app.shutdownPipelines()
+	if err != nil {
+		return err
```
Comment (nilebox) [inline service/service.go]: Similar question here: shall we proceed and combine & return all accumulated errors in the end?

File: service/service.go (hunk 1 above)
Comment (nilebox) [reply service/service.go]: Also I've noticed that currently we return error as soon as one processor failed to shutdown:
https://github.com/open-telemetry/opentelemetry-collector/blob/91728bc8ce02f78886a52303de7509a71c1fee29/service/builder/pipelines_builder.go#L65-L69

This seems like a bug to me, we should proceed to shutdown remaining processors instead, and return collected errors at the very end.

Comment (nilebox) [reply service/service.go]: See #628

Comment (nilebox) [reply service/service.go]: Fixed.

File: service/service.go (hunk 2 above)
Comment (nilebox) [reply service/service.go]: Fixed.

File: service/service.go [hunk 3]
```diff
@@ -313,19 +338,36 @@ func (app *Application) notifyPipelineNotReady() {
...
+	}
+
+	if len(errs) != 0 {
+		return oterr.CombineErrors(errs)
+	}
+
+	return nil
 }
 
 func (app *Application) shutdownExtensions() {
```
Comment (nilebox) [inline service/service.go]: Should this function also return errors rather than `app.logger.Warn(...)`?
Or switch other shutdown functions to logging as well for consistency?

Comment (pjanotti) [reply service/service.go]: For consistency, it should return errors too.

File: service/builder/exporters_builder.go [hunk 4]
```diff
@@ -88,10 +88,19 @@ func (exps Exporters) StartAll(logger *zap.Logger, host component.Host) error {
 }
 
 // ShutdownAll stops all exporters.
-func (exps Exporters) ShutdownAll() {
+func (exps Exporters) ShutdownAll() error {
+	var errs []error
 	for _, exp := range exps {
-		exp.Shutdown()
+		err := exp.Shutdown()
```
[the remark this answers is not in the document]
Comment (nilebox) [reply service/builder/exporters_builder.go]: Agreed. I can send a separate PR with that change, since it will require adding `sync.WaitGroup` and running shutdown in goroutines, not just a mechanical change.

File: service/service.go (hunk 3 above)
Comment (nilebox) [reply service/service.go]: Done.

File: cmd/otelcol/main.go [hunk 5]
```diff
@@ -25,14 +25,14 @@ import (
...
+	handleErr := func(message string, err error) {
 		if err != nil {
-			log.Fatalf("Failed to run the service: %v", err)
+			log.Fatalf("%s: %v", message, err)
 		}
 	}
 
 	factories, err := defaults.Components()
-	handleErr(err)
+	handleErr("Failed to build default components", err)
```
Comment (nilebox) [inline cmd/otelcol/main.go]: Here and below - changed fatal error message to be more specific to the stage, as requested by @pjanotti .

File: service/builder/exporters_builder.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (tigrannajaryan) [reply service/builder/exporters_builder.go]: I agree, let's do it separately.

Technically the entire pipelines can be shutdown concurrently, but we need to carefully track exporters that are attached to the same pipeline to only shutdown once. Likewise for receivers attached to the same pipeline.
