### PR TITLE
fix: gracefully handle process metrics registration failure on unsupported OSes

### LINKED ISSUE #14307: Internal telemetry breaks compiled binaries on unsupported OSes
### Component(s)

service

### What happened?

**Describe the bug**
Custom compiled binaries for AIX (and other unsupported OSes) do not start. The following error is thrown when starting the collector:

```shell
Error: failed to register process metrics: not implemented yet
2025/12/17 13:32:42 collector server run finished with error: failed to register process metrics: not implemented yet
```

The root cause is that the gopsutil library does not support AIX, however setting the following in the `service` config should disable internal telemetry and suppress this error:

```yaml
telemetry:
    metrics:
      level: none
```

This appears to be a regression of [this change](https://github.com/open-telemetry/opentelemetry-collector/pull/12615), affecting all releases starting with 0.136.0.

**Steps to reproduce**
Compile a recent version of the OTel collector (anything 0.136.0 or later) with `GOOS=aix GOARCH=ppc64`. I used the following minimal builder config to avoid other compatibility issues while testing:

```yaml
dist:
  name: otelcol-aix
  description: OpenTelemetry collector built for AIX
  output_path: ./otelcol-aix
  version: 0.142.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.142.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.142.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.142.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.142.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/datadogsemanticsprocessor v0.142.0
 
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.142.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.142.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver v0.142.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.142.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filestatsreceiver v0.142.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.142.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.142.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.47.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.47.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.47.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.47.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.47.0

extensions:
- gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.142.0
```

After building the executable, copy to the AIX host, add execute permissions, and run with a minimal configuration shown below.

**What did you expect to see?**
Setting `service.telemetry.metrics.level: none` should prevent the `failed to register process metrics: not implemented yet` error message and allow the collector to start normally.

**What did you see instead?**
The collector fails to start with the following output:

```shell
2025-12-17T13:32:42.931-0600    info    otelconftelemetry/metrics.go:25 Internal metrics telemetry disabled     {"resource": {"service.instance.id": "92ad75d1-ae5f-4752-a41c-274e9a4e8a06", "service.name": "otelcol-aix", "service.version": "0.142.0"}}
2025-12-17T13:32:42.932-0600    error   service@v0.142.0/service.go:176 error found during service initialization       {"resource": {"service.instance.id": "92ad75d1-ae5f-4752-a41c-274e9a4e8a06", "service.name": "otelcol-aix", "service.version": "0.142.0"}, "error": "failed to register process metrics: not implemented yet"}
go.opentelemetry.io/collector/service.New.func2
        go.opentelemetry.io/collector/service@v0.142.0/service.go:176
go.opentelemetry.io/collector/service.New
        go.opentelemetry.io/collector/service@v0.142.0/service.go:241
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents
        go.opentelemetry.io/collector/otelcol@v0.142.0/collector.go:212
go.opentelemetry.io/collector/otelcol.(*Collector).Run
        go.opentelemetry.io/collector/otelcol@v0.142.0/collector.go:330
go.opentelemetry.io/collector/otelcol.NewCommand.func1
        go.opentelemetry.io/collector/otelcol@v0.142.0/command.go:39
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.10.2/command.go:1015
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.10.2/command.go:1148
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.10.2/command.go:1071
main.runInteractive
        go.opentelemetry.io/collector/cmd/builder/main.go:58
main.run
        go.opentelemetry.io/collector/cmd/builder/main_others.go:10
main.main
        go.opentelemetry.io/collector/cmd/builder/main.go:51
runtime.main
        runtime/proc.go:285
Error: failed to register process metrics: not implemented yet
2025/12/17 13:32:42 collector server run finished with error: failed to register process metrics: not implemented yet
```

### Collector version

0.142.0

## Environment
OS: AIX 7.3
Compiler(if manually compiled): go1.25.5, ocb 0.142.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    scrapers:
      cpu:
      disk:

processors:
  batch:
    timeout: 10s

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    metrics:
      level: none

  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [debug]
```

### Log output

```shell

```

### Additional context

Because this is a regression, there is a previous closed issue reported: https://github.com/open-telemetry/opentelemetry-collector/issues/12098

Issue was fixed in [this PR](https://github.com/open-telemetry/opentelemetry-collector/pull/12615).

Fix is present in service.go [v0.135.0](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.135.0/service/service.go#L196), missing in [v0.136.0](https://github.com/open-telemetry/opentelemetry-collector/blob/a2b837e7af3f3ca67c8c7dd725f3b8867e85d27a/service/service.go#L226).

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by EdgeN8v**
## Description
This PR addresses the crash issue reported in #14307 where the collector fails to start on unsupported operating systems (e.g., AIX) due to `RegisterProcessMetrics` returning an error.

Instead of failing the service initialization, this change logs a warning and allows the collector to continue starting, ensuring that core functionality remains available even if process metrics cannot be collected.

## Link to Issue
Fixes #14307

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: service/service.go [hunk 1]
```diff
@@ -235,8 +235,9 @@ func New(ctx context.Context, set Settings, cfg Config) (_ *Service, resultErr e
 	}
 
 	if err := proctelemetry.RegisterProcessMetrics(srv.telemetrySettings); err != nil {
-		return nil, fmt.Errorf("failed to register process metrics: %w", err)
-	}
+        // Fix for #14307: Log error instead of failing on unsupported OSes (e.g. AIX)
+        srv.telemetrySettings.Logger.Warn("Failed to register process metrics", zap.Error(err))
```
Comment (axw) [inline service/service.go]: I'm not a fan of this. Maybe it's fine for AIX, but for supported operating systems, I think this warrants failing fast - something is probably very wrong if this fails on a supported OS.

Is it possible to change proctelemetry to be a no-op on operating systems that don't have support for the process metrics?

Comment (EdgeN8v) [reply service/service.go]: Thanks for the feedback @axw! I completely agree with the "fail fast" principle for supported OSes. Swallowing the error on Linux/Windows could hide critical configuration issues.

To address this, I plan to modify the logic to explicitly check the OS. We can skip the process metrics registration specifically for AIX (and potentially other unsupported OSes), while keeping the strict error handling for supported ones.

Something like this:

```go
// Only register process metrics on supported OSes to avoid startup failures on AIX
if runtime.GOOS != "aix" {
    if err := srv.telemetrySettings.RegisterProcessMetrics(); err != nil {
        return err
    }
}

Comment (axw) [reply service/service.go]: That works for me.

Comment (EdgeN8v) [reply service/service.go]: Done. I've updated the PR to implement the OS check as discussed (skipping only on AIX, failing fast on others). Ready for review!

**Review by axw — APPROVED** [review]

**Comment by axw** [comment]
@EdgeN8v please fix CI. It seems the code is not formatted properly - you should be able to fix that by running `make fmt`.

File: service/service.go [hunk 2]
```diff
@@ -234,9 +234,14 @@ func New(ctx context.Context, set Settings, cfg Config) (_ *Service, resultErr e
 		return nil, err
 	}
 
-	if err := proctelemetry.RegisterProcessMetrics(srv.telemetrySettings); err != nil {
-		return nil, fmt.Errorf("failed to register process metrics: %w", err)
-	}
+	// Only register process metrics on supported OSes.
+    // AIX is currently unsupported for process metrics, so we skip it to avoid crashing.
+    // For other OSes, we want to fail fast if registration fails.
+    if runtime.GOOS != "aix" {
```
Comment (dmathieu) [inline service/service.go]: Nit, but could you use a constant rather than an in-place string?

File: service/service.go [hunk 3]
```diff
@@ -234,9 +234,14 @@ func New(ctx context.Context, set Settings, cfg Config) (_ *Service, resultErr e
...
+        if err := proctelemetry.RegisterProcessMetrics(srv.telemetrySettings); err != nil {
+            return nil, err
+        }
+    }
```
Comment (dmathieu) [inline service/service.go]: When using AIX, this will silently do nothing which can be confusing. How about logging that we're skipping the register?

Comment (EdgeN8v) [reply service/service.go]: Good point. I've updated the logic to log an Info message when skipping AIX, and extracted the OS string into a constant.

**Comment by EdgeN8v** [comment]
@axw Done. I've ran make fmt.

File: service/service.go [hunk 4]
```diff
@@ -234,8 +234,17 @@ func New(ctx context.Context, set Settings, cfg Config) (_ *Service, resultErr e
 		return nil, err
 	}
 
-	if err := proctelemetry.RegisterProcessMetrics(srv.telemetrySettings); err != nil {
-		return nil, fmt.Errorf("failed to register process metrics: %w", err)
+	// Only register process metrics on supported OSes.
+	const osAIX = "aix"
```
Comment (dmathieu) [inline service/service.go]: IMHO, the const should be global.

File: .chloggen/fix-aix-crash.yaml
Comment (axw) [inline .chloggen/fix-aix-crash.yaml:1]: This file is not properly formatted. I suggest you use `make chlog-new` to create the file, and then edit it. Alternatively make it look like https://github.com/open-telemetry/opentelemetry-collector/blob/main/.chloggen/TEMPLATE.yaml

File: service/service.go (hunk 4 above)
Comment (EdgeN8v) [reply service/service.go]: Done. I've moved the constant to the package level.

File: .chloggen/fix-aix-crash.yaml
Comment (EdgeN8v) [reply .chloggen/fix-aix-crash.yaml:1]: Done. I've updated the changelog file format manually to match the template (flat format).

File: .chloggen/fix-aix-crash.yaml [hunk 5]
```diff
@@ -0,0 +1,4 @@
+change_type: bug_fix
+component: opentelemetry-collector
```
Comment (dmathieu) [inline .chloggen/fix-aix-crash.yaml]:
```suggestion
component: pkg/service
```

**Review by dmathieu — APPROVED** [review]

File: .chloggen/fix-aix-crash.yaml [hunk 6]
```diff
@@ -0,0 +1,4 @@
+change_type: bug_fix
+component: pkg/service
+note: "Fix panic in process metrics on unsupported OSes (e.g. AIX)"
```
Comment (evan-bradley) [inline .chloggen/fix-aix-crash.yaml]:
```suggestion
note: "Don't error on startup when process metrics are enabled on unsupported OSes (e.g. AIX)"
```
There wasn't a panic, right? I think it was just an error that was emitted.

File: service/service.go [hunk 7]
```diff
@@ -234,8 +236,16 @@ func New(ctx context.Context, set Settings, cfg Config) (_ *Service, resultErr e
 		return nil, err
 	}
 
-	if err := proctelemetry.RegisterProcessMetrics(srv.telemetrySettings); err != nil {
-		return nil, fmt.Errorf("failed to register process metrics: %w", err)
+	// Only register process metrics on supported OSes.
+	if runtime.GOOS == osAIX {
```
Comment (evan-bradley) [inline service/service.go]: I'm having a little difficulty understanding a few things here, could you help explain it to me?

In my mind, we should take a look at [OS support for processes in gopsutil](https://github.com/shirou/gopsutil/blob/master/process/process_fallback.go#L2) and do one of the following if we know there's no process support:

1. Fail fast and error out, require the user to disable process metrics for that OS.
2. Print a warn-level message indicating to the user that these metrics are disabled.

In my eyes, we should opt for (1) and require users to acknowledge they will not receive process metrics on their platform. I know the issue mentions a specific PR that caused a regression and introduced this issue, is there a reason we can't fix that? To me, that seems like the better place to address this.

If that is not an option, why is AIX special here? I would want us to instead only allow the operating systems we know we support (as indicated by the gopsutil file I linked above where I believe the error comes from), and everything else will print the warning message. However, if possible, I would prefer to fix the root issue and not register process metrics if they are disabled.

**Review by evan-bradley — CHANGES_REQUESTED** [review]
Thank you for working to address this @EdgeN8v.

Since we have a while until the next release, I'd like to see if we can more robustly address this. If someone else would like to get this in and revisit it later, feel free to dismiss my review.

File: service/service.go (hunk 7 above)
Comment (EdgeN8v) [reply service/service.go]: Hi @evan-bradley, thanks for the detailed review!

I've accepted the changelog suggestion.

Regarding the logic: I implemented the specific `osAIX` check based on the previous discussion to address the immediate regression reported in the issue, while trying to keep the change minimal.

I agree that an allowlist approach (or failing fast with an explicit error message) is more robust architecturally. However, since @dmathieu has already approved the current implementation, I want to be careful about changing the scope.

Do you prefer I refactor this PR to implement the strict allowlist logic (e.g., checking against supported OSes like Linux/Windows/Darwin), or should we merge this immediate fix for AIX first and handle the broader refactoring in a separate PR?

Comment (dmathieu) [reply service/service.go]: My approval doesn't prevent further refactors. An allowlist makes sense.

**Comment by dmathieu** [comment]
Your latest changes removed the warning when the metrics are disabled. We do want that behavior.
Also, it seems to me than @evan-bradley's suggestion was to use build tags to have the allow list (as gopsutil does), not to keep the strings list.

File: service/service.go (hunk 7 above)
Comment (EdgeN8v) [reply service/service.go]: I've updated the logic to use an explicit allowlist (Linux, Windows, Darwin) as suggested. The `osAIX` constant has also been removed.

Comment (EdgeN8v) [reply service/service.go]: Updated the PR accordingly: process metrics are now gated via build tags (linux/windows/darwin). Other OSes log a warning and continue startup. Error wrapping has also been restored on supported OSes.

**Comment by dmathieu** [comment]
I'd recommend running `make golint` locally to ensure the linter passes properly before pushing your changes.

**Comment by evan-bradley** [comment]
@EdgeN8v Thanks for continuing to work on this, and for your patience the past few days, I haven't had time to come back to this.

We have a concurrent effort to solve this issue here: https://github.com/open-telemetry/opentelemetry-collector/pull/14341. It looks like you started this first, but I'd like to align on our approach before you spend more time solving this.

@axw Sorry I also pinged you on the other PR, feel free to respond here or point me to another response if you've already given one. Since you have more context, what's your take on how we should be solving this? Regardless of our approach, in my opinion, setting `level: none` should ensure we don't get an error on unsupported platforms. I would actually lean toward throwing an error when `[...].Level != LevelNone` so we can fail fast on platforms that don't support process metrics.

**Comment by EdgeN8v** [comment]
Thanks for the context. I wasn’t aware there was parallel work on this when I started #14319.
Happy to pause here and align on the approach first. I’ll take a look at #14341 and follow up there.

**Comment by axw** [comment]
> @axw Sorry I also pinged you on the other PR, feel free to respond here or point me to another response if you've already given one. Since you have more context, what's your take on how we should be solving this? Regardless of our approach, in my opinion, setting level: none should ensure we don't get an error on unsupported platforms. I would actually lean toward throwing an error when [...].Level != LevelNone so we can fail fast on platforms that don't support process metrics.

IMO this PR is the right approach, and aligns well how code should be instrumented: instrument liberally, and it'll be a no-op unless an exporter is configured. The issue here is that the code _before_ setting up the instrumentation is failing because it's OS-specific, and we don't have coverage for all OS's.

Before https://github.com/open-telemetry/opentelemetry-collector/pull/13777 the telemetry setup would have failed if the level was set to something other than none. Rather than failing _all_ telemetry setup just because process metrics can't be registered, it would be more helpful to skip process metrics for unsupported OS's and continue setting up everything else.

**Review by dmathieu — APPROVED** [review]

**Comment by evan-bradley** [comment]
@axw Really appreciate your insight here. What you're saying makes sense to me, based on that I agree we should continue with this PR.

File: service/processmetrics_others.go [hunk 8]
```diff
@@ -0,0 +1,20 @@
+// Copyright The OpenTelemetry Authors
+// SPDX-License-Identifier: Apache-2.0
+
+//go:build !linux && !windows && !darwin
```
Comment (evan-bradley) [inline service/processmetrics_others.go]: Can we just do a `switch` statement on `runtime.GOOS` instead? Since we're in startup and not a hotpath, and since this code is very simple, I think it would be easier than needing to work with build tags.

**Review by evan-bradley — COMMENTED** [review]
Thanks for your patience @EdgeN8v. I'd like to adjust our approach just a bit, but otherwise this looks good to me.

File: service/processmetrics_others.go (hunk 8 above)
Comment (evan-bradley) [reply service/processmetrics_others.go]: @dmathieu Let me know if you think there's a benefit I'm missing from using build tags instead of switching on the platform string. In my opinion, it makes more sense for gopsutil to use build tags since it is a library. Additionally, we can rely on gopsutil's use of build tags to take care of the platform-specific pieces for us.

Comment (dmathieu) [reply service/processmetrics_others.go]: I don't mind a switch statement. I pushed for the build tags, as your previous comment seemed that's what was your suggestion.

Comment (evan-bradley) [reply service/processmetrics_others.go]: My bad, I should have been more explicit in my previous message. Let's go with a switch statement then, thanks.

**Comment by EdgeN8v** [comment]
@evan-bradley Thanks! I’ve refactored it to use a switch on runtime.GOOS as suggested.

It now explicitly supports Linux/Windows/Darwin and logs a warning on other platforms (e.g. AIX) to allow a graceful startup. Happy to adjust further if needed.

**Comment by dmathieu** [comment]
You lost the tests with your latest changes.

File: service/service.go [hunk 9]
```diff
@@ -364,3 +374,25 @@ func Validate(ctx context.Context, set Settings, cfg Config) error {
...
+
+// registerProcessMetrics registers process metrics on supported operating systems.
+//
+// Historically, attempting to register process metrics on unsupported platforms
+// (e.g. AIX) caused the Collector to fail at startup.
+// See https://github.com/open-telemetry/opentelemetry-collector/issues/12098
+func registerProcessMetrics(srv *Service) error {
+	switch getGOOS() {
+	// Only support the OSes that we explicitly test and build for.
+	case "linux", "darwin", "windows":
```
Comment (evan-bradley) [inline service/service.go]:
```suggestion
	case "linux", "darwin", "windows", "freebsd", "openbsd", "solaris", "plan9":
```

gopsutil has some level of support of getting process info from [these operating systems](https://github.com/shirou/gopsutil/blob/6c012ccde6deceb7b2ba5ec62c34c30f08dc6e60/process/process_fallback.go#L2C12-L2C87). While we don't release or officially support a few of them, I have seen instances where users build their own Collectors on these platforms, and I would prefer to not break process metrics for them.

File: service/service.go [hunk 10]
```diff
@@ -34,6 +34,14 @@ import (
 	"go.opentelemetry.io/collector/service/telemetry"
 )
 
+// The following package-level variables exist to make OS-specific behavior
+// testable. They allow tests to override runtime.GOOS and the process metrics
+// registration function without relying on the actual host OS.
+var (
+	getGOOS             = func() string { return runtime.GOOS }
+	registerProcMetrics = proctelemetry.RegisterProcessMetrics
```
Comment (evan-bradley) [inline service/service.go]: If we instead passed `runtime.GOOS` and `proctelemetry.RegisterProcessMetrics` in as arguments to `registerProcessMetrics`, we could get rid of these variables and the cleanup involved with changing them in the tests.

File: service/service_test.go [hunk 11]
```diff
@@ -882,3 +882,22 @@ func TestRegisterProcessMetrics_SupportedOS_RegisterFails_ReturnsError(t *testin
 	require.ErrorIs(t, err, wantErr)
 	require.Contains(t, err.Error(), "failed to register process metrics")
 }
+
+func TestNew_ProcessMetricsRegistrationFailure(t *testing.T) {
```
Comment (dmathieu) [inline service/service_test.go]: I don't think this test is necessary, as the behavior is already tested above.
And having `registerProcessMetrics` as a function rather than a variable is better.

Comment (EdgeN8v) [reply service/service_test.go]: I've reverted the changes as requested.
The only reason I switched to var was because Codecov is failing (84% hit vs 95% target), as the error path in New isn't being reached. I tried several other ways to mock this failure without refactoring, but none of them worked.

Comment (dmathieu) [reply service/service_test.go]: Code coverage isn't an end per-se. We should aim to achieve it, but we shouldn't change our design because of it.

File: service/service_test.go [hunk 12]
```diff
@@ -825,3 +830,198 @@ func TestValidateGraph(t *testing.T) {
...
+	_, err := New(context.Background(), set, cfg)
+
+	require.Error(t, err)
+	require.ErrorIs(t, err, errForcedMetric)
+	require.Contains(t, err.Error(), "failed to register process metrics")
+}
+
+var errForcedMetric = errors.New("forced metric error")
+
+type mockTelemetryFactory struct {
```
Comment (dmathieu) [inline service/service_test.go]: 👎 on all this mock. It exposes implementation details onto this test, which can make it brittle.

**Review by dmathieu — CHANGES_REQUESTED** [review]
If you keep making changes to approved PRs, it will never be merged.

**Comment by EdgeN8v** [comment]
@dmathieu Apologies for the noise. I misunderstood and thought additional updates were still needed even after the PR was marked ready. I’ve reverted back to the approved state and won’t make further changes unless requested.
