### PR TITLE
Ensure unique aliases

### LINKED ISSUE #12162: [OCB] Ensure unique aliases for packages with same suffix
**Describe the bug**
When two packages have the same suffix, this leads to OCB using the same alias, which breaks the build.

**Steps to reproduce**
`builder-config.yaml`
```
extensions:
- gomod: extension01/impl v0.61.0
  path: ../extension01/impl
- gomod: extension02/impl v0.61.0
  path: ../extension02/impl
```

Resulting `components.go`:
```
package main

import (
	impl "extension01/impl "
	impl "extension02/impl"
)

...

func components() (otelcol.Factories, error) {
	factories.Extensions, err = extension.MakeFactoryMap(
		impl.NewFactory(),
		impl.NewFactory(),
	)
...
	factories.ExtensionModules[impl.NewFactory().Type()] = "extension01/impl v0.61.0"
	factories.ExtensionModules[impl.NewFactory().Type()] = "extension02/impl v0.61.0"
...
}
```

**What did you expect to see?**
Unique aliases

### PR DESCRIPTION
**Pull request by mackjmr**
#### Description
This PR ensures that unique aliases are used for modules with same suffix.

#### Link to tracking issue
Fixes #12162

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
does this need a changelog?

**Comment by mackjmr** [comment]
@songy23 added in latest commit

**Comment by mackjmr** [comment]
good catch @jackgopack4, addressed in latest commit

**Review by jackgopack4 — APPROVED** [review]
looks good to me, thanks for addressing

**Comment by songy23** [comment]
https://github.com/open-telemetry/opentelemetry-collector/actions/runs/13013886944/job/36298551353?pr=12201 please fix linter

File: cmd/builder/internal/builder/config.go [hunk 1]
```diff
@@ -220,7 +221,7 @@ func validateModules(name string, mods []Module) error {
 	return nil
 }
 
-func parseModules(mods []Module) ([]Module, error) {
+func parseModules(mods []Module, usedNames map[string]int) ([]Module, map[string]int, error) {
```
Comment (djaglowski) [inline cmd/builder/internal/builder/config.go:224]:
```suggestion
func parseModules(mods []Module, usedNames map[string]int) ([]Module, error) {
```

Maps are reference types so modifying it within the function is enough to achieve the desired effect for the caller. ([example](https://go.dev/play/p/dLL21ygzt3D))

Comment (mackjmr) [reply cmd/builder/internal/builder/config.go]: Good call, updated 👍

**Review by ms-jcorley — APPROVED** [review]

**Review by songy23 — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]

**Comment by mackjmr** [comment]
Are we good to merge this in ?

**Review by codeboten — APPROVED** [review]
