### PR TITLE
Move error out of `ReportComponentStatus` function signature, use `ReportStatus` instead

### LINKED ISSUE #9148: `TelemetrySettings.ReportComponentStatus(...) error`: unsure how to handle returned error
We are using new component status reporting capabilities that replace `host.ReportFatalError`.

The new method to report component status has a signature that returns an error:
 `TelemetrySettings.ReportComponentStatus(...) error`

How should we handle the error being returned? It is ignored in most places right now.

### PR DESCRIPTION
**Pull request by atoulme**
Fixes #9148

### CODE REVIEW

File: service/service.go [hunk 1]
```diff
@@ -113,7 +113,9 @@ func New(ctx context.Context, set Settings, cfg Config) (*Service, error) {
 		MetricsLevel:   cfg.Telemetry.Metrics.Level,
 		// Construct telemetry attributes from build info and config's resource attributes.
 		Resource: pcommonRes,
-		Status:   status.NewReporter(srv.host.notifyComponentStatusChange),
+		Status: status.NewReporter(srv.host.notifyComponentStatusChange, func(err error) {
+			srv.telemetry.Logger().Warn("Invalid transition", zap.Error(err))
```
Comment (mwear) [inline service/service.go:117]: I think `debug` is probably the proper log level. Failed state transitions are expected behavior when using the `ReportComponentStatus` API.

Comment (atoulme) [reply service/service.go:117]: Sure thing. Is this approach valid overall?

Comment (mwear) [reply service/service.go]: It's an approach worth considering. My only reservation is that logging about invalid state transitions might give the user the impression that something is wrong with status reporting, when the invalid transitions are largely expected. I do think we want to give some feedback if the API is used before start however.

Comment (atoulme) [reply service/service.go]: ok that's doable by using errors.Is, just need to make sure the error is exported. I'll check.

File: service/service.go [hunk 2]
```diff
@@ -113,7 +114,13 @@ func New(ctx context.Context, set Settings, cfg Config) (*Service, error) {
 		MetricsLevel:   cfg.Telemetry.Metrics.Level,
 		// Construct telemetry attributes from build info and config's resource attributes.
 		Resource: pcommonRes,
-		Status:   status.NewReporter(srv.host.notifyComponentStatusChange),
+		Status: status.NewReporter(srv.host.notifyComponentStatusChange, func(err error) {
+			if errors.Is(err, status.ErrStatusNotReady) {
+				srv.telemetry.Logger().Warn("Invalid transition", zap.Error(err))
+			} else {
+				srv.telemetry.Logger().Debug("Invalid transition", zap.Error(err))
```
Comment (mwear) [inline service/service.go:121]: I'm wondering if we might omit logging about invalid transitions altogether since they are expected to happen and do not indicate an underlying problem using the API.

Comment (atoulme) [reply service/service.go:121]: sure. I can do that.

Now the bigger problem is how to deprecate this method to remove the error returned - I'll work on that next.

**Review by bogdandrutu — COMMENTED** [review]
This looks good to me

File: service/internal/servicetelemetry/telemetry_settings.go [hunk 3]
```diff
@@ -43,12 +43,17 @@ type TelemetrySettings struct {
 // ToComponentTelemetrySettings returns a TelemetrySettings for a specific component derived from
 // this service level Settings object.
 func (s TelemetrySettings) ToComponentTelemetrySettings(id *component.InstanceID) component.TelemetrySettings {
+	status := status.NewComponentStatusFunc(id, s.Status.ReportStatus)
```
Comment (mwear) [inline service/internal/servicetelemetry/telemetry_settings.go:46]: Super minor nit, can we call this `statusFunc`?

**Review by mwear — APPROVED** [review]
Looks great. I like the more concise method name -- `ReportStatus`. Thanks for cleaning this up!

File: service/internal/servicetelemetry/telemetry_settings.go (hunk 3 above)
Comment (atoulme) [reply service/internal/servicetelemetry/telemetry_settings.go:46]: Sure!

**Comment by atoulme** [comment]
Thanks I will follow up in a few days!

File: service/internal/servicetelemetry/telemetry_settings.go (hunk 3 above)
Comment (atoulme) [reply service/internal/servicetelemetry/telemetry_settings.go]: done

File: component/telemetry.go [hunk 4]
```diff
@@ -37,13 +37,13 @@ type TelemetrySettings struct {
...
-	// If the API is being used properly, these errors are safe to ignore.
+	// use this method to report status after start and before shutdown.
+	// Deprecated: [v0.92.0] This function will be removed in a future release.
+	// Use ReportStatus instead.
 	ReportComponentStatus func(*StatusEvent) error
+
+	// ReportStatus allows a component to report runtime changes in status. The service
+	// will automatically report status for a component during startup and shutdown. Components can
+	// use this method to report status after start and before shutdown.
+	ReportStatus func(*StatusEvent)
```
Comment (bogdandrutu) [inline component/telemetry.go:48]: What about we use interface instead, something like:

```golang
type StatusReporter interface {
   Report(*StatusEvent)
}

type TelemetrySettings struct {
  ....
  StatusReporter StatusReporter // I am not sure about the name of the variable, I like the interface name
}
```

This allows us to add more funcs to this interface in the future. For that we can even use optional interfaces that the StatusReporters can optionally implement, or we add an un-exported func and we have a "NopStatusReporters" that everyone must embed to implement the interface.

Comment (atoulme) [reply component/telemetry.go:48]: trying it

Comment (atoulme) [reply component/telemetry.go:48]: a bit more research needed, especially as we can use this interface to resolve this comment:
https://github.com/open-telemetry/opentelemetry-collector/blob/b3d04f58abda0f0550b2bfa547390ee2ce150be8/component/telemetry.go#L17-L19

Comment (mwear) [reply component/telemetry.go:48]: I don't anticipate needing additional status reporting methods for components. If we have some examples, I'd be open to considering it. As this is a method on `component.TelemetrySettings`, to be used by components, is there any value in having a optional interface? FWIW, the service does need multiple methods, and when I made that change, I intentionally did not expose the additional method on `component.TelemetrySettings`. The other difference with the `servicetelemetry.TelemetrySettings` version is that it takes the `component.InstanceID` as a parameter, whereas the component version is bound to an `InstanceID` for a specific component via a closure.

**Comment by atoulme** [comment]
Is there anything left to do?

**Review by bogdandrutu — APPROVED** [review]
