### PR TITLE
Re-add version code to cmd/builder

### LINKED ISSUE #11220: OCB v0.107.0 and onward no longer report version on command line
**Describe the bug**

ocb from v0.107.0 onward reports "devel" as version when running on CLI instead of version number. Confirmed to work in v106.1 and earlier

**Steps to reproduce**
Download any ocb binary v0.107.0 or later and run `ocb version`

**What did you expect to see?**
expect to see `ocb version vX.XXX.X`

**What did you see instead?**
instead see `ocb version (devel)

**What version did you use?**
v0.107.0, v0.108.0, v0.109.0

**What config did you use?**
n/a

**Environment**
darwin/arm64, downloaded ocb binary

**Additional context**
reported in releases repo https://github.com/open-telemetry/opentelemetry-collector-releases/issues/664
PR to re-add code and add unit tests that was removed and causes cli to not report proper build version.
Also requires adding flag in build process, PR open in releases: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/665

### PR DESCRIPTION
**Pull request by jackgopack4**
Revert "[chore] delete code to set a version and date, as it it not used (#10715)"
Remove date string but re-add functions that check for version number
This (mostly) reverts commit b53f57d.

#### Description
This re-enables the functionality to set a version number for ocb binary (cmd/builder). It was erroneously removed. It also adds unit tests for this functionality, as a warning is given on CI with no code coverage.

#### Link to tracking issue
Relates to https://github.com/open-telemetry/opentelemetry-collector-releases/issues/664.
Closes #11220 along with https://github.com/open-telemetry/opentelemetry-collector-releases/pull/665

#### Testing
ran build and release cycles inside personal fork repositories (jackgopack4/opentelemetry-collector and jackgopack4/opentelemetry-collector-releases)

#### Documentation
.chloggen file

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@jackgopack4 who is writing the version though? Am I missing something here?

**Comment by jackgopack4** [comment]
after this code was removed, passing the build flag for version does not properly set the version when someone wants to run `ocb version` or run ocb and see the output of version before it runs all of its commands.

as I understand it, this function is called by the cobra cli interface when someone runs ocb on the command line.

File: cmd/builder/internal/version.go [hunk 1]
```diff
@@ -14,18 +14,34 @@ var (
...
+	var err error
 	return &cobra.Command{
 		Use:   "version",
 		Short: "Version of ocb",
 		Long:  "Prints the version of the ocb binary",
 		RunE: func(cmd *cobra.Command, _ []string) error {
+			version, err = fn(debug.ReadBuildInfo)
+			if err != nil {
+				return err
+			}
```
Comment (bogdandrutu) [inline cmd/builder/internal/version.go:44]: Is the difference just that the `debug.ReadBuildInfo()` is executed in the Run? If that is the case, can we do just that?

Comment (jackgopack4) [reply cmd/builder/internal/version.go:44]: no, that's not enough to make a difference. running `CGO_ENABLED=0 go build -trimpath -ldflags='-s -w -X go.opentelemetry.io/collector/cmd/builder/internal.version=v0.110.0'` with this code passes a version number but just moving the debug.ReadBuildInfo into the RunE command does not fix it.

Comment (jackgopack4) [reply cmd/builder/internal/version.go:44]: need to have a check to see if version is still blank; the init function is overwriting version with `debug.ReadBuildInfo` otherwise

Comment (jackgopack4) [reply cmd/builder/internal/version.go:44]: simply adding an `if version == ""` check to the `init()` function originally on line 17 would also solve it, it seems

Comment (jackgopack4) [reply cmd/builder/internal/version.go]: ok @bogdandrutu I made the PR much smaller and still fixed the issue

Comment (bogdandrutu) [reply cmd/builder/internal/version.go]: >running CGO_ENABLED=0 go build -trimpath -ldflags='-s -w -X go.opentelemetry.io/collector/cmd/builder/internal.version=v0.110.0' 

Where do we do this?
