### PR TITLE
fluentbit Extension: Fix flaky test

### LINKED ISSUE #1848: TestProcessManagerArgs - fluentbitextension test is unstable
See https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/3608/workflows/774aefa0-fd5c-45d5-b0aa-827cff15aeb2/jobs/38277

```
Failed
([]observer.LoggedEntry) (len=6 cap=6) {
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:58.899717627 +0000 UTC m=+0.019446312,
   LoggerName: (string) "",
   Message: (string) (len=30) "Fluent extension changed state",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=5) "state",
    Type: (zapcore.FieldType) 15,
    Integer: (int64) 0,
    String: (string) (len=8) "starting",
    Interface: (interface {}) <nil>
   }
  }
 },
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:58.899779833 +0000 UTC m=+0.019508514,
   LoggerName: (string) "",
   Message: (string) (len=26) "Starting fluent subprocess",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=7) "command",
    Type: (zapcore.FieldType) 15,
    Integer: (int64) 0,
    String: (string) (len=112) "/tmp/mocksubproc042379101 --config=/dev/stdin --http --port=2020 --flush=1 -o forward://127.0.0.1:8000 --match=*",
    Interface: (interface {}) <nil>
   }
  }
 },
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:58.900418692 +0000 UTC m=+0.020147367,
   LoggerName: (string) "",
   Message: (string) (len=30) "Fluent extension changed state",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=5) "state",
    Type: (zapcore.FieldType) 15,
    Integer: (int64) 0,
    String: (string) (len=7) "running",
    Interface: (interface {}) <nil>
   }
  }
 },
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:58.906606547 +0000 UTC m=+0.026335228,
   LoggerName: (string) "",
   Message: (string) (len=7) "Config:",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) {
  }
 },
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:59.103320141 +0000 UTC m=+0.223048829,
   LoggerName: (string) "",
   Message: (string) (len=30) "Fluent extension changed state",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=5) "state",
    Type: (zapcore.FieldType) 15,
    Integer: (int64) 0,
    String: (string) (len=13) "shutting-down",
    Interface: (interface {}) <nil>
   }
  }
 },
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:59.103571802 +0000 UTC m=+0.223300512,
   LoggerName: (string) "",
   Message: (string) (len=30) "Fluent extension changed state",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=5) "state",
    Type: (zapcore.FieldType) 15,
    Integer: (int64) 0,
    String: (string) (len=7) "stopped",
    Interface: (interface {}) <nil>
   }
  }
 }
}
    process_linux_test.go:133: 
([]observer.LoggedEntry) (len=5 cap=5) {
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:58.8999535 +0000 UTC m=+0.019682202,
   LoggerName: (string) "",
   Message: (string) (len=30) "Fluent extension changed state",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=5) "state",
    Type: (zapcore.FieldType) 15,
    Integer: (int64) 0,
    String: (string) (len=8) "starting",
    Interface: (interface {}) <nil>
   }
  }
 },
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:58.90006668 +0000 UTC m=+0.019795364,
   LoggerName: (string) "",
   Message: (string) (len=26) "Starting fluent subprocess",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=7) "command",
    Type: (zapcore.FieldType) 15,
    Integer: (int64) 0,
    String: (string) (len=32) "/tmp/mocksubproc752661272 --http",
    Interface: (interface {}) <nil>
   }
  }
 },
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:58.900338973 +0000 UTC m=+0.020067657,
   LoggerName: (string) "",
   Message: (string) (len=30) "Fluent extension changed state",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=5) "state",
    Type: (zapcore.FieldType) 15,
    Integer: (int64) 0,
    String: (string) (len=7) "errored",
    Interface: (interface {}) <nil>
   }
  }
 },
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) error,
   Time: (time.Time) 2020-09-22 23:23:58.900360907 +0000 UTC m=+0.020089588,
   LoggerName: (string) "",
   Message: (string) (len=22) "FluentBit process died",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=5) "error",
    Type: (zapcore.FieldType) 26,
    Integer: (int64) 0,
    String: (string) "",
    Interface: (*os.PathError)(0xc0004100c0)(fork/exec /tmp/mocksubproc752661272: text file busy)
   }
  }
 },
 (observer.LoggedEntry) {
  Entry: (zapcore.Entry) {
   Level: (zapcore.Level) debug,
   Time: (time.Time) 2020-09-22 23:23:58.900363749 +0000 UTC m=+0.020092424,
   LoggerName: (string) "",
   Message: (string) (len=30) "Fluent extension changed state",
   Caller: (zapcore.EntryCaller) undefined,
   Stack: (string) ""
  },
  Context: ([]zapcore.Field) (len=1 cap=1) {
   (zapcore.Field) {
    Key: (string) (len=5) "state",
    Type: (zapcore.FieldType) 15,
    Integer: (int64) 0,
    String: (string) (len=10) "restarting",
    Interface: (interface {}) <nil>
   }
  }
 }
}
Key: (string) (len=5) "state",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=8) "starting",
Interface: (interface {}) <nil>
Key: (string) (len=7) "command",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=112) "/tmp/mocksubproc466588790 --config=/dev/stdin --http --port=2020 --flush=1 -o forward://127.0.0.1:8000 --match=*",
Interface: (interface {}) <nil>
Key: (string) (len=5) "state",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=7) "running",
Interface: (interface {}) <nil>
Key: (string) (len=5) "state",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=7) "errored",
Interface: (interface {}) <nil>
Key: (string) (len=5) "error",
Type: (zapcore.FieldType) 26,
Integer: (int64) 0,
String: (string) "",
Interface: (*exec.ExitError)(0xc0002b7f20)(signal: killed)
Key: (string) (len=5) "state",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=10) "restarting",
Interface: (interface {}) <nil>
Key: (string) (len=5) "state",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=8) "starting",
Interface: (interface {}) <nil>
Key: (string) (len=7) "command",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=112) "/tmp/mocksubproc466588790 --config=/dev/stdin --http --port=2020 --flush=1 -o forward://127.0.0.1:8000 --match=*",
Interface: (interface {}) <nil>
Key: (string) (len=5) "state",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=7) "running",
Interface: (interface {}) <nil>
Key: (string) (len=5) "state",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=13) "shutting-down",
Interface: (interface {}) <nil>
Key: (string) (len=5) "state",
Type: (zapcore.FieldType) 15,
Integer: (int64) 0,
String: (string) (len=7) "stopped",
Interface: (interface {}) <nil>
```

### PR DESCRIPTION
**Pull request by keitwb**
The failures reported in #1848 seem to be caused by the issue described
in https://github.com/golang/go/issues/22315 and the fact that we run
tests in parallel.

Fixes #1848.

### CODE REVIEW

**Comment by keitwb** [comment]
Test failure is some transient docker failure on the publish-check step.

File: extension/fluentbitextension/process_linux_test.go [hunk 1]
```diff
@@ -56,7 +56,8 @@ func setup(t *testing.T, conf *Config) (*processManager, **process.Process, func
 	err = mockScriptFile.Chmod(0700)
 	require.Nil(t, err)
 
-	mockScriptFile.Close()
+	err = mockScriptFile.Close()
```
Comment (bogdandrutu) [inline extension/fluentbitextension/process_linux_test.go:59]: `require.NoError(t, mockScriptFile.Close())`

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@keitwb thanks for the fix.
