### PR TITLE
exporter/prometheusexporter: support Summary

### LINKED ISSUE #2661: PrometheusReceiver ignores Summary and Histogram Metrics that do not have _sum counter.
**Describe the bug**
Summary and Histogram metrics exposed by frameworks like DropWizard do not track "_sum" counter and hence do not produce this in the output. When Prometheus receiver is run against such outputs, the histograms and Summaries are just ignored.

**Steps to reproduce**
A Simple Dropward application with a histogram metric and otelcollector with prometheus receiver.

**What did you expect to see?**
Expect to see the Histogram / Summary passed through the pipeline and available for exporters (with _sum as "0").

**What did you see instead?**
The Metric is dropped silently.

**What version did you use?**
Version: (v0.21.0)

**What config did you use?**
`receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ 'localhost:35599' ]
              labels:
                instance_type: gke_container
                container_name: "${CONTAINER_NAME}"
                namespace_id: "${NAMESPACE_NAME}"
                pod_id: "${POD_NAME}"

processors:
  batch:

exporters:
  file:
    path: /tmp/metrics.json

  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 5

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [logging, file]
`
**Environment**
OS: Debian
Docker image.

**Additional context**

### PR DESCRIPTION
**Pull request by odeke-em**
Allows Summary metrics to be exported to Prometheus.
To walk through this feature, I created an adaptation of a Brian Brazil
tutorial for DropWizard, to create a Java server at
https://github.com/odeke-em/bugs/tree/master/opentelemetry-collector/2661
and it uses DropWizard, and exports out JVM statistics with Prometheus where the
*gc_collection_seconds are of the summary kind when scraped by visiting
http://localhost:1234/metrics which produced

```
 # HELP jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
 # TYPE jvm_gc_collection_seconds summary
 jvm_gc_collection_seconds_count{gc="G1 Young Generation",} 4.0
 jvm_gc_collection_seconds_sum{gc="G1 Young Generation",} 0.026
 jvm_gc_collection_seconds_count{gc="G1 Old Generation",} 0.0
```

and then roundtripped the collector to scrape those metrics and then
export them to Prometheus

    VS

making Prometheus directly scrape that endpoint and then comparing
results.

Fixes #2661

### CODE REVIEW

**Comment by odeke-em** [comment]
Alright, ready for action, kindly cc-ing some reviewers @alolita @Aneurysm9 @rakyll @bogdandrutu @brian-brazil.

File: exporter/prometheusexporter/collector.go [hunk 1]
```diff
@@ -207,6 +209,40 @@ func (c *collector) convertIntHistogram(metric pdata.Metric) (prometheus.Metric,
...
+	var cumSum float64
+	var cumCount uint64
+	quantiles := make(map[float64]float64)
+	labelsMap := pdata.NewStringMap()
+	for i := 0; i < dataPoints.Len(); i++ {
+		sdpi := dataPoints.At(i)
+		qv := sdpi.QuantileValues()
+		for j := 0; j < qv.Len(); j++ {
+			qvj := qv.At(j)
+			quantiles[qvj.Quantile()] += qvj.Value()
```
Comment (brian-brazil) [inline exporter/prometheusexporter/collector.go:224]: Why is this an addition? Quantiles can't be added.

**Comment by odeke-em** [comment]
Quantiles indeed can’t be added but I wasn’t sure if there will ALWAYS be
exactly one value with the quantile or not — this part wasn’t clear.
Replacement wouldn’t be my immediate fallback given that then ordering
would matter.

File: exporter/prometheusexporter/collector.go (hunk 1 above)
Comment (odeke-em) [reply exporter/prometheusexporter/collector.go:224]: Quantiles indeed can’t be added but I wasn’t sure if there
will ALWAYS be exactly one value with the quantile or not — this part wasn’t clear.
Replacement wouldn’t be my immediate fallback
given that then ordering would matter.

Comment (brian-brazil) [reply exporter/prometheusexporter/collector.go:224]: There should be exactly one per summary metricpoint for a given quantile, otherwise it's invalid exposition.

Comment (odeke-em) [reply exporter/prometheusexporter/collector.go]: Fixed, thank you!

File: exporter/prometheusexporter/collector.go [hunk 2]
```diff
@@ -207,6 +209,41 @@ func (c *collector) convertIntHistogram(metric pdata.Metric) (prometheus.Metric,
 	return m, nil
 }
 
+func (c *collector) convertSummary(metric pdata.Metric) (prometheus.Metric, error) {
+	dataPoints := metric.Summary().DataPoints()
+
+	var cumSum float64
+	var cumCount uint64
+	quantiles := make(map[float64]float64)
```
Comment (Aneurysm9) [inline exporter/prometheusexporter/collector.go:217]: Should these values be tracked on a per data point basis?  What is the expected behavior if a `pdata.Metric` is received that has multiple summary data points?  Perhaps I misunderstand the data model, but my assumption would be that they would all have quantile values at the same quantiles.  Should the most recent summary data point be exported?  It seems like the current implementation will aggregate the sum and count but take the last value seen for each quantile, which doesn't feel right.

Comment (odeke-em) [reply exporter/prometheusexporter/collector.go:217]: You do have a great point and thank you for articulating it! Indeed, one point with varying quantiles, single sum and single count. Thank you! Done.

**Review by Aneurysm9 — APPROVED** [review]

File: exporter/prometheusexporter/accumulator.go [hunk 3]
```diff
@@ -94,11 +94,43 @@ func (a *lastValueAccumulator) addMetric(metric pdata.Metric, il pdata.Instrumen
 		return a.accumulateIntHistogram(metric, il, now)
 	case pdata.MetricDataTypeHistogram:
 		return a.accumulateDoubleHistogram(metric, il, now)
+	case pdata.MetricDataTypeSummary:
+		return a.accumulateSummary(metric, il, now)
+	default:
+		a.logger.With(
+			zap.Any("data_type", metric.DataType()),
+			zap.Any("metric_name", metric.Name()),
```
Comment (bogdandrutu) [inline exporter/prometheusexporter/accumulator.go:102]: Any/String/s

**Review by bogdandrutu — COMMENTED** [review]
The description of the PR is incorrect the ignore of no sum is fixed.

File: exporter/prometheusexporter/accumulator.go (hunk 3 above)
Comment (odeke-em) [reply exporter/prometheusexporter/accumulator.go]: Done, thanks!

**Comment by odeke-em** [comment]
>The description of the PR is incorrect the ignore of no sum is fixed.

@bogdandrutu sorry I don't follow what you mean, all I talked about was that now we export Summary through the prometheusexporter, where does "the ignore of no sum is fixed" relate? Thanks for the review too!

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@odeke-em please fix lint errors

**Comment by odeke-em** [comment]
@bogdandrutu done, although the "lint" flagged legitimate Go code in 2 cases that don't make sense so might want to look at the false positives. Thank you for the reviews @Aneurysm9 and @bogdandrutu!
