### PR TITLE
Incorporate next consumer's capabilities into connector capabilities

### LINKED ISSUE #7776: forwardconnector shouldn't set MutatesData: false
**Describe the bug**
A filter processor in a second pipeline affects export data in a previous pipeline connected by forwardconnector

**Steps to reproduce**
Try running the config provided below multiple times, it sometimes works, sometimes breaks.

**What did you expect to see?**
Original pipeline unaffected by second pipeline, 
logging/1: 17 metrics
logging/2: 1 metric

log output:

```
2023-05-28T17:05:15.454+0100	info	service/telemetry.go:104	Setting up own telemetry...
2023-05-28T17:05:15.454+0100	info	service/telemetry.go:127	Serving Prometheus metrics	{"address": ":8888", "level": "Basic"}
2023-05-28T17:05:15.454+0100	info	exporter@v0.78.2/exporter.go:275	Development component. May change in the future.	{"kind": "exporter", "data_type": "metrics", "name": "logging/2"}
2023-05-28T17:05:15.456+0100	info	exporter@v0.78.2/exporter.go:275	Development component. May change in the future.	{"kind": "exporter", "data_type": "metrics", "name": "logging/1"}
2023-05-28T17:05:15.459+0100	info	connector/connector.go:636	Development component. May change in the future.	{"kind": "exporter", "name": "forward", "exporter_in_pipeline": "metrics", "receiver_in_pipeline": "metrics"}
2023-05-28T17:05:15.464+0100	info	service/service.go:131	Starting otelcol-custom...	{"Version": "1.0.0", "NumCPU": 16}
2023-05-28T17:05:15.464+0100	info	extensions/extensions.go:30	Starting extensions...
2023-05-28T17:05:15.464+0100	info	prometheusreceiver@v0.77.0/metrics_receiver.go:255	Starting discovery manager	{"kind": "receiver", "name": "prometheus_simple", "data_type": "metrics"}
2023-05-28T17:05:15.466+0100	info	prometheusreceiver@v0.77.0/metrics_receiver.go:243	Scrape job added	{"kind": "receiver", "name": "prometheus_simple", "data_type": "metrics", "jobName": "prometheus_simple/127.0.0.1:8888"}
2023-05-28T17:05:15.467+0100	info	service/service.go:148	Everything is ready. Begin running and processing data.
2023-05-28T17:05:15.467+0100	info	prometheusreceiver@v0.77.0/metrics_receiver.go:289	Starting scrape manager	{"kind": "receiver", "name": "prometheus_simple", "data_type": "metrics"}
2023-05-28T17:05:20.525+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 14, "data points": 17}
2023-05-28T17:05:20.525+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:20.629+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 17, "data points": 21}
2023-05-28T17:05:20.629+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:21.623+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 17, "data points": 21}
2023-05-28T17:05:21.623+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:21.723+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 17, "data points": 21}
2023-05-28T17:05:21.723+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:22.624+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 17, "data points": 21}
2023-05-28T17:05:22.624+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:22.724+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 17, "data points": 21}
2023-05-28T17:05:22.724+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:23.724+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 17, "data points": 21}
2023-05-28T17:05:23.724+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:23.825+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 17, "data points": 21}
2023-05-28T17:05:23.825+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:24.726+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 17, "data points": 21}
2023-05-28T17:05:24.726+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:24.824+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 17, "data points": 21}
2023-05-28T17:05:24.824+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
^C2023-05-28T17:05:25.529+0100	info	otelcol/collector.go:227	Received signal from OS	{"signal": "interrupt"}
2023-05-28T17:05:25.529+0100	info	service/service.go:157	Starting shutdown...
2023-05-28T17:05:25.529+0100	info	extensions/extensions.go:44	Stopping extensions...
2023-05-28T17:05:25.529+0100	info	service/service.go:171	Shutdown complete.
```

**What did you see instead?**
Data appears to be dropped in original pipeline
logging/1: 1 metric
logging/2: 1 metric

```
2023-05-28T17:05:27.499+0100	info	service/telemetry.go:104	Setting up own telemetry...
2023-05-28T17:05:27.499+0100	info	service/telemetry.go:127	Serving Prometheus metrics	{"address": ":8888", "level": "Basic"}
2023-05-28T17:05:27.499+0100	info	exporter@v0.78.2/exporter.go:275	Development component. May change in the future.	{"kind": "exporter", "data_type": "metrics", "name": "logging/1"}
2023-05-28T17:05:27.501+0100	info	exporter@v0.78.2/exporter.go:275	Development component. May change in the future.	{"kind": "exporter", "data_type": "metrics", "name": "logging/2"}
2023-05-28T17:05:27.505+0100	info	connector/connector.go:636	Development component. May change in the future.	{"kind": "exporter", "name": "forward", "exporter_in_pipeline": "metrics", "receiver_in_pipeline": "metrics"}
2023-05-28T17:05:27.507+0100	info	service/service.go:131	Starting otelcol-custom...	{"Version": "1.0.0", "NumCPU": 16}
2023-05-28T17:05:27.507+0100	info	extensions/extensions.go:30	Starting extensions...
2023-05-28T17:05:27.508+0100	info	prometheusreceiver@v0.77.0/metrics_receiver.go:255	Starting discovery manager	{"kind": "receiver", "name": "prometheus_simple", "data_type": "metrics"}
2023-05-28T17:05:27.510+0100	info	prometheusreceiver@v0.77.0/metrics_receiver.go:243	Scrape job added	{"kind": "receiver", "name": "prometheus_simple", "data_type": "metrics", "jobName": "prometheus_simple/127.0.0.1:8888"}
2023-05-28T17:05:27.510+0100	info	service/service.go:148	Everything is ready. Begin running and processing data.
2023-05-28T17:05:27.510+0100	info	prometheusreceiver@v0.77.0/metrics_receiver.go:289	Starting scrape manager	{"kind": "receiver", "name": "prometheus_simple", "data_type": "metrics"}
2023-05-28T17:05:32.524+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:32.524+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:32.627+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:32.627+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:33.525+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:33.525+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:33.626+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:33.626+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:34.629+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:34.629+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:34.726+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:34.726+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:35.725+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:35.725+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:35.824+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/2", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-05-28T17:05:35.824+0100	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging/1", "resource metrics": 1, "metrics": 1, "data points": 1}
^C2023-05-28T17:05:35.985+0100	info	otelcol/collector.go:227	Received signal from OS	{"signal": "interrupt"}
2023-05-28T17:05:35.985+0100	info	service/service.go:157	Starting shutdown...
2023-05-28T17:05:35.985+0100	info	extensions/extensions.go:44	Stopping extensions...
2023-05-28T17:05:35.986+0100	info	service/service.go:171	Shutdown complete.
```

**What version did you use?**
Version: `v0.77.0`

**What config did you use?**
Config:

```yaml
receivers:
  prometheus_simple:
    collection_interval: 0.1s
    endpoint: 127.0.0.1:8888

processors:
  filter:
    metrics:
      metric:
        - 'name != "up"'
exporters:
  logging/1:
  logging/2:
connectors:
  forward:
service:
  pipelines:
    metrics/1:
      receivers:
        - prometheus_simple
      exporters:
        - logging/1
        - forward
    metrics/2:
      receivers:
        - forward
      processors:
        - filter
      exporters:
        logging/2
```

**Additional context**

This appears to either consistently work, or consistently not with no change to config.

### PR DESCRIPTION
**Pull request by djaglowski**
Resolves #7776

The collector copies data whenever handing it to components that may mutate it. The point at which a copy must be made is within a fanout consumer. There are two points at which a fanout consumer may be placed:
1. Immediately after a receiver shared by multiple pipelines
2. Immediately before multiple exporters of a single pipeline

When data is fanned out _to_ a connector (acting as an exporter), we must ensure that the fanout consumer before exporters (point 2 above) is able to take into account whether or not the connector will be handing the data off to a pipeline that will mutate the data.

### CODE REVIEW

File: service/internal/graph/graph_test.go [hunk 1]
```diff
@@ -651,6 +651,30 @@ func TestConnectorPipelinesGraph(t *testing.T) {
...
+						r, ok := receiver.(*connectorNode)
+						if !ok {
+							continue
+						}
+						for expPipelineID, expPipeline := range pg.pipelines {
+							if expPipelineID.Type() != pipelineID.Type() {
+								continue
+							}
+							for _, exporter := range expPipeline.exporters {
+								e, ok := receiver.(*connectorNode)
```
Comment (evan-bradley) [inline service/internal/graph/graph_test.go:666]: Should this be `exporter.(*connectorNode)`?

File: service/internal/graph/graph_test.go [hunk 2]
```diff
@@ -651,6 +651,30 @@ func TestConnectorPipelinesGraph(t *testing.T) {
...
+								if !ok || exporter.ID() != receiver.ID() {
+									continue
+								}
+								assert.True(t, e.getConsumer().Capabilities().MutatesData,
```
Comment (codeboten) [inline service/internal/graph/graph_test.go:670]: Could this be rewritten as `assert.Equal(t, expectMutatesData, e.getConsumer().Capabilities().MutatesData)` and avoid the conditional at line 655? Thinking this would prevent regressions where a consumer reports mutable when it's not expected

**Review by codeboten — COMMENTED** [review]
This looks ok to me, just one question

File: service/internal/graph/graph_test.go (hunk 2 above)
Comment (djaglowski) [reply service/internal/graph/graph_test.go]: The problem is that this assertion is not necessary expected. This test case contains an example of where it goes wrong:

```go
{
	name: "pipelines_conn_fork_merge_traces.yaml",
	pipelineConfigs: map[component.ID]*PipelineConfig{
		component.NewIDWithName("traces", "in"): {
			Receivers:  []component.ID{component.NewID("examplereceiver")},
			Processors: []component.ID{component.NewID("exampleprocessor")},
			Exporters:  []component.ID{component.NewIDWithName("exampleconnector", "fork")}, // wrapped w/ mutates: true
		},
		component.NewIDWithName("traces", "type0"): {
			Receivers:  []component.ID{component.NewIDWithName("exampleconnector", "fork")},
			Processors: []component.ID{component.NewID("exampleprocessor")},
			Exporters:  []component.ID{component.NewIDWithName("exampleconnector", "merge")},
		},
		component.NewIDWithName("traces", "type1"): {
			Receivers:  []component.ID{component.NewIDWithName("exampleconnector", "fork")},
			Processors: []component.ID{component.NewIDWithName("exampleprocessor", "mutate")},
			Exporters:  []component.ID{component.NewIDWithName("exampleconnector", "merge")},
		},
		component.NewIDWithName("traces", "out"): {
			Receivers:  []component.ID{component.NewIDWithName("exampleconnector", "merge")},
			Processors: []component.ID{component.NewID("exampleprocessor")},
			Exporters:  []component.ID{component.NewID("exampleexporter")},
		},
	},
	expectedPerExporter: 2,
},
```

The `type0` and `type1` pipelines both use the `/fork` connector as a receiver, but only `type1` mutates data. So the expectation is that the connector will inherit `MutatesData: true` from `type1`. However, `expectMutatesData` is specific to each pipeline, so when looking at `type0`, we don't expect a match. Essentially, we can't prove a negative (without looking at the broader picture).

All that said, your point is valid and I've reworked this entire section in a way that accounts for all pipelines to which a connector emits, which allows us to validate both ways.

**Review by dmitryax — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
