### PR TITLE
hook up start and shutdown functions in fileexporter

### LINKED ISSUE #3248: fileexporter panics when marshaling data
**Describe the bug**
The fileexporter panics when it processes data and causes the Collector to fail.

**Steps to reproduce**
Run the given Kubernetes manifest with `k apply -f .`.

[collector-egress-file.txt](https://github.com/open-telemetry/opentelemetry-collector/files/6522939/collector-egress-file.txt)

**What did you expect to see?**
The Collector starting and then writing metric data to the configured file in the container. 

**What did you see instead?**
The Collector starts but fails as soon as the Prometheus metric data is processed by the fileexporter. 

**What version did you use?**
Version: v0.27.0

**What config did you use?**
Config:

```yaml
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'collector-metrics'
              scrape_interval: 10s
              static_configs:
                - targets:
                    - 'localhost:8888'

    exporters:
      logging:
      file:
        path: /metrics.json

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          # Works if only the logging exporter is configured.
          #exporters: [logging]
          # Panics if any data sent to file exporter. This configuration
          # tests only the metrics, but also fails with logs or traces.
          exporters: [logging, file]
```

**Environment**
OS: Microsoft Windows 10 Enterprise (Version 10.0.18363 Build 18363)

**Additional context**
Although the example only reproduces the problem for metrics, in our environment we see the same behavior for logs and traces as well.

The stack trace of the panic follows:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xcf8878]

goroutine 146 [running]:
github.com/gogo/protobuf/jsonpb.(*errWriter).write(...)
        github.com/gogo/protobuf@v1.3.2/jsonpb/jsonpb.go:1272
github.com/gogo/protobuf/jsonpb.(*Marshaler).marshalObject(0x4b98600, 0xc0003dae80, 0x36cb5b0, 0xc0003488a0, 0x0, 0x0, 0x0, 0x0, 0x2d1c640, 0x9360200ae101)
        github.com/gogo/protobuf@v1.3.2/jsonpb/jsonpb.go:281 +0x14f8
github.com/gogo/protobuf/jsonpb.(*Marshaler).Marshal(0x4b98600, 0x0, 0x0, 0x36cb5b0, 0xc0003488a0, 0xc00061e420, 0x36de718)
        github.com/gogo/protobuf@v1.3.2/jsonpb/jsonpb.go:138 +0x1b0
go.opentelemetry.io/collector/exporter/fileexporter.exportMessageAsLine(0xc000b16f90, 0x36cb5b0, 0xc0003488a0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/fileexporter/file_exporter.go:63 +0xc9
go.opentelemetry.io/collector/exporter/fileexporter.(*fileExporter).ConsumeMetrics(...)
        go.opentelemetry.io/collector/exporter/fileexporter/file_exporter.go:52
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).export(0xc000b11dc0, 0x36de6e0, 0xc00061e420, 0x36de6e0, 0xc00061e420)
        go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:55 +0x47
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000059c08, 0x36f16f8, 0xc000b11dc0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/exporterhelper/common.go:222 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc0009bff80, 0x36f16f8, 0xc000b11dc0, 0x31a4d05, 0x8)
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send(0xc00063adb0, 0x36f16f8, 0xc000b11dc0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:119 +0xb1
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send(0xc0000dc690, 0x36f16f8, 0xc000b11dc0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/exporterhelper/queued_retry.go:171 +0x3dc
go.opentelemetry.io/collector/exporter/exporterhelper.NewMetricsExporter.func2(0x36de718, 0xc000810f00, 0xc0003488a0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:103 +0xbe
go.opentelemetry.io/collector/consumer/consumerhelper.ConsumeMetricsFunc.ConsumeMetrics(0xc000b11280, 0x36de718, 0xc000810f00, 0xc0003488a0, 0x0, 0x0)
        go.opentelemetry.io/collector/consumer/consumerhelper/metrics.go:29 +0x44
go.opentelemetry.io/collector/service/internal/fanoutconsumer.metricsConsumer.ConsumeMetrics(0xc000b112e0, 0x2, 0x2, 0x36de718, 0xc000810f00, 0xc0003488a0, 0xc0003488a0, 0xc000aa7040)
        go.opentelemetry.io/collector/service/internal/fanoutconsumer/consumer.go:51 +0xa4
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*transaction).Commit(0xc000122b60, 0x314c3638, 0xed839af41)
        go.opentelemetry.io/collector/receiver/prometheusreceiver/internal/transaction.go:202 +0x2e9
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1(0xc0003dbce8, 0xc00068bcf8, 0xc00002a2c0)
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:1096 +0x49
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc00002a2c0, 0x2540be400, 0x2540be400, 0x0, 0x0, 0x0, 0x314c3638, 0xed839af41, 0x4b991a0, 0x0, ...)
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:1163 +0xb4d
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc00002a2c0, 0x2540be400, 0x2540be400, 0x0)
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:1049 +0x365
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:518 +0x9ce
```

### PR DESCRIPTION
**Pull request by sincejune**
**Description:**
Hook up `Start` and `Shutdown` functions in fileexporter to avoid nil file handler.

**Testing:**
Manually tested.

### CODE REVIEW

**Comment by sincejune** [comment]
Modified test file as LogExporter, MetricsExporter and TracesExporter are sharing the same file handler in `fileexporter`.

File: exporter/fileexporter/file_exporter.go [hunk 1]
```diff
@@ -72,10 +73,21 @@ func exportMessageAsLine(e *fileExporter, message proto.Message) error {
 func (e *fileExporter) Start(context.Context, component.Host) error {
 	var err error
 	e.file, err = os.OpenFile(e.path, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0600)
+	if err == nil {
```
Comment (carlosalberto) [inline exporter/fileexporter/file_exporter.go:76]: Technically you don't need to set this as the default value is `false`, although this can probably be kept as an explicit statement. Not very important though ;)

**Review by carlosalberto — APPROVED** [review]

File: exporter/fileexporter/file_exporter.go [hunk 2]
```diff
@@ -72,10 +73,21 @@ func exportMessageAsLine(e *fileExporter, message proto.Message) error {
...
+		e.isFileClosed = false
+	}
 	return err
 }
 
 // Shutdown stops the exporter and is invoked during shutdown.
 func (e *fileExporter) Shutdown(context.Context) error {
-	return e.file.Close()
+	if e.isFileClosed {
```
Comment (carlosalberto) [inline exporter/fileexporter/file_exporter.go:84]: It seems you are adding this to prevent calling `file.Close()` more than once, it _may_ be a good option to use the lock to do this. Not sure though, and I will leave that for the maintainers to decide ;)

File: exporter/fileexporter/file_exporter.go [hunk 3]
```diff
@@ -35,9 +35,10 @@ var marshaler = &jsonpb.Marshaler{}
 // fileExporter is the implementation of file exporter that writes telemetry data to a file
 // in Protobuf-JSON format.
 type fileExporter struct {
-	path  string
-	file  io.WriteCloser
-	mutex sync.Mutex
+	path         string
+	file         io.WriteCloser
+	mutex        sync.Mutex
+	isFileClosed bool
```
Comment (bogdandrutu) [inline exporter/fileexporter/file_exporter.go:41]: This is not needed, we do guarantee in the SharedComponent that is called only once. So this can be reverted.

**Review by bogdandrutu — CHANGES_REQUESTED** [review]

File: exporter/fileexporter/file_exporter.go (hunk 3 above)
Comment (sincejune) [reply exporter/fileexporter/file_exporter.go:41]: Actually, I don't think so. I tried to make a fileexporter instance (with current master) shared in traces service and logs services. The `shutdown` was invoked twice.

Comment (sincejune) [reply exporter/fileexporter/file_exporter.go:41]: So do `start` functions.

File: exporter/fileexporter/file_exporter.go (hunk 1 above)
Comment (sincejune) [reply exporter/fileexporter/file_exporter.go:76]: Thanks. I actually would like to remove the flag if the ShareComponent can guarantee `Shutdown` is called only once. Otherwise, I think an explicit statement would be better :)

File: exporter/fileexporter/file_exporter.go (hunk 3 above)
Comment (bogdandrutu) [reply exporter/fileexporter/file_exporter.go:41]: If you create via the factory it should not.

Comment (bogdandrutu) [reply exporter/fileexporter/file_exporter.go:41]: See test that proves my point https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/defaultcomponents/default_exporters_test.go#L163. If I miss something let me konw.

**Review by bogdandrutu — APPROVED** [review]

File: exporter/fileexporter/factory.go [hunk 4]
```diff
@@ -63,7 +69,13 @@ func createMetricsExporter(
 	fe := exporters.GetOrAdd(cfg, func() component.Component {
 		return &fileExporter{path: cfg.(*Config).Path}
 	})
-	return exporterhelper.NewMetricsExporter(cfg, params.Logger, fe.Unwrap().(*fileExporter).ConsumeMetrics)
+	return exporterhelper.NewMetricsExporter(
+		cfg,
+		params.Logger,
+		fe.Unwrap().(*fileExporter).ConsumeMetrics,
+		exporterhelper.WithStart(fe.Start),
+		exporterhelper.WithShutdown(fe.Shutdown),
```
Comment (bogdandrutu) [inline exporter/fileexporter/factory.go:77]: @sincejune here is where you passed the instance start/shutdown instead of the SharedComponent start/shutdown

**Comment by loomis-relativity** [comment]
@sincejune Thanks for the fix. @bogdandrutu We won't be using the v0.27.0 release, so as long as this is fixed going forward, this issue can be closed.

File: exporter/fileexporter/factory.go (hunk 4 above)
Comment (sincejune) [reply exporter/fileexporter/factory.go:77]: @bogdandrutu Thanks! Now I understand.
