### PR TITLE
[confighttp] Reuse zstd reader objects

### LINKED ISSUE #11824: Excessive memory consumption when using ZSTD to receive compressed data
**Describe the bug**
We've seen excessive memory consumption that leads to OOMs when _receiving_ ZSTD-compressed data.

**Steps to reproduce**
1. Enable zstd compression for the HTTP exporter in an upstream collector
2. Observe OOMs in your receiving collector!

You can observe excessive memory via pprof:
image

**What version did you use?**
v0.114.0

### PR DESCRIPTION
**Pull request by ethercrow**
#### Description
Allocating zstd reader objects on every incoming requests leads to a lot of byte buffers being allocated and collected. The compression library recommends reusing readers to avoid these allocations.

#### Link to tracking issue
Fixes #11824

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]

File: config/confighttp/compression.go [hunk 1]
```diff
@@ -51,18 +71,24 @@ var availableDecoders = map[string]func(body io.ReadCloser) (io.ReadCloser, erro
...
+		var err error
+		if v == nil {
+			// NOTE(tigrannajaryan):
 			// Concurrency 1 disables async decoding. We don't need async decoding, it is pointless
 			// for our use-case (a server accepting decoding http requests).
 			// Disabling async improves performance (I benchmarked it previously when working
 			// on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23257).
-			zstd.WithDecoderConcurrency(1),
-		)
+			zr, err = zstd.NewReader(body, zstd.WithDecoderConcurrency(1))
```
Comment (dehaansa) [inline config/confighttp/compression.go:83]: Is there a reason you haven't implemented the New() function in the pool to create the readers?

Comment (ethercrow) [reply config/confighttp/compression.go:83]: Yes, didn’t see a convenient way to return a reader creation error from there.

In general, I looked at how fasthttp does it: https://github.com/valyala/fasthttp/blob/master/zstd.go

Comment (dehaansa) [reply config/confighttp/compression.go:83]: Perfect, thanks for the explanation.

**Review by atoulme — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Thanks @ethercrow! The change looks good, can you post a benchmark to show the performance before and after this change?

**Comment by ethercrow** [comment]
Sorry, I have never run this code. My problem turned out to be in zstd decoding in grpc, which is handled by another library entirely. I was just assuming that the only place in the collector codebase involving zstd decoding must be the culprit.

**Comment by codeboten** [comment]
@ethercrow ah thanks for the update... is this change no longer necessary then?

**Comment by ethercrow** [comment]
I think it's still a good change to make.

I will probably do some real world testing in future, when I have some collectors communicating through otlphttp. Just can't promise any specific date.

**Review by jmacd — APPROVED** [review]
Nice! 

Note that https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal/otelarrow/compression/zstd has re-use, too, good to have.

**Review by codeboten — APPROVED** [review]
Ran some benchmarks before and after the change, change looks good:

```
goos: darwin
goarch: arm64
pkg: go.opentelemetry.io/collector/config/confighttp
cpu: Apple M3 Max
                                │    /tmp/a    │             /tmp/b              │
                                │    sec/op    │    sec/op     vs base           │
ServerWithDecompression/test-14   170.2µ ± ∞ ¹   120.3µ ± ∞ ¹  ~ (p=0.333 n=2) ²

                                │    /tmp/a     │              /tmp/b              │
                                │     B/op      │     B/op       vs base           │
ServerWithDecompression/test-14   14.18Mi ± ∞ ¹   11.44Mi ± ∞ ¹  ~ (p=0.333 n=2) ²

                                │   /tmp/a    │             /tmp/b             │
                                │  allocs/op  │  allocs/op   vs base           │
ServerWithDecompression/test-14   262.5 ± ∞ ¹   254.5 ± ∞ ¹  ~ (p=0.333 n=2) ²
```
