### PR TITLE
[service] Fix panic when not using `NewCommand`

### LINKED ISSUE #4138: Running the Collector panics if service.NewCommand is not called first
**Describe the bug**

Running the Collector through the `Run` function without using `service.NewCommand` first will cause a panic because of nil flag pointers.

**Steps to reproduce**

The following example (adapted from [`TestCollector_StartAsGoRoutine`](https://github.com/open-telemetry/opentelemetry-collector/blob/b39f52bfe67b03d0ff7b3601d3b48bf1ce41c8ac/service/collector_test.go#L164)) will trigger the panic.

```go
package main

import (
	"context"
	"strings"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/service"
	"go.opentelemetry.io/collector/service/defaultcomponents"
	"go.opentelemetry.io/collector/service/parserprovider"
)

const configStr = `
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp:
    endpoint: "localhost:4317"
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
`

func main() {
	factories, err := defaultcomponents.Components()
	if err != nil {
		panic(err)
	}
	set := service.CollectorSettings{
		BuildInfo:         component.NewDefaultBuildInfo(),
		Factories:         factories,
		ConfigMapProvider: parserprovider.NewInMemoryMapProvider(strings.NewReader(configStr)),
	}
	col, err := service.New(set)
	if err != nil {
		panic(err)
	}

	err = col.Run(context.Background()) // panic happens here
	if err != nil {
		panic(err)
	}
}
```

**What did you expect to see?**

The Collector does not panic at start.

**What did you see instead?**

The Collector panics:

```
❯ ./panictest 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x460bec4]

goroutine 1 [running]:
go.opentelemetry.io/collector/service/internal/telemetrylogs.logDeprecatedMessages(0xc0000ba8e0)
        /Users/{my user}/Source/otel/opentelemetry-collector/service/internal/telemetrylogs/logger.go:79 +0x24
go.opentelemetry.io/collector/service/internal/telemetrylogs.NewLogger({0x20, 0x6d, {0x48e4daf, 0xc000193950}}, {0x0, 0x0, 0x0})
        /Users/{my user}/Source/otel/opentelemetry-collector/service/internal/telemetrylogs/logger.go:74 +0x2d4
go.opentelemetry.io/collector/service.(*Collector).setupConfigurationComponents(0xc0003f80f0, {0x49f9f88, 0xc0000360c8})
        /Users/{my user}/Source/otel/opentelemetry-collector/service/collector.go:171 +0x195
go.opentelemetry.io/collector/service.(*Collector).Run(0xc0003f80f0, {0x49f9f88, 0xc0000360c8})
        /Users/{my user}/Source/otel/opentelemetry-collector/service/collector.go:223 +0x26e
main.main()
        /Users/{my user}/Source/otel/opentelemetry-collector/panictest/main.go:43 +0x23c
```

**What version did you use?**

I can reproduce with b39f52bfe67b03d0ff7b3601d3b48bf1ce41c8ac

**What config did you use?**

n/a

**Environment**

Not relevant

**Additional context**

This happens because the flags are nil by default.

It does not happen in the `TestCollector_StartAsGoRoutine` since previous tests call `NewCommand` and thus initialize the flags.

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

- Reorder tests to trigger bug
- Add default value to flags

**Link to tracking Issue:** Fixes #4138

**Testing:** Reordered tests to trigger the panic

### CODE REVIEW

**Comment by mx-psi** [comment]
Not sure why this makes other tests fail:

```
    collector_test.go:198: 
        	Error Trace:	collector_test.go:198
        	            				collector_test.go:143
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:46329/metrics": dial tcp [::1]:46329: connect: connection refused
        	Test:       	TestCollector_Start
--- FAIL: TestCollector_Start (0.02s)
```

**Comment by bogdandrutu** [comment]
@mx-psi it is still expected to crash since the issue https://github.com/open-telemetry/opentelemetry-collector/issues/4138 is not yet resolved, but I believe this is good to speed-up that issue.

**Comment by mx-psi** [comment]
> Not sure why this makes other tests fail

This happens because telemetry is initialized only one https://github.com/open-telemetry/opentelemetry-collector/blob/b39f52bfe67b03d0ff7b3601d3b48bf1ce41c8ac/service/telemetry.go#L60-L64 I can refactor this to improve tests but I would rather do it in a different PR

**Review by tigrannajaryan — APPROVED** [review]
Does this fully fix https://github.com/open-telemetry/opentelemetry-collector/issues/4138 or there is more work to do? If fixed would be nice to add a test to show it is fixed.

**Comment by mx-psi** [comment]
> Does this fully fix #4138 or there is more work to do?

Yes, the example program does not crash at startup and in general this class of crashes should be gone.

>  If fixed would be nice to add a test to show it is fixed.

I thought I needed to do more work to work around `collectorTelemetry` for adding a test, but it was easier than I expected, added in the last commit :)

File: service/collector_test.go [hunk 1]
```diff
@@ -63,6 +63,56 @@ service:
       exporters: [otlp]
 `
 
+// colTelemetryTest initializes telemetry without affecting the global sync.Once.
+type colTelemetryTest struct {
```
Comment (bogdandrutu) [inline service/collector_test.go:67]: Why is this needed instead of using directly your own instance of colTelemetry?

File: internal/collector/telemetry/telemetry.go [hunk 2]
```diff
@@ -25,11 +25,14 @@ const (
...
 
 var (
+	metricsAddrDefault   = ":8888"
+	metricsPrefixDefault = "otelcol"
+	addInstanceIDDefault = true
 	// Command-line flags that control publication of telemetry data.
-	metricsAddrPtr   *string
-	metricsPrefixPtr *string
+	metricsAddrPtr   = &metricsAddrDefault
+	metricsPrefixPtr = &metricsPrefixDefault
```
Comment (Aneurysm9) [inline internal/collector/telemetry/telemetry.go:33]:
```suggestion
	metricsAddrPtr   = new(string)
	metricsPrefixPtr = new(string)
```

Would this be safer?  Does anything use the default value that might break if it changes when the user specifies this value via CLI flags?

File: service/collector_test.go (hunk 1 above)
Comment (mx-psi) [reply service/collector_test.go]: There was no need, fixed :)

File: internal/collector/telemetry/telemetry.go (hunk 2 above)
Comment (mx-psi) [reply internal/collector/telemetry/telemetry.go:33]: On this particular instance it would be fine to just use `new`, but on the logs side it's not https://github.com/open-telemetry/opentelemetry-collector/blob/afad36e3785b78906f6eb5f9e91354a9e05a274c/service/internal/telemetrylogs/logger.go#L78-L90 since you need the value to be `"deprecated"`. I would prefer to leave it like this for consistency
