### PR TITLE
[exporter/debug] Guard from out of bounds profiles dictionary indices

### LINKED ISSUE #14803: [exporter/debug] should check for index out of range for profiles dictionary
### Component(s)

exporter/debug

### What happened?

**Describe the bug**
A previous bug in the pprofreceiver caused profiles to be emitted without dictionary data, causing the debugexporter to panic searching an index which does not exist in the dictionary
i've submitted a PR to fix the pprofreceiver but it might happen in the future for other profiles component, and the debugexporter should be resilient to this case. it should fail with a proper error instead of panicing
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/14790#issuecomment-4081292262
**Steps to reproduce**

run collector with provided config and run service exposing pprof on port 6060
**What did you expect to see?**

errors printed that debug exporter could not parse profiles data

**What did you see instead?**

Log output

### Collector version

v0.147.1-0.20260313183754-7cd8f588399b

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
    pprof:
      endpoint: http://localhost:6060/debug/pprof/heap
      collection_interval: 10s

  exporters:
    debug:
      verbosity: detailed

  service:
    pipelines:
      profiles:
        receivers: [pprof]
        exporters: [debug]
```

### Log output

```shell
panic: runtime error: index out of range [4] with length 0

goroutine 59 [running]:
go.opentelemetry.io/collector/pdata/pprofile.KeyValueAndUnitSlice.At(...)
	/go/pkg/mod/go.opentelemetry.io/collector/pdata/pprofile@v0.147.1-0.20260313183754-7cd8f588399b/generated_keyvalueandunitslice.go:55
go.opentelemetry.io/collector/exporter/debugexporter/internal/normal.normalProfilesMarshaler.MarshalProfiles({}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/debugexporter@v0.147.1-0.20260313183754-7cd8f588399b/internal/normal/profiles.go:50 +0x81c
go.opentelemetry.io/collector/exporter/debugexporter.(*debugExporter).pushProfiles(0x40001e8870, {0x0?, 0x0?}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/debugexporter@v0.147.1-0.20260313183754-7cd8f588399b/exporter.go:114 +0x170
go.opentelemetry.io/collector/consumer/xconsumer.ConsumeProfilesFunc.ConsumeProfiles(0x40002063c0?, {0x233c8d8?, 0x4000726d20?}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/consumer/xconsumer@v0.147.1-0.20260313183754-7cd8f588399b/profiles.go:31 +0x44
go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper.NewProfiles.requestConsumeFromProfiles.func2({0x233c8d8?, 0x4000726d20?}, {0x2333ed0?, 0x400042abb8?})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper@v0.147.0/profiles.go:156 +0x50
go.opentelemetry.io/collector/exporter/exporterhelper/internal/sender.(*sender[...]).Send(...)
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper@v0.147.0/internal/sender/sender.go:31
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*obsReportSender[...]).Send(0x2334c60, {0x233c910, 0x40002063c0?}, {0x2333ed0?, 0x400042abb8})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper@v0.147.0/internal/obs_report_sender.go:105 +0x7c
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Send(0x4000438248, {0x233c910, 0x40002063c0}, {0x2333ed0, 0x400042abb8})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper@v0.147.0/internal/base_exporter.go:113 +0x68
go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper.NewProfilesRequest.newConsumeProfiles.func1({0x233c910, 0x40002063c0}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper@v0.147.0/profiles.go:211 +0x1d4
go.opentelemetry.io/collector/consumer/xconsumer.ConsumeProfilesFunc.ConsumeProfiles(...)
	/go/pkg/mod/go.opentelemetry.io/collector/consumer/xconsumer@v0.147.1-0.20260313183754-7cd8f588399b/profiles.go:31
go.opentelemetry.io/collector/service/internal/refconsumer.refProfiles.ConsumeProfiles({{0xffff74166028?, 0x40001f4c60?}}, {0x233c910?, 0x40002063c0?}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/service@v0.147.1-0.20260313183754-7cd8f588399b/internal/refconsumer/profiles.go:30 +0x94
go.opentelemetry.io/collector/consumer/xconsumer.ConsumeProfilesFunc.ConsumeProfiles(...)
	/go/pkg/mod/go.opentelemetry.io/collector/consumer/xconsumer@v0.147.1-0.20260313183754-7cd8f588399b/profiles.go:31
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/receivercreator.(*enhancingConsumer).ConsumeProfiles(0x40000eab90, {0x233c910, 0x40002063c0}, {0x40000c5200?, 0x40001be0e8?})
	/src/receiver/receivercreator/consumer.go:137 +0xd4
go.opentelemetry.io/collector/scraper/scraperhelper/xscraperhelper.scrapeProfiles(0x400049eba0, {0x232a620, 0x40000eab90})
	/go/pkg/mod/go.opentelemetry.io/collector/scraper/scraperhelper/xscraperhelper@v0.147.1-0.20260313183754-7cd8f588399b/controller.go:135 +0x28c
go.opentelemetry.io/collector/scraper/scraperhelper/xscraperhelper.NewProfilesController.func1(0x6fc23ac00?)
	/go/pkg/mod/go.opentelemetry.io/collector/scraper/scraperhelper/xscraperhelper@v0.147.1-0.20260313183754-7cd8f588399b/controller.go:109 +0x20
go.opentelemetry.io/collector/scraper/scraperhelper/internal/controller.(*Controller[...]).startScraping.func1()
	/go/pkg/mod/go.opentelemetry.io/collector/scraper/scraperhelper@v0.147.1-0.20260313183754-7cd8f588399b/internal/controller/controller.go:113 +0xe4
sync.(*WaitGroup).Go.func1()
	/usr/local/go/src/sync/waitgroup.go:239 +0x4c
created by sync.(*WaitGroup).Go in goroutine 53
	/usr/local/go/src/sync/waitgroup.go:237 +0x70
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by NimrodAvni78**
#### Description
check before accessing profiles dictionary indices and fail gracefully if they are out of bounds

#### Link to tracking issue
Fixes #14803

#### Testing
Added tests to prove missing dictionary indices fail and don't panic

### CODE REVIEW

**Comment by dmathieu** [comment]
I wonder if a better behavior wouldn't be to output the error, rather than returning an error and forgetting about the rest of the data.

**Comment by NimrodAvni78** [comment]
@dmathieu your saying ignoring every value which is not found in the dictionary?

we can also add a mock value like `[Missing Item at index $index]`

**Comment by dmathieu** [comment]
Yes, that's what I mean.

cc @florianl

**Comment by NimrodAvni78** [comment]
yeah i can reimplement it to work like that
should we omit the value entirely and warn to log? or add this kind of "mock value" like i suggested
since this can probably be in all parts, like attribute names, attributes values, sample_type and so on

**Comment by dmathieu** [comment]
I wouldn't warn to logs. Having to go from debug output to log warnings to see there are issues, and then figuring out where they are wouldn't be so easy if we log.
Your `[Missing Dictionary Item #<INDEX>]` sounds good to me.

File: exporter/debugexporter/internal/normal/profiles.go [hunk 1]
```diff
@@ -47,8 +47,18 @@ func (normalProfilesMarshaler) MarshalProfiles(pd pprofile.Profiles) ([]byte, er
 				if profile.AttributeIndices().Len() > 0 {
 					attrs := []string{}
 					for _, i := range profile.AttributeIndices().AsRaw() {
-						a := dic.AttributeTable().At(int(i))
-						attrs = append(attrs, fmt.Sprintf("%s=%s", dic.StringTable().At(int(a.KeyStrindex())), a.Value().AsString()))
+						attrIdx := int(i)
+						if attrIdx >= dic.AttributeTable().Len() {
+							attrs = append(attrs, fmt.Sprintf("[Missing Dictionary Item #%d]", attrIdx))
```
Comment (dmathieu) [inline exporter/debugexporter/internal/normal/profiles.go]: Sorry for the back and forth.


```suggestion
							attrs = append(attrs, fmt.Sprintf("[Missing Dictionary AttributeTable Item #%d]", attrIdx))
```

File: exporter/debugexporter/internal/normal/profiles.go [hunk 2]
```diff
@@ -47,8 +47,18 @@ func (normalProfilesMarshaler) MarshalProfiles(pd pprofile.Profiles) ([]byte, er
...
+							continue
+						}
+						a := dic.AttributeTable().At(attrIdx)
+						keyIdx := int(a.KeyStrindex())
+						key := fmt.Sprintf("[Missing Dictionary Item #%d]", keyIdx)
```
Comment (dmathieu) [inline exporter/debugexporter/internal/normal/profiles.go]:
```suggestion
						key := fmt.Sprintf("[Missing Dictionary Key String Item #%d]", keyIdx)
```

File: exporter/debugexporter/internal/otlptext/databuffer.go [hunk 3]
```diff
@@ -350,8 +350,18 @@ func (b *dataBuffer) logProfileSamples(ss pprofile.SampleSlice, dic pprofile.Pro
 		if lai := sample.AttributeIndices().Len(); lai > 0 {
 			b.logEntry("        Attributes:")
 			for j := range lai {
-				attr := dic.AttributeTable().At(int(sample.AttributeIndices().At(j)))
-				b.logEntry("             -> %s: %s", dic.StringTable().At(int(attr.KeyStrindex())), attr.Value().AsRaw())
+				attrIdx := int(sample.AttributeIndices().At(j))
+				if attrIdx >= dic.AttributeTable().Len() {
+					b.logEntry("             -> [Missing Dictionary Item #%d]", attrIdx)
```
Comment (dmathieu) [inline exporter/debugexporter/internal/otlptext/databuffer.go]:
```suggestion
					b.logEntry("             -> [Missing Dictionary AttributeTable Item #%d]", attrIdx)
```

File: exporter/debugexporter/internal/otlptext/databuffer.go [hunk 4]
```diff
@@ -350,8 +350,18 @@ func (b *dataBuffer) logProfileSamples(ss pprofile.SampleSlice, dic pprofile.Pro
...
+					continue
+				}
+				attr := dic.AttributeTable().At(attrIdx)
+				keyIdx := int(attr.KeyStrindex())
+				key := fmt.Sprintf("[Missing Dictionary Item #%d]", keyIdx)
```
Comment (dmathieu) [inline exporter/debugexporter/internal/otlptext/databuffer.go]:
```suggestion
				key := fmt.Sprintf("[Missing Dictionary Key String Item #%d]", keyIdx)
```

File: .chloggen/debugexporter-profiles-guard-missing-dictionary-index.yaml [hunk 5]
```diff
@@ -0,0 +1,25 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. receiver/otlp)
+component: exporter/debug
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Guard exporter/debug from out of bounds profiles dictionary indices
```
Comment (andrzej-stencel) [inline .chloggen/debugexporter-profiles-guard-missing-dictionary-index.yaml]:
```suggestion
note: Guard from out of bounds profiles dictionary indices
```

File: exporter/debugexporter/internal/normal/profiles.go [hunk 6]
```diff
@@ -47,8 +47,18 @@ func (normalProfilesMarshaler) MarshalProfiles(pd pprofile.Profiles) ([]byte, er
 				if profile.AttributeIndices().Len() > 0 {
 					attrs := []string{}
 					for _, i := range profile.AttributeIndices().AsRaw() {
-						a := dic.AttributeTable().At(int(i))
-						attrs = append(attrs, fmt.Sprintf("%s=%s", dic.StringTable().At(int(a.KeyStrindex())), a.Value().AsString()))
+						attrIdx := int(i)
+						if attrIdx >= dic.AttributeTable().Len() {
+							attrs = append(attrs, fmt.Sprintf("[Missing Dictionary AttributeTable Item #%d]", attrIdx))
+							continue
+						}
```
Comment (bogdandrutu) [inline exporter/debugexporter/internal/normal/profiles.go:54]: @dmathieu how can this happen? Should we validate the input and this should never happen in practice? Will be extremely hard to use if this check is needed every time we access the profiles.

Comment (dmathieu) [reply exporter/debugexporter/internal/normal/profiles.go:54]: We do validate the input on the receivers we control. But we can't control every receiver.
