### PR TITLE
Prometheus Receiver: Print a more informative message about 'up' metric value

### LINKED ISSUE #1825: Misleading error message for invalid "up" metric value in Prometheus receiver
**Describe the bug**
The `up` metric is considered special by Prometheus receiver and must always contain a constant value of `1.0`.
This concept is documented in https://www.prometheus.io/docs/concepts/jobs_instances/:
> `up{job="<job-name>", instance="<instance-id>"}`: `1` if the instance is healthy, i.e. reachable, or `0` if the scrape failed.
> ...
> The `up` time series is useful for instance availability monitoring.

The issue is that when the value differs from `1.0`, Prometheus receiver prints a generic error message `"http client error"`: https://github.com/open-telemetry/opentelemetry-collector/blob/cba929da651544f953a627260352e6b145eb8f01/receiver/prometheusreceiver/internal/metricsbuilder.go#L115
e.g.
```
{
  "level":"warn",
  "ts":1600755340.4938133,
  "caller":"internal/metricsbuilder.go:115",
  "msg":"http client error",
  "component_kind":"receiver",
  "component_type":"prometheus",
  "component_name":"prometheus",
  "timestamp":1600755339676,
  "value":0,
  "labels":"map[instance:<ip>:<port> job:k8sapps kubernetes_pod_name:podname]"
}
```
i.e. doesn't mention anything about the `up` metric.

**Steps to reproduce**
Configure Prometheus to scrape a non-existent endpoint. This should produce the `up` metric with a value `0`.

**What did you expect to see?**
A more informative message, e.g. `"Scraping failed: the 'up' metric had a value 0"`.
We should also check specifically for `0` and in case it's different from 0/1 return a validation error instead.

**What did you see instead?**
`"msg":"http client error"`

**What version did you use?**
Version: `v0.10.0` / `master`

### PR DESCRIPTION
**Pull request by nilebox**
**Description:**
- Handle `0` separately from other (invalid) values and print informative log message.
- Delete unused OpenCensus metric

**Link to tracking Issue:** Fixes #1825

### CODE REVIEW

File: receiver/prometheusreceiver/internal/transaction.go [hunk 1]
```diff
@@ -159,14 +156,6 @@ func (tr *transaction) Commit() error {
 		return err
 	}
 
-	if tr.metricBuilder.hasInternalMetric {
-		m := ochttp.ClientRoundtripLatency.M(tr.metricBuilder.scrapeLatencyMs)
```
Comment (nilebox) [inline receiver/prometheusreceiver/internal/transaction.go:163]: Removed redundant OC metric and related code since it must be registered via OpenCensus view to be used which we don't do in the collector.

**Review by dmitryax — APPROVED** [review]
LGTM

**Comment by bogdandrutu** [comment]
@nilebox please fix lint issues.

**Comment by nilebox** [comment]
@bogdandrutu fixed.
