### PR TITLE
fix(otlphttpexporter): show actual destination URL in error messages

### LINKED ISSUE #14673: otlphttpexporter: Error messages show original URL instead of actual destination when middleware modifies request
### Component(s)

exporter/otlp_http

### What happened?

**Problem**
When using middleware extensions that modify the request URL (e.g., for dynamic routing), HTTP error messages from otlphttpexporter show the original placeholder URL instead of the actual destination URL.

For example, with a middleware that routes requests from http://localhost:4318/v1/logs to https://actual-destination.example.com/v1/logs, the error message shows:

`no more retries left: failed to make an HTTP request: Post "http://localhost:4318/v1/logs": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

The URL http://localhost:4318/v1/logs is misleading - the actual request was sent to https://actual-destination.example.com/v1/logs.

**Root Cause**
Go's net/http package wraps transport errors in a *url.Error struct that captures the request URL before any RoundTripper middleware executes. This happens internally in http.Client.Do():
`// From net/http/client.go
func (c *Client) do(req *Request) (retres *Response, reterr error) {
    // ...
    if err != nil {
        // URL is captured here, before RoundTripper chain runs
        return nil, &url.Error{Op: urlErrorOp(req.Method), URL: req.URL.String(), Err: err}
    }
}
`
Even if middleware modifies req.URL, the *url.Error is created with the original URL.

**Proposed Solution**
In exporter/otlphttpexporter/otlp.go, unwrap the *url.Error and reconstruct it with the correct URL:
resp, err := e.client.Do(req)if err != nil {    var urlErr *url.Error    if errors.As(err, &urlErr) {        // Replace the URL in the error with the actual destination URL        urlErr.URL = req.URL.String()    }    return fmt.Errorf("failed to make an HTTP request: %w", err)}
Or alternatively, construct a new error entirely:
resp, err := e.client.Do(req)if err != nil {    var urlErr *url.Error    if errors.As(err, &urlErr) {        return fmt.Errorf("failed to make an HTTP request: %s %q: %w",             urlErr.Op, req.URL, urlErr.Err)    }    return fmt.Errorf("failed to make an HTTP request to %s: %w", req.URL, err)}
This would produce:
failed to make an HTTP request: Post "https://actual-destination.example.com/v1/logs": context deadline exceeded

**Use Case**
This is important for scenarios where:
Middleware extension dynamically updates the destination endpoint

### Collector version

v0.146.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by EdgeN8v**
Fixes #14673 

**Description:**
When a middleware extension modifies the request URL, HTTP error messages from `otlphttpexporter` previously showed the original placeholder URL. This PR unwraps the `*url.Error` returned by `http.Client.Do()` and replaces the URL in the error message with the actual modified destination URL (`req.URL`), preventing misleading error logs. 

Added unit tests to verify the behavior.

### CODE REVIEW

File: exporter/otlphttpexporter/otlp_test.go [hunk 1]
```diff
@@ -1174,3 +1175,42 @@ type badReader struct{}
...
+
+func (t *mockTransport) RoundTrip(req *http.Request) (*http.Response, error) {
+	return t.roundTripFunc(req)
+}
+
+func TestExport_ErrorShowsModifiedURL(t *testing.T) {
+	originalURL := "http://localhost:4318/v1/logs"
+	modifiedURL := "https://actual-destination.example.com/v1/logs"
+
+	mockTransport := &mockTransport{
```
Comment (dmathieu) [inline exporter/otlphttpexporter/otlp_test.go]: You're overriding a mock struct with the variable name here, which is quite misleading.


```suggestion
	transport := &mockTransport{
```

File: exporter/otlphttpexporter/otlp_test.go [hunk 2]
```diff
@@ -1174,3 +1175,42 @@ type badReader struct{}
...
+		roundTripFunc: func(req *http.Request) (*http.Response, error) {
+			parsedModified, _ := url.Parse(modifiedURL)
```
Comment (dmathieu) [inline exporter/otlphttpexporter/otlp_test.go]:
```suggestion
			parsedModified, err := url.Parse(modifiedURL)
			require.NoError(t, err)
```

File: exporter/otlphttpexporter/otlp_test.go [hunk 3]
```diff
@@ -1174,3 +1175,42 @@ type badReader struct{}
...
+			req.URL = parsedModified
+
+			return nil, context.DeadlineExceeded
```
Comment (dmathieu) [inline exporter/otlphttpexporter/otlp_test.go]: How about returning a custom error here?


```suggestion
			return nil, errors.New("we need an error logged")
```

File: exporter/otlphttpexporter/otlp.go [hunk 4]
```diff
@@ -173,9 +173,9 @@ func (e *baseExporter) pushProfiles(ctx context.Context, td pprofile.Profiles) e
 	return e.export(ctx, e.profilesURL, request, e.profilesPartialSuccessHandler)
 }
 
-func (e *baseExporter) export(ctx context.Context, url string, request []byte, partialSuccessHandler partialSuccessHandler) error {
-	e.logger.Debug("Preparing to make HTTP request", zap.String("url", url))
-	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(request))
+func (e *baseExporter) export(ctx context.Context, requestURL string, request []byte, partialSuccessHandler partialSuccessHandler) error {
```
Comment (dmathieu) [inline exporter/otlphttpexporter/otlp.go:176]: I'm not sure we should rename this variable.

Comment (EdgeN8v) [reply exporter/otlphttpexporter/otlp.go:176]: I renamed it to avoid shadowing the `net/url` package. Without the rename, using `*url.Error` triggers a compiler error (`url.Error is not a type`) because the compiler thinks `url` refers to the string parameter.
