### PR TITLE
[chore][confmap] Show that issue 10799 is fixed

### LINKED ISSUE #10799: Issue using environment variable for pipelines
**Describe the bug**
Environment variables used for pipelines are not processed correctly in 0.106.1, while they worked in 0.105.0. I have tried to put the value in double quotes and disable the confmap.strictlyTypedInput feature gate without success.

I a receiving an error instead.

When using confmap.strictlyTypedInput
failed to get config: cannot resolve the configuration: expanding ${env:OTEL_LOGS_RECEIVER}: retrieved value does not have unambiguous string representation: [filelog windowseventlog/application]

When using -confmap.strictlyTypedInput
failed to get config: cannot resolve the configuration: expanding ${env:OTEL_LOGS_RECEIVER}: expected convertable to string value type, got ["filelog" "windowseventlog/application"]([]interface {})

**What version did you use?**
0.106.1

**What config did you use?**
```
    logs:
      receivers: ${env:OTEL_LOGS_RECEIVER}
      processors: [memory_limiter,resourcedetection/system,resource/environment,transform,filter,batch]
      exporters: ${env:OTEL_LOGS_EXPORTER}
```

With [filelog,windowseventlog/application]  as the environment value for OTEL_LOGS_RECEIVER as an example.

**Environment**
Windows 2022 Server

### PR DESCRIPTION
**Pull request by mx-psi**
#### Description

Shows that #10795 (as well as #10800) fixed this issue.

#### Link to tracking issue

Fixes #10799

### CODE REVIEW

File: confmap/internal/e2e/types_test.go [hunk 1]
```diff
@@ -634,3 +634,52 @@ logging:
 		cfgStr.Field,
 	)
 }
+
+func TestIssue10799(t *testing.T) {
```
Comment (songy23) [inline confmap/internal/e2e/types_test.go:638]: Can we give it a more descriptive name, like TestEnvVarInPipeline etc.?

Same for the file names

Comment (codeboten) [reply confmap/internal/e2e/types_test.go:638]: might be worth adding a link to the issue in a comment in the test

**Review by TylerHelmuth — APPROVED** [review]

File: confmap/internal/e2e/types_test.go (hunk 1 above)
Comment (mx-psi) [reply confmap/internal/e2e/types_test.go]: Done!

**Review by songy23 — APPROVED** [review]
