### PR TITLE
[service] Validate pipeline type against component types

### LINKED ISSUE #8007: `validate` command does not validate pipeline type
**Describe the bug**

Thew `validate` command intoduced in https://github.com/open-telemetry/opentelemetry-collector/pull/7835 does not validate the type of pipeline a component is assigned to. For example, if a metrics-only component is used in a logs pipeline, validation passes, but I would expect it to fail.

**Steps to reproduce**

- Download the latest contrib distro (to have access to various types of components) from https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.80.0
- Prepare a config file that uses components in invalid pipeline types, see below.
- Run the collector to verify that the configuration is invalid:

```console
$ otelcol-contrib-0.80.0-linux_amd64 --config config.yaml 
2023-07-03T11:49:33.120+0200    info    service/telemetry.go:81 Setting up own telemetry...
2023-07-03T11:49:33.120+0200    info    service/telemetry.go:104        Serving Prometheus metrics      {"address": ":8888", "level": "Basic"}
2023-07-03T11:49:33.120+0200    info    exporter@v0.80.0/exporter.go:275        Stability level of component is undefined       {"kind": "exporter", "data_type": "logs", "name": "prometheus"}
Error: failed to build pipelines: failed to create "prometheus" exporter for data type "logs": telemetry type is not supported
2023/07/03 11:49:33 collector server run finished with error: failed to build pipelines: failed to create "prometheus" exporter for data type "logs": telemetry type is not supported
```

- Run the `validate` command:

```console
$ otelcol-contrib-0.80.0-linux_amd64 validate --config config.yaml
$ echo $?
0
```

**What did you expect to see?**
Validation fails

**What did you see instead?**
Validation succeeds

**What version did you use?**
`v0.80.0`

**What config did you use?**

```yaml
exporters:
  awscloudwatchlogs:
    log_group_name: x
    log_stream_name: x
  jaeger:
    endpoint: x
  prometheus:

receivers:
  filelog:
  httpcheck:
    endpoint: x
  zipkin:

service:
  pipelines:
    logs:
      exporters:
      - prometheus # metrics-only
      receivers:
      - zipkin # traces-only

    metrics:
      exporters:
      - jaeger # traces-only
      receivers:
      - filelog # logs-only

    traces:
      exporters:
      - awscloudwatchlogs # logs-only
      receivers:
      - httpcheck # metrics-only
```

**Environment**
OS: Ubuntu 23.04 lunar

**Additional context**

Currently, there is no documentation describing to what extent the validation works. I believe it's reasonable for the user to assume the pipeline types would be validated. I understand that what the `validate` command does under the hood is just run `Validate()` on the config object.

### PR DESCRIPTION
**Pull request by ycombinator**
**Description:** <Describe what has changed.>

This change adds another layer of validation to pipelines. It validates that all the components in a pipeline are of the same type as the pipeline.

For example, if a `metrics` pipeline contains a `traces`-only receiver, the `otelcol validate -config ...` command will fail.

**Link to tracking Issue:** 
Fixes #8007.

**Testing:** 
Added unit test + existing tests are passing.

**Documentation:**
godoc.

### CODE REVIEW

File: service/service.go [hunk 1]
```diff
@@ -141,6 +146,39 @@ func New(ctx context.Context, set Settings, cfg Config) (*Service, error) {
 	return srv, nil
 }
 
+func Validate(ctx context.Context, set Settings, cfg Config) error {
```
Comment (sfc-gh-bdrutu) [inline service/service.go:149]: Why public?

File: service/service.go [hunk 2]
```diff
@@ -128,6 +128,11 @@ func New(ctx context.Context, set Settings, cfg Config) (*Service, error) {
 	srv.telemetrySettings.MeterProvider = srv.telemetryInitializer.mp
 	srv.telemetrySettings.TracerProvider = srv.telemetryInitializer.tp
 
+	// validate the configuration
+	if err := validate(ctx, set, cfg, srv.telemetrySettings); err != nil {
+		return nil, err
+	}
```
Comment (sfc-gh-bdrutu) [inline service/service.go:134]: Would we not find out about this error anyway when we call `graph.Build`?

File: service/service.go [hunk 3]
```diff
@@ -141,6 +146,39 @@ func New(ctx context.Context, set Settings, cfg Config) (*Service, error) {
...
+	tel, err := telemetry.New(ctx, telemetry.Settings{ZapOptions: set.LoggingOptions}, cfg.Telemetry)
+	if err != nil {
+		return fmt.Errorf("failed to get logger: %w", err)
+	}
+
+	telSettings := servicetelemetry.TelemetrySettings{
+		Logger:         tel.Logger(),
+		TracerProvider: tel.TracerProvider(),
+		MeterProvider:  noop.NewMeterProvider(),
+	}
```
Comment (sfc-gh-bdrutu) [inline service/service.go:159]: Why not using `noop` everywhere?

File: service/service.go (hunk 1 above)
Comment (ycombinator) [reply service/service.go:149]: Because it's being called from the `otelcol` package.

File: service/service.go (hunk 2 above)
Comment (ycombinator) [reply service/service.go:134]: Yes, that's true.  I was trying to validate it even earlier than that but you're right — it doesn't really matter.  Removing this call, thanks for catching it.

Comment (ycombinator) [reply service/service.go]: Removed in 8729b39daebf2056602e2a9016b6cf714266ff21.

File: service/service.go (hunk 3 above)
Comment (ycombinator) [reply service/service.go:147]: Do you mean for the `Logger` and `TracerProvider` fields?  I'm not seeing anything in the `noop` package that could be used to initialize those fields.

**Comment by ycombinator** [comment]
PR is still active; waiting on review.

**Comment by ycombinator** [comment]
Hi @bogdandrutu, would you mind kicking off the CI checks again on this PR, please? Thanks!

**Comment by ycombinator** [comment]
Thanks @atoulme, for kicking off CI again.  I've fixed another linter error (from `impi`) in 8b53d4ea9. Would you mind kicking off CI one more time, please? Thank you.

BTW, I noticed that CI, specifically the `contrib-tests / contrib-tests-matrix (receiver-1) (pull_request)` check, is [failing](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/7879312495/job/21499696810?pr=9257) on these tests from `opentelemetry-collector-contrib`:

```
--- FAIL: TestScrape (0.06s)
    --- FAIL: TestScrape/Standard (0.01s)
        network_scraper_test.go:234: 
            	Error Trace:	/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:234
            	            				/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:203
            	Error:      	Not equal: 
            	            	expected: 12
            	            	actual  : 13
            	Test:       	TestScrape/Standard
    --- FAIL: TestScrape/Standard_with_direction_removed (0.01s)
        network_scraper_test.go:234: 
            	Error Trace:	/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:234
            	            				/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:203
            	Error:      	Not equal: 
            	            	expected: 12
            	            	actual  : 13
            	Test:       	TestScrape/Standard_with_direction_removed
    --- FAIL: TestScrape/Validate_Start_Time (0.01s)
        network_scraper_test.go:234: 
            	Error Trace:	/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:234
            	            				/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:203
            	Error:      	Not equal: 
            	            	expected: 12
            	            	actual  : 13
            	Test:       	TestScrape/Validate_Start_Time
    --- FAIL: TestScrape/Include_Filter_that_matches_nothing (0.01s)
        network_scraper_test.go:234: 
            	Error Trace:	/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:234
            	            				/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:203
            	Error:      	Not equal: 
            	            	expected: 12
            	            	actual  : 13
            	Test:       	TestScrape/Include_Filter_that_matches_nothing
    --- FAIL: TestScrape/Conntrack_error_ignored_if_metric_disabled (0.01s)
        network_scraper_test.go:234: 
            	Error Trace:	/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:234
            	            				/tmp/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go:203
            	Error:      	Not equal: 
            	            	expected: 12
            	            	actual  : 13
            	Test:       	TestScrape/Conntrack_error_ignored_if_metric_disabled
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper	0.081s
```

I'm not following how the failing assertion in a test for the `hostmetricsreceiver` component might be failing because of the change in this PR here. 🤔

**Comment by ycombinator** [comment]
> It's possible contrib CI is broken. Rerunning.

Thanks.  Or could it be because I'm not a OTel Community member (yet)?

**Comment by atoulme** [comment]
Nothing like that, we just run CI by checking out the latest main of contrib, which can break.

FWIW CI doesn't run for you on commit because this is your first PR. After you have a commit in the repository, CI will run when you push to your branch without our intervention.

**Comment by ycombinator** [comment]
Hi @atoulme, could you please guide me on what's needed to merge this PR? I'm afraid it will be closed in 14 days otherwise due to being stale. Thanks!

**Comment by atoulme** [comment]
> Hi @atoulme, could you please guide me on what's needed to merge this PR? I'm afraid it will be closed in 14 days otherwise due to being stale. Thanks!

you ask for review by pinging approvers. I'm not an approver. You can participate in the SIG meeting as well, which is happening right now, to ask for review.

File: service/service.go (hunk 1 above)
Comment (atoulme) [reply service/service.go:134]: @ycombinator please take this as strong feedback that adding new public API to packages is discouraged at this time. Please add a godoc comment and prepare to discuss why this must be public.

Comment (ycombinator) [reply service/service.go:134]: Got it, thanks for letting me know about trying not to increase the public API surface.  It makes sense.  Let me see if I can reimplement this functionality without adding to the public API, otherwise I will add a godoc here.

**Comment by ycombinator** [comment]
> you ask for review by pinging approvers. 

Pinging @Aneurysm9, @djaglowski, @jpkrohling for review.  Thanks!

File: service/service.go (hunk 1 above)
Comment (djaglowski) [reply service/service.go:139]: Could we get the same result by just calling `New`? Is there a side effect to calling `New` which is being avoided by having a separate function?

Comment (ycombinator) [reply service/service.go]: Thanks for the suggestion, @djaglowski - it totally works! Not sure why I didn't consider that much simpler approach 🤦.  Anyway, implemented in e373dd97f.

File: receiver/receivertest/nop_logs_receiver.go [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+import (
+	"context"
+
+	"go.opentelemetry.io/collector/component"
+	"go.opentelemetry.io/collector/component/componenttest"
+	"go.opentelemetry.io/collector/consumer"
+	"go.opentelemetry.io/collector/receiver"
+)
+
+var nopLogsComponentType = component.MustNewType("nop_logs")
```
[the remark this answers is not in the document]
Comment (ycombinator) [reply receiver/receivertest/nop_logs_receiver.go:15]: Love the functional options pattern here to avoid creating an entirely new receiver!

> It's a bit awkward with because we want to keep the defaults as true, but here's what I came up with to do it:

What if we negated the options so they're `WithoutTraces()`, `WithoutMetrics()`, and `WithoutLogs()`? That would let us preserve the current behavior as the default. Not sure if the `Without*` is more confusing than `With*`, though?

[the remark this answers is not in the document]
Comment (ycombinator) [reply receiver/receivertest/nop_logs_receiver.go]: @djaglowski I implemented your idea, albeit with `Without*` options (see previous comment) in 3fe135652.  I also had to dynamically name the receiver's type based on the options to avoid a collision with the default `nop` type.  Let me know what you think.  Thanks!

[the remark this answers is not in the document]
Comment (djaglowski) [reply receiver/receivertest/nop_logs_receiver.go]: Hmm, having to modify the component type is not ideal. _Maybe_ it's a little nicer if we make the options mutually exclusive e.g. `WithOnly(component.DataType)` because then at last the alternate types can just be `noplogs` / `nopmetrics`, etc.

Either way, this personally still seems better than defining multiple components but it will be up to a maintainer.

[the remark this answers is not in the document]
Comment (ycombinator) [reply receiver/receivertest/nop_logs_receiver.go]: > Hmm, having to modify the component type is not ideal. _Maybe_ it's a little nicer if we make the options mutually exclusive e.g. `WithOnly(component.DataType)` because then at last the alternate types can just be `noplogs` / `nopmetrics`, etc.

With this approach, I think the functional options pattern makes less sense, at least ergonomically, if the caller is required to pass at most one `WithOnly(component.DataType)` option to the factory?

Perhaps it would make sense to leave the `NewNopFactory` implementation as-is, that is, to return a factory that constructs `nop` receivers supporting all data types.  And then introduce something like `NewNopFactoryForType(component.DataType)` that returns a factory that constructs `nop` receivers supporting only the given data type? I implemented this in ce1ad7d5c, if you want to take a look.

> Either way, this personally still seems better than defining multiple components but it will be up to a maintainer.

Agreed.

[the remark this answers is not in the document]
Comment (djaglowski) [reply receiver/receivertest/nop_logs_receiver.go]: > NewNopFactoryForType

This looks better to me. Thanks for iterating on it.

**Comment by ycombinator** [comment]
Hi @djaglowski, @bogdandrutu, @sfc-gh-bdrutu, is there any more work needed on this PR?  Thanks!

**Comment by ycombinator** [comment]
@codeboten @bogdandrutu @dmitryax @mx-psi Would one of you have some time to review this PR and merge it if it's ready, please?  It's been open for nearly three months now.  Thank you!

**Review by mx-psi — APPROVED** [review]
Thanks, merging!
