### PR TITLE
[builder] Add .exe to output binary names when building for Windows

### LINKED ISSUE #12591: [builder] Produces binary name with no `.exe` extension on Windows
### Component(s)

_No response_

### What happened?

**Describe the bug**
If you use the builder to build a Windows binary, that binary will not have a `.exe` extension. That's because the `-o` flag is passed to `go build` as the distribution name only, with no platform consideration.

**Steps to reproduce**
Run the builder on Windows, or with `GOOS=windows`.

**What did you expect to see?**
`<distribution name>.exe`

**What did you see instead?**

`<distribution name>`

### Collector version

v0.121.0

## Environment
OS: Windows
Compiler(if manually compiled): go 1.24.0

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell
2025-03-09T22:12:26.248-0400    INFO    internal/command.go:99  OpenTelemetry Collector Builder  {"version": "(devel)"}
2025-03-09T22:12:26.249-0400    INFO    internal/command.go:104 Using config file{"path": "internal/config/default.yaml"}
2025-03-09T22:12:26.251-0400    INFO    builder/config.go:165   Using go        {"go-executable": "C:\\Users\\Braydon\\sdk\\go1.24.0\\bin\\go.exe"}
2025-03-09T22:12:26.264-0400    INFO    builder/main.go:99      Sources created {"path": "C:\\Users\\Braydon\\AppData\\Local\\Temp\\otelcol-distribution148321280"}
2025-03-09T22:13:05.790-0400    INFO    builder/main.go:201     Getting go modules
2025-03-09T22:13:08.976-0400    INFO    builder/main.go:110     Compiling
2025-03-09T22:13:32.737-0400    INFO    builder/main.go:140     Compiled        {"binary": "C:\\Users\\Braydon\\AppData\\Local\\Temp\\otelcol-distribution148321280/otelcorecol"}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ShaanveerS**
#### Description
This PR fixes builder output naming on Windows by appending .exe to the compiled binary name when ocb runs on Windows.

#### Link to tracking issue
Fixes #12591

#### Testing
Added unit test for Windows/non-Windows output naming

### CODE REVIEW

File: cmd/builder/internal/builder/main.go [hunk 1]
```diff
@@ -146,11 +147,26 @@ func Compile(cfg *Config) error {
...
 		return fmt.Errorf("%w: %s", errCompileFailed, err.Error())
 	}
-	cfg.Logger.Info("Compiled", zap.String("binary", fmt.Sprintf("%s/%s", cfg.Distribution.OutputPath, cfg.Distribution.Name)))
+	cfg.Logger.Info("Compiled", zap.String("binary", fmt.Sprintf("%s/%s", cfg.Distribution.OutputPath, binaryName)))
 
 	return nil
 }
 
+func outputBinaryName(name string) string {
+	goos := os.Getenv("GOOS")
```
Comment (florianl) [inline cmd/builder/internal/builder/main.go]: To avoid issues with being set to an empty value, should we replace os.Getenv with os.LookupEnv?

File: cmd/builder/internal/builder/main.go [hunk 2]
```diff
@@ -146,11 +147,26 @@ func Compile(cfg *Config) error {
...
+	if goos == "" {
+		goos = runtime.GOOS
+	}
+
+	if goos != "windows" {
```
Comment (florianl) [inline cmd/builder/internal/builder/main.go]: To avoid case sensitive issues, should strings.EqualFold used here as well?

File: cmd/builder/internal/builder/main.go (hunk 1 above)
Comment (ShaanveerS) [reply cmd/builder/internal/builder/main.go]: done!

File: cmd/builder/internal/builder/main.go (hunk 2 above)
Comment (ShaanveerS) [reply cmd/builder/internal/builder/main.go]: done, thanks!

File: cmd/builder/internal/builder/main_test.go [hunk 3]
```diff
@@ -148,6 +148,20 @@ func TestGenerateInvalidOutputPath(t *testing.T) {
...
+		assert.Equal(t, "otelcorecol.exe", outputBinaryName("otelcorecol"))
+		assert.Equal(t, "otelcorecol.exe", outputBinaryName("otelcorecol.exe"))
+	})
+
+	t.Run("non-windows target does not add exe", func(t *testing.T) {
+		t.Setenv("GOOS", "linux")
+		assert.Equal(t, "otelcorecol", outputBinaryName("otelcorecol"))
+		assert.Equal(t, "otelcorecol.exe", outputBinaryName("otelcorecol.exe"))
+	})
+}
```
Comment (dmathieu) [inline cmd/builder/internal/builder/main_test.go:174]: We could remove repetition here with slice subtests.


```suggestion
func TestOutputBinaryName(t *testing.T) {
	for _, tt := range []struct {
		name string
		goos string
		wantName string
	}{
		{
			name: "on windows",
			goos: "windows",
			wantName: "otelcorecol.exe",
		},
		{
			name: "on other OSes",
			goos: "linux",
			wantName: "otelcorecol",
		},		
	} {
		t.Run(tt.name, func(t *testing.T) {
			t.Setenv("GOOS", tt.goos)
			assert.Equal(t, tt.wantName, outputBinaryName("otelcorecol"))
			assert.Equal(t, tt.wantName, outputBinaryName("otelcorecol.exe"))
		})
	}
}
```

**Review by pjanotti — APPROVED** [review]

File: cmd/builder/internal/builder/main_test.go (hunk 3 above)
Comment (ShaanveerS) [reply cmd/builder/internal/builder/main_test.go:174]: done!
