### PR TITLE
Fix log adapter in Prometheus receiver

### LINKED ISSUE #1486: Prometheus receiver prints "level" field twice in log messages
**Describe the bug**
All log messages produced by Prometheus code imported by Prometheus receiver print "level" field twice, e.g.:
```
{"level":"info","ts":1596545757.1352987,"caller":"scrape/scrape.go:962","msg":"","level":"debug","scrape_pool":"target2","target":"http://127.0.0.1:38363/target2/metrics","msg":"Scrape failed","err":"server returned HTTP status 404 Not Found"}
 ```

The problem is in the zap -> go-kit log adapter: https://github.com/open-telemetry/opentelemetry-collector/blob/bd921afde8e33d46c6f1586b0182cee1addc391e/receiver/prometheusreceiver/internal/logger.go#L37
- `l.Infow()` produces the first `"level":"info"` field
- the `"level":"debug"` in the example above is produced by go-kit logger (https://github.com/go-kit/kit/blob/556100560949062d23fe05d9fda4ce173c30c59f/log/level/level.go#L178-L188) and passed as part of "keyvals" to the adapter linked above.

**Steps to reproduce**
1. Replace logger with `zap.NewProduction()` in https://github.com/open-telemetry/opentelemetry-collector/blob/bd921afde8e33d46c6f1586b0182cee1addc391e/receiver/prometheusreceiver/metrics_receiver_test.go#L45
2. Run EndToEndTest: https://github.com/open-telemetry/opentelemetry-collector/blob/bd921afde8e33d46c6f1586b0182cee1addc391e/receiver/prometheusreceiver/metrics_receiver_test.go#L928-L929

**What did you expect to see?**
A single "level" field (probably the one produced by Prometheus code / go-kit)
To implement this fix we need to improve the function https://github.com/open-telemetry/opentelemetry-collector/blob/bd921afde8e33d46c6f1586b0182cee1addc391e/receiver/prometheusreceiver/internal/logger.go#L34, which should check if `level` is one of the fields in `keyvals` and respect it for using appropriate zap level, and then drop the go-kit one.

**What did you see instead?**
Two "level" fields in JSON output

### PR DESCRIPTION
**Pull request by nilebox**
**Description:**
Fixing a bug:
- deduplicate the "level" field in log messages coming from Prometheus
- use appropriate zap log level rather than always using `Info`

**Link to tracking Issue:** Fixes #1486

**Testing:** Added unit tests

**Documentation:** -

### CODE REVIEW

File: receiver/prometheusreceiver/internal/logger.go [hunk 1]
```diff
@@ -32,14 +36,89 @@ type zapToGokitLogAdapter struct {
...
+	}
+
+	return zapLevel, output
+}
+
+// check if a given key-value pair represents go-kit log level and return
+// a corresponding zap log level
+func matchLogLevel(key interface{}, val interface{}) (*zapcore.Level, bool) {
+	strKey, ok := key.(string)
+	if !ok || strKey != "level" {
```
Comment (james-bebbington) [inline receiver/prometheusreceiver/internal/logger.go:79]: Move to `const`?

File: receiver/prometheusreceiver/internal/logger.go [hunk 2]
```diff
@@ -32,14 +36,89 @@ type zapToGokitLogAdapter struct {
...
+		logFunc("", keyvals...)
 	} else {
 		// in case something goes wrong
 		w.l.Info(keyvals...)
 	}
 	return nil
 }
 
+// extract go-kit log level from key value pairs, convert it to zap log level
+// and remove from the list to avoid duplication in log message
```
Comment (james-bebbington) [inline receiver/prometheusreceiver/internal/logger.go:56]: Is it idiomatic to start the comment with the function name even for non-exported functions? I've tended to do that anyway, but maybe it's not important

File: receiver/prometheusreceiver/internal/logger.go [hunk 3]
```diff
@@ -32,14 +36,89 @@ type zapToGokitLogAdapter struct {
...
+
+	zapLevel := toZapLevel(levelVal)
+	return &zapLevel, true
+}
+
+// convert go-kit log level to zap
+func toZapLevel(value level.Value) zapcore.Level {
+	// See https://github.com/go-kit/kit/blob/556100560949062d23fe05d9fda4ce173c30c59f/log/level/level.go#L184-L187
+	switch value.String() {
+	case "error":
```
Comment (james-bebbington) [inline receiver/prometheusreceiver/internal/logger.go:96]: Make these all `consts`. Also consider just returning the zap logging functions here (could make this a `type`) so you don't need the `levelToFunc ` function below

File: receiver/prometheusreceiver/internal/logger.go [hunk 4]
```diff
@@ -32,14 +36,89 @@ type zapToGokitLogAdapter struct {
...
+	case zapcore.DebugLevel:
+		return logger.Debugf, nil
+	case zapcore.InfoLevel:
+		return logger.Infof, nil
+	case zapcore.WarnLevel:
+		return logger.Warnf, nil
+	case zapcore.ErrorLevel:
+		return logger.Errorf, nil
+	}
+	return nil, fmt.Errorf("unrecognized level: %q", lvl)
```
Comment (james-bebbington) [inline receiver/prometheusreceiver/internal/logger.go:121]: I think it'd be more consistent with the other code if this just returned `Infof`

File: receiver/prometheusreceiver/internal/logger_test.go [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+			input: []interface{}{
+				"level",
+				"warn", // String is not recognized
+			},
+			wantLevel: zapcore.InfoLevel, // Default
+			wantOutput: []interface{}{
+				"level",
+				"warn", // Field is preserved
+			},
+		},
```
Comment (james-bebbington) [inline receiver/prometheusreceiver/internal/logger_test.go:116]: It would be better to test the `Log` function directly imo. You could [hook](https://github.com/open-telemetry/opentelemetry-collector/blob/8af0a90dcf19c26f3ebdcc97b3616e763b63a9e4/service/logger.go#L65) into zap logs and test what is actually logged. That would also get your coverage up 😄

Comment (bogdandrutu) [reply receiver/prometheusreceiver/internal/logger_test.go:186]: @nilebox maybe consider this in a followup PR

Comment (nilebox) [reply receiver/prometheusreceiver/internal/logger_test.go:186]: I have already added a test with zap hooks actually: https://github.com/open-telemetry/opentelemetry-collector/blob/8b55cb68fde852297e8572fcf344032377abb708/receiver/prometheusreceiver/internal/logger_test.go#L78

I kept the original tests as well, because zap hook entries don't have custom fields so I can't assert them there unfortunately.
