### PR TITLE
[confmap] Do not leak expanded values on Sub

### LINKED ISSUE #11154: Unable to use file directives to include the contents of individual processors v0.109.0
**Describe the bug**

In versions prior to 0.109.0 we were able to include the contents of a processor definition using a file directive, e.g.:

```yaml
transform/redaction-rules: ${file:redaction-rules.yaml}
```

However, when attempting to validate the configuration v0.109.0, it fails with the following error:

```yaml
error decoding 'processors': error reading configuration for "transform/redaction-rules:": unexpected sub-config value kind for key:transform/redaction-rules value:{map[error_mode:ignore....] error_mode: ignore
} kind:struct
```

**Steps to reproduce**

**What did you expect to see?**

I expect the behavior to remain the same, for the validation to succeed, and the collector to start up. 

**What did you see instead?**

The collector and/or validation commands fail with an error `error decoding 'processors': error reading configuration for "transform/redaction-rules:"`

**What version did you use?**

v0.109.0

**What config did you use?**

```yaml
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
        - transform/redaction-rules
      exporters:
        - logging
        
# The pipeline details
receivers:
  otlp:
      http:

processors:
  transform/redaction-rules:
    ${file:redaction-rules.yaml}

  batch: {}

exporters:
  logging:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1

```

```yaml
 # transform/redaction-rules
 ---
error_mode: ignore
trace_statements:
- context: span
  statements:
    - |-
      set(attributes["http.target"],
      SHA256(attributes["http.target"]))
      where attributes["http.target"] != nil
    - |-
      set(attributes["http.url"],
      SHA256(attributes["http.url"]))
      where attributes["http.url"] != nil
    - |-
      set(attributes["url.full"],
      SHA256(attributes["url.full"]))
      where attributes["url.full"] != nil
```

**Environment**

**Additional context**

### PR DESCRIPTION
**Pull request by mx-psi**
#### Description

Fixes `Sub` method to drop string representation if the requested sub-conf has it.

#### Link to tracking issue
Fixes #11154

#### Testing

Added unit tests.

### CODE REVIEW

File: confmap/confmap_test.go [hunk 1]
```diff
@@ -876,6 +876,28 @@ func TestExpandedValue(t *testing.T) {
...
+	assert.Equal(t, map[string]any{"subkey": map[string]any{"subsubkey": "value"}}, cm.Get("key"))
+	assert.Equal(t, map[string]any{"key": map[string]any{"subkey": map[string]any{"subsubkey": "value"}}}, cm.ToStringMap())
+	assert.Equal(t, map[string]any{"subsubkey": "value"}, cm.Get("key::subkey"))
+
+	sub, err := cm.Sub("key::subkey")
+	assert.NoError(t, err)
+	assert.Equal(t, map[string]any{"subsubkey": "value"}, sub.ToStringMap())
+
+	// This should return value, but currently `Get` does not support keys within expanded values.
+	assert.Equal(t, nil, cm.Get("key::subkey::subsubkey"))
```
Comment (mx-psi) [inline confmap/confmap_test.go:898]:
```suggestion
	assert.Nil(t, cm.Get("key::subkey::subsubkey"))
```

**Review by bogdandrutu — APPROVED** [review]

**Review by songy23 — APPROVED** [review]
