### PR TITLE
Print generated resource attributes for internal logs

### LINKED ISSUE #13110: Generated resource attributes are missing from internal printed logs
### Component(s)

service

### What happened?

**Describe the bug**
After the implementation to #12582, the attributes under `.service.telemetry.resource` are added to the console logger. But some other attributes that are generated, will not be printed (but they will be sent via OTLP).

This ticket is to also add them to the printed resource attributes.

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iblancasa**
#### Link to tracking issue
Fixes #13110

#### Testing
- Improved the unit tests.

### CODE REVIEW

**Review by jade-guiton-dd — CHANGES_REQUESTED** [review]
Thanks for the PR! I think there is a slight problem with your current solution.

File: service/telemetry/logger.go [hunk 1]
```diff
@@ -43,17 +43,18 @@ func newLogger(set Settings, cfg Config) (*zap.Logger, log.LoggerProvider, error
 	// To make sure they are also exposed in logs written to stdout, we add them as fields to the Zap core created above using WrapCore.
 	// We do NOT add them to the logger using With, because that would apply to all logs, even ones exported through the core that wraps
 	// the LoggerProvider, meaning that the attributes would be exported twice.
-	logger = logger.WithOptions(zap.WrapCore(func(c zapcore.Core) zapcore.Core {
-		var fields []zap.Field
-		for k, v := range cfg.Resource {
-			if v != nil {
-				f := zap.Stringp(k, v)
-				fields = append(fields, f)
+	// Note that we also add the resource attributes generated in service.go.
```
Comment (jade-guiton-dd) [inline service/telemetry/logger.go]: Instead of this new line, could you update the comment above (which still mentions `cfg.Resource` even though it's no longer used) to something like `The attributes in set.Resource.Attributes(), which are generated in service.go, [...]`?

File: service/telemetry/logger.go [hunk 2]
```diff
@@ -43,17 +43,18 @@ func newLogger(set Settings, cfg Config) (*zap.Logger, log.LoggerProvider, error
...
+	if set.Resource != nil {
+		logger = logger.WithOptions(zap.WrapCore(func(c zapcore.Core) zapcore.Core {
+			var fields []zap.Field
+			for _, attr := range set.Resource.Attributes() {
+				fields = append(fields, zap.String(string(attr.Key), attr.Value.AsString()))
```
Comment (jade-guiton-dd) [inline service/telemetry/logger.go]: In the "canonical" Collector it won't matter since the resource attributes are only ever strings, but for the sake of trying to keep the interface reusable, I think it would be better to use `Value.Emit()` instead of `Value.AsString()`. This will convert the attribute to a string representation if it isn't already one instead of returning an empty string.
```suggestion
				fields = append(fields, zap.String(string(attr.Key), attr.Value.Emit()))
```

File: service/telemetry/logger_test.go [hunk 3]
```diff
@@ -126,38 +128,115 @@ func TestNewLogger(t *testing.T) {
...
 
-	mylogger, _, _ := newLogger(set, cfg)
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			observerCore, observedLogs := observer.New(zap.InfoLevel)
 
-	mylogger.Info("Test log message")
-	require.Len(t, observedLogs.All(), 1)
+			set := Settings{
+				BuildInfo: tt.buildInfo,
```
Comment (jade-guiton-dd) [inline service/telemetry/logger_test.go]: Nit: You can probably remove this since the code no longer uses it.

**Review by jade-guiton-dd — APPROVED** [review]
Looks good, just a few nitpicks.

File: service/telemetry/logger.go (hunk 2 above)
Comment (iblancasa) [reply service/telemetry/logger.go]: Didn't know about this. Thanks!

**Comment by iblancasa** [comment]
@open-telemetry/collector-maintainers can we merge this? Thank you!

File: service/telemetry/logger.go [hunk 4]
```diff
@@ -39,21 +39,24 @@ func newLogger(set Settings, cfg Config) (*zap.Logger, log.LoggerProvider, error
...
-				f := zap.Stringp(k, v)
-				fields = append(fields, f)
+	// The attributes in set.Resource.Attributes(), which are generated in service.go, are added
+	// as resource attributes for logs exported through the LoggerProvider instantiated below.
+	// To make sure they are also exposed in logs written to stdout, we add them as fields to the
+	// Zap core created above using WrapCore.
+	// We do NOT add them to the logger using With, because that would apply to all logs, even ones
+	// exported through the core that wraps the LoggerProvider, meaning that the attributes would
+	// be exported twice.
+	if set.Resource != nil {
```
Comment (bogdandrutu) [inline service/telemetry/logger.go]: And `len(set.Resource.Attributes()) > 0`?

Comment (iblancasa) [reply service/telemetry/logger.go]: I can add it but it will have no effect beccause there are some attributes that will be generated if not present... so the `len` will never be 0.

**Comment by iblancasa** [comment]
@open-telemetry/collector-maintainers can we merge this? Thanks!

File: service/telemetry/logger.go (hunk 4 above)
Comment (bogdandrutu) [reply service/telemetry/logger.go]: There is no guarantee about "there are some attributes that will be generated if not present". Is there a contract about that since Resource is public?

Comment (jade-guiton-dd) [reply service/telemetry/logger.go]: You _could_ instantiate your own service with no attributes in the resource, yes. But it wouldn't break anything, it would just output an empty `resource` field. Do you think that could be a problem?

Comment (bogdandrutu) [reply service/telemetry/logger.go]: My point is that it does unnecessary work to wrap the core when not needed.

Comment (iblancasa) [reply service/telemetry/logger.go]: Don't worry. Just added the change.
