### PR TITLE
fix(cli): components subcommand should return providers and converters in sorted order

### LINKED ISSUE #14476: [cmd/components] : provider schemes in `otelcol components` are not printed in stable order
### Component(s)

_No response_

### What happened?

**Describe the bug**

When running the OpenTelemetry collector sub-command components:
```
otelcol components > components.yaml
```
provider schemes are not output in stable order, e.g.
```yaml
#...
providers:
    - scheme: yaml
      module: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.50.0
    - scheme: env
      module: go.opentelemetry.io/collector/confmap/provider/envprovider v1.50.0
    - scheme: file
      module: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.50.0
    - scheme: http
      module: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.50.0
    - scheme: https
      module: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.50.0
```
or 
```yaml
#...
providers:
    - scheme: env
      module: go.opentelemetry.io/collector/confmap/provider/envprovider v1.50.0
    - scheme: file
      module: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.50.0
    - scheme: http
      module: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.50.0
    - scheme: https
      module: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.50.0
    - scheme: yaml
      module: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.50.0
```

**Steps to reproduce**

Download OpenTelemetryCollector default distribution, run components sub-command.
Provider schemes in the output will not be consistently printed in stable order.

**What did you expect to see?**

The component factories are printed in sorted order, the motivation is likely two-fold, for ease of reading for operators and for any downstream consumers of the components sub-command would want to rely on stable output here, e.g. potentially OpAmp

**What did you see instead?**

Provider schemes in the output were not printed in stable order,  would get randomly ordered provider schemes

### Collector version

v0.144.0

## Environment
N/A

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell
N/A
```

### Additional context

N/A

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by alexandreLamarre**
#### Description

`otel components` does not print provider schemes and converter modules in a stable order in it's output

#### Link to tracking issue
Fixes #14476

#### Testing

Running the subcommand from the built distribution.

~I opted not to add additional tests to command_components_test.go, since stability order for other components was not being unit-tested either. Open to adding tests for these cases, let me know!~

added unit tests for the new providers / converters stable output & added tests for the existing behaviour for components (receivers,processors,exporters,connectors,extensions) that are already output in stable order

#### Documentation

N/A

### CODE REVIEW

**Comment by dmathieu** [comment]
Shouldn't we do this for every component? (and yes, we need tests).

**Comment by alexandreLamarre** [comment]
The other components are already sorted by the sortFactories helper, but I can add tests for the existing behaviour

**Comment by dmathieu** [comment]
Ah, you're right. Yes, adding tests to prevent regressions is always better.
If you feel like it, you can also add tests for sortFactories, in another PR.

**Comment by alexandreLamarre** [comment]
converter modules were also not sorted, I can add that as well, but I was unsure if those were supported anywhere - I'm not familiar with converters. I can also add those for completeness
```go
type CollectorSettings struct {
    // ...

	// ConverterModules maps converter names to their respective go modules.
	ConverterModules []string
```

**Comment by evan-bradley** [comment]
>converter modules were also not sorted, I can add that as well, but I was unsure if those were supported anywhere - I'm not familiar with converters. I can also add those for completeness

Providers and Converters are usually referenced hand-in-hand in the Collector, so I think it would make sense to add them as well. It can be in this PR or another one, either way is okay.

File: otelcol/command_components.go [hunk 1]
```diff
@@ -160,3 +152,31 @@ func sortFactoriesByType[T component.Factory](factories map[component.Type]T) []
...
+			Module: providers[providerScheme],
+		})
+	}
+	return providerComponents
+}
+
+func sortConverterModules(modules []string) []componentWithoutStability {
+	sortedModulesCopy := make([]string, len(modules))
+	copy(sortedModulesCopy, modules)
+	sort.Strings(sortedModulesCopy)
```
Comment (alexandreLamarre) [inline otelcol/command_components.go:187]: In practice, a collector could have the same module string and different versions. 

Is it worth handling the case where we want to sort by (module, version), and use something like semver sorting for versions? 

WDYT?

File: otelcol/command_components_test.go [hunk 2]
```diff
@@ -43,3 +43,37 @@ func TestNewBuildSubCommand(t *testing.T) {
 	// line that makes the test fail.
 	assert.Equal(t, strings.ReplaceAll(strings.ReplaceAll(string(ExpectedOutput), "\n", ""), "\r", ""), strings.ReplaceAll(strings.ReplaceAll(b.String(), "\n", ""), "\r", ""))
 }
+
+func TestComponentsStableOutput(t *testing.T) {
+	set := CollectorSettings{
+		BuildInfo:              component.NewDefaultBuildInfo(),
+		Factories:              nopFactories,
```
Comment (alexandreLamarre) [inline otelcol/command_components_test.go]: Can follow up in a separate PR later today for factories sorting, a little more involved that the providers & converters

File: otelcol/command_components.go (hunk 1 above)
Comment (evan-bradley) [reply otelcol/command_components.go:187]: >In practice, a collector could have the same module string and different versions.

I don't think this is possible due to the way Go handles dependencies, could you detail the situation you see happening here?

Normally importing the same module at two different versions requires a workaround that involves changing the module name as well.

Comment (alexandreLamarre) [reply otelcol/command_components.go:187]: Ah yeah you're right, got a little mixed up

**Comment by dmathieu** [comment]
You need to run `make gotidy`.

**Comment by alexandreLamarre** [comment]
Yep I saw the CI failures the other day and unfortunately got caught up in something else before being able to take a look. Apologies for the delay

File: .chloggen/fix-otelcol-components-output.yaml [hunk 3]
```diff
@@ -0,0 +1,25 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. receiver/otlp)
+component: pkg/otelcol
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: "Fixed an issue where the otelcol components subcommand output 'providers' and 'converters' sections were not printed in stable order"
```
Comment (dmathieu) [inline .chloggen/fix-otelcol-components-output.yaml]:
```suggestion
note: Order providers and converters in alphabetical order in the `components` subcommand.
```

File: otelcol/command_components.go [hunk 4]
```diff
@@ -164,6 +159,49 @@ func sortFactoriesByType[T component.Factory](factories map[component.Type]T) []
 	return sortedFactories
 }
 
+func isProviderAlias[T confmap.ProviderFactory](f T) bool {
```
Comment (dmathieu) [inline otelcol/command_components.go]: I don't think we need a new method here. We could add `confmap.ProviderFactory` to the allows generic types in `isComponentAlias`.

```golang
func isComponentAlias[T component.Factory|confmap.ProviderFactory](component T) bool {
```

Comment (alexandreLamarre) [reply otelcol/command_components.go]: Unfortunately go still doesn't support unions over interfaces with methods, so opted to consolidate to one helper with `any`

File: otelcol/command_components.go [hunk 5]
```diff
@@ -164,7 +159,43 @@ func sortFactoriesByType[T component.Factory](factories map[component.Type]T) []
...
+			Module: mod,
+		})
+	}
+	return sortedModules
+}
+
+func isComponentAlias[T any](component T) bool {
 	if al, ok := any(component).(componentalias.TypeAliasHolder); ok {
 		return al.DeprecatedAlias().String() != ""
 	}
```
Comment (evan-bradley) [inline otelcol/command_components.go]: Would it be easier to just make the `component` parameter's type `any` so we don't have to do the casting on the first line of the function?

File: otelcol/command_components_test.go [hunk 6]
```diff
@@ -45,6 +57,185 @@ func TestNewBuildSubCommand(t *testing.T) {
...
+
+	// ensure output is reasonably consistent
+	for range 5 {
+		b := bytes.NewBufferString("")
+		cmd.SetOut(b)
+		err = cmd.Execute()
+		require.NoError(t, err)
+		// Trim new line at the end of the two strings to make a better comparison as string() adds an extra new
+		// line that makes the test fail.
+		assert.Equal(t, strings.ReplaceAll(strings.ReplaceAll(string(ExpectedOutput), "\n", ""), "\r", ""), strings.ReplaceAll(strings.ReplaceAll(b.String(), "\n", ""), "\r", ""))
```
Comment (evan-bradley) [inline otelcol/command_components_test.go]: Could we use [strings.Trim](https://pkg.go.dev/strings#Trim) to trim the excess newlines?

File: otelcol/command_components.go (hunk 5 above)
Comment (alexandreLamarre) [reply otelcol/command_components.go]: oh right, yeah that was silly of me

Comment (evan-bradley) [reply otelcol/command_components.go]: No worries, we've all been there. :slightly_smiling_face:

**Comment by alexandreLamarre** [comment]
Thanks @dmathieu @evan-bradley for the guidance and quick feedback on this one
