### PR TITLE
[exporterhelper] make enqueue failures available

### LINKED ISSUE #8673: enqueue_failed counters not available in otel metrics
**Describe the bug**
The following metrics are not available via opentelemetry metrics:

```
otelcol_exporter_enqueue_failed_log_records_total{exporter="otlp"} 0
otelcol_exporter_enqueue_failed_metric_points_total{exporter="otlp"} 0
otelcol_exporter_enqueue_failed_spans_total{exporter="otlp"} 0
```

This is because they're registered with a separate registry than the one used by the otel OC bridge.

**Steps to reproduce**
Enabled the following feature gates:
```
--feature-gates=telemetry.useOtelForInternalMetrics
--feature-gates=telemetry.useOtelWithSDKConfigurationForInternalTelemetry
```

**What did you expect to see?**
Expected to see those metrics emitted via OTLP

**What did you see instead?**
Those metrics did not appear

**What version did you use?**
v0.87.0

### PR DESCRIPTION
**Pull request by codeboten**
These metrics were only exporter either via OC or via the prometheus exporter. Fixes #8673

### CODE REVIEW

**Review by jmacd — COMMENTED** [review]
🥇 💯 🚀 👍

File: exporter/exporterhelper/obsexporter.go [hunk 1]
```diff
@@ -252,3 +273,43 @@ func toNumItems(numExportedItems int, err error) (int64, int64) {
...
+	}
+	if failed > 0 {
+		_ = stats.RecordWithTags(
+			ctx,
+			or.mutators,
+			failedMeasure.M(failed))
+	}
+}
+
+func (or *ObsReport) recordEnqueueFailureWithOtel(ctx context.Context, dataType component.DataType, failed int64) {
```
Comment (moh-osman3) [inline exporter/exporterhelper/obsexporter.go:303]: I'm wondering if this new otel metric can be updated externally through the API? This package allows an external package to call `exporterhelper.ObsReport.StartTracesOp`  and `exporterhelper.ObsReport.EndTracesOp`. And `EndTracesOp` will call `recordMetrics` which will record `sent` and `failedToSend` - i.e. can the API also update `failedToEnqueue`?

**Review by moh-osman3 — COMMENTED** [review]
Thanks for making this change!

File: exporter/exporterhelper/obsexporter.go (hunk 1 above)
Comment (jmacd) [reply exporter/exporterhelper/obsexporter.go:303]: IMO StartTracesOp and EndTracesOp should be able to catch the error from the queue sender, but the individual sub-components are not connected in the right order for this. I do not want to replicate existing functionality, for the record, @moh-osman3, I think we should focus on a new spec: https://github.com/open-telemetry/semantic-conventions/pull/184

Comment (codeboten) [reply exporter/exporterhelper/obsexporter.go:303]: > will call recordMetrics which will record sent and failedToSend - i.e. can the API also update failedToEnqueue?

I originally considered going the route of recordMetrics updating all 3 metrics, but sent/failedToSend are just opposites of each other, which makes it easy to record together. I suppose recording enqueue failed could be done by checking the error type in `End*Op`. Whether we decide to do this or not (based on @jmacd's comment) I would do this as a follow up PR, as that's a change in behaviour. This PR is really just about ensuring that the metric is emitted in both the OC and the Otel case :)

Would be happy to open an issue to follow up @moh-osman3

Comment (moh-osman3) [reply exporter/exporterhelper/obsexporter.go:303]: That makes sense thanks @codeboten @jmacd! I was mainly asking because I was writing some code in the otel-arrow repository and realized I wouldn't have access to that metric if I tried to access obsreport externally. But as Josh pointed out we might just do a simpler instrumentation from scratch instead of depending on that obsreport package

File: obsreport/obsreporttest/otelprometheuschecker.go [hunk 2]
```diff
@@ -77,20 +77,32 @@ func (pc *prometheusChecker) checkExporterLogs(exporter component.ID, sent, send
...
-func (pc *prometheusChecker) checkExporterMetrics(exporter component.ID, sentMetricPoints, sendFailedMetricPoints int64) error {
-	return pc.checkExporter(exporter, "metric_points", sentMetricPoints, sendFailedMetricPoints)
+func (pc *prometheusChecker) checkExporterMetrics(exporter component.ID, sent, sendFailed int64) error {
+	return pc.checkExporter(exporter, "metric_points", sent, sendFailed)
 }
 
 func (pc *prometheusChecker) checkExporter(exporter component.ID, datatype string, sent, sendFailed int64) error {
 	exporterAttrs := attributesForExporterMetrics(exporter)
-	errs := pc.checkCounter(fmt.Sprintf("exporter_sent_%s", datatype), sent, exporterAttrs)
+	var errs error
```
Comment (codeboten) [inline obsreport/obsreporttest/otelprometheuschecker.go:86]:
```suggestion
	errs := pc.checkCounter(fmt.Sprintf("exporter_sent_%s", datatype), sent, exporterAttrs)
```

File: obsreport/obsreporttest/otelprometheuschecker.go [hunk 3]
```diff
@@ -77,20 +77,32 @@ func (pc *prometheusChecker) checkExporterLogs(exporter component.ID, sent, send
...
+
+	errs = multierr.Append(errs,
+		pc.checkCounter(fmt.Sprintf("exporter_sent_%s", datatype), sent, exporterAttrs))
+
```
Comment (codeboten) [inline obsreport/obsreporttest/otelprometheuschecker.go:90]:
```suggestion
	errs := pc.checkCounter(fmt.Sprintf("exporter_sent_%s", datatype), sent, exporterAttrs)
```

File: obsreport/obsreporttest/otelprometheuschecker.go [hunk 4]
```diff
@@ -77,20 +77,34 @@ func (pc *prometheusChecker) checkExporterLogs(exporter component.ID, sent, send
...
```
[the remark this answers is not in the document]
Comment (codeboten) [reply obsreport/obsreporttest/otelprometheuschecker.go]: I've reverted this change

**Review by dmitryax — APPROVED** [review]
