### PR TITLE
Fix ExpandedValue behavior for *string fields

### LINKED ISSUE #14034: Resource attributes for internal telemetry unable to parse numeric strings
### Component(s)

confmap

### What happened?

**Describe the bug**
When a yaml key is supplied dynamically via environment variables, if an environment variable is numeric, e.g. `123`, or `1234567890`, it will be treated as an integer, and fails to validate to a string [here](https://github.com/open-telemetry/opentelemetry-collector/blob/c854264a0df84e4abc8064f1c686fe55d2327b90/service/telemetry/otelconftelemetry/config.go#L23).

**Steps to reproduce**
Use the otel config below

**What did you expect to see?**
OTEL is able to boot

**What did you see instead?**
Please see log output section

### Collector version

0.135.0

## Environment
AWS ECS, but can be reproduciblbe in any environment, with any numeric string, despite being wrapped in quotes/double quotes.

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"
processors: {}
exporters:
  debug:
    verbosity: "detailed"
service:
  pipelines:
    logs:
      receivers:
        - otlp
      exporters:
        - debug
  telemetry:
    resource:
      service.name: otel-gateway
      service.version: 'v0.0.0'
      deployment.environment.name: 'test'
      aws.ecs.cluster.arn: '${env:AWS_ECS_CLUSTER_ARN}'
      aws.ecs.launchtype: '${env:AWS_ECS_LAUNCHTYPE}'
      aws.ecs.task.arn: '${env:AWS_ECS_TASK_ARN}'
      aws.ecs.task.family: '${env:AWS_ECS_TASK_FAMILY}'
      aws.ecs.task.id: '${env:AWS_ECS_TASK_ID}'
      aws.ecs.task.revision: '${env:AWS_ECS_TASK_REVISION}'
      cloud.account.id: '${env:CLOUD_ACCOUNT_ID}'
      cloud.availability_zone: '${env:CLOUD_AVAILABILITY_ZONE}'
      cloud.platform: '${env:CLOUD_PLATFORM}'
      cloud.provider: '${env:CLOUD_PROVIDER}'
      cloud.region: '${env:CLOUD_REGION}'
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: 'https://otel.somedomain:4318'
                timeout: 30000
    logs:
      level: INFO
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: 'https://otel.somedomain:4318'
                timeout: 30000
    traces:
      propagators:
        - tracecontext
        - b3
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: 'https://otel.somedomain:4318'
                timeout: 30000
```

### Log output

```shell
2025/10/15 12:30:58 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
'service.telemetry.resource[cloud.account.id]' expected type 'string', got unconvertible type 'int'
'service.telemetry.resource[aws.ecs.task.revision]' expected type 'string', got unconvertible type 'int'
```

### Additional context

`CLOUD_ACCOUNT_ID` is in AWS account ID format e.g. `123456789012`
`AWS_ECS_TASK_REVISION` is a numeric string, e.g. `123`, `234`, ...

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by jade-guiton-dd**
#### Description

The `useExpandValue` hook in `confmap` makes sure that we can parse externally-loaded values such as environment values as YAML when needed, but that they can remain interpreted as strings when assigned to `string` fields. However, until this PR, this did not extend to `*string` fields, like [the ones in the `service::telemetry::resource` map](https://github.com/open-telemetry/opentelemetry-collector/blob/587b90b9ecc1db959ee9104d5bf993591f80ca43/service/telemetry/otelconftelemetry/config.go#L23), causing `expected type 'string', got unconvertible type` errors when assigning environment variables that can be parsed as a non-string YAML type to resource attributes.

I believe this PR will not change behavior outside of resolving that error. In principle, there could be a change if `ExpandedValue.Value` has a type compatible with a `*string` field, but with a different value from `ExpandedValue.Original`. I thought this could perhaps happen if an environment variable contains a quoted string (the YAML parsed value would be a `string` with the quotes removed), but it looks like [we explicitly refuse to parse YAML strings](https://github.com/open-telemetry/opentelemetry-collector/blob/587b90b9ecc1db959ee9104d5bf993591f80ca43/confmap/provider.go#L170-L173) ([tested for here](https://github.com/open-telemetry/opentelemetry-collector/blob/587b90b9ecc1db959ee9104d5bf993591f80ca43/confmap/provider_test.go#L173-L177)).

#### Link to tracking issue
Fixes #14034

#### Testing

I added a test case in the existing tests for `useExpandValue` to match the `map[string]*string` use case. I also manually tested that there is no longer a crash in the specific case of a `service::telemetry::resource` attribute set to an integer-like environment variable, and that the behavior for quoted environment variables did not change.

### CODE REVIEW

File: confmap/internal/confmap_test.go [hunk 1]
```diff
@@ -1031,6 +1031,12 @@ func TestExpandedValue(t *testing.T) {
 	require.NoError(t, cm.Unmarshal(&cfgStr))
 	assert.Equal(t, "original", cfgStr.Key)
 
+	cfgMapStrPtr := map[string]*string{}
```
Comment (mx-psi) [inline confmap/internal/confmap_test.go:1053]: Could we do a test where we have a struct with a field of type `*string` so that it is the same as the others?

Comment (jade-guiton-dd) [reply confmap/internal/confmap_test.go:1053]: Ok, I'll add both

**Review by mx-psi — APPROVED** [review]

**Comment by jade-guiton-dd** [comment]
Looks like I did find some changes in behavior for this PR. On main, setting `service::telemetry::resource::test_attr: ${env:TEST_ATTR}` with `TEST_ATTR=null` disables that resource attribute entirely, like setting it to `null` directly, whereas it now sets the attribute to the string `"null"`. Similarly, setting the environment variable to an empty string or not setting it at all used to similarly parse to `null` and disable the attribute, but it now sets it to the empty string.

The "correct" behavior is not entirely clear, but I think I'll add an exception for these special cases. Let's hope nobody wants to set their config fields to these special string values...

**Comment by jade-guiton-dd** [comment]
I pushed a new version which:
1. uses the unparsed string for `**string` fields (and `***string` and beyond), in case someone wants to use those for some reason;
2. uses the parsed string for values parsed to `null` assigned to a pointer.

The latter is the existing behavior. This means any of these in an environment variable will NOT be resolved as a string if assigned to a `*string` field and will instead set the field to `nil`:
- the empty string, including from an undefined environment variable;
- `null`, `NULL`, `Null`, `~`;
- any of the above prefixed with `!!null`;
- probably other weird things from the YAML spec.

As long as [that weird quirk of the `NewRetrievedFromYAML` function](https://github.com/open-telemetry/opentelemetry-collector/blob/587b90b9ecc1db959ee9104d5bf993591f80ca43/confmap/provider.go#L170-L173) remains there, I don't think there is any way to input those strings into a resource attribute via an environment variable.

File: confmap/internal/decoder.go [hunk 2]
```diff
@@ -95,8 +95,23 @@ func useExpandValue() mapstructure.DecodeHookFuncType {
...
+			for baseType.Kind() == reflect.Pointer {
+				baseType = baseType.Elem()
+				pointed = true
+			}
+			useOriginal := baseType.Kind() == reflect.String
+
+			// `exp.Value` should take priority if it can be mapped and has a different value.
+			// If `exp.Value` is a string, `NewRetrievedFromYAML` guarantees they have the same value,
+			// but this leaves the case of a `null` value.
+			if useOriginal && pointed && exp.Value == nil {
```
Comment (mx-psi) [inline confmap/internal/decoder.go]: We could simplify to
```suggestion
			if pointed && exp.Value == nil {
```

Comment (jade-guiton-dd) [reply confmap/internal/decoder.go]: No, `pointed` can be true without `useOriginal` if the type is something like `*int`.

Comment (jade-guiton-dd) [reply confmap/internal/decoder.go]: Oh but I guess your point is that setting `useOriginal` to `false` if it's already `false` is a no-op. Ok that's fine

**Comment by jade-guiton-dd** [comment]
Do you think it would make sense to gate this change behind `NewExpandedValueSanitizer`, like the changes further down in the function? So it could be disabled easily in case it causes issues

**Comment by mx-psi** [comment]
It would help with reducing potential unwanted side effects from this

File: confmap/internal/decoder.go [hunk 3]
```diff
@@ -95,7 +95,29 @@ func useExpandValue() mapstructure.DecodeHookFuncType {
 		data any,
 	) (any, error) {
 		if exp, ok := data.(ExpandedValue); ok {
-			v := castTo(exp, to.Kind() == reflect.String)
+			var useOriginal bool
+			if NewExpandedValueSanitizer.IsEnabled() {
+				// Based on mapstructure's behavior, we can map `exp.Original` to `to` if it is a `string`,
+				// or potentially a pointer (to a pointer...) to a `string``.
```
Comment (evan-bradley) [inline confmap/internal/decoder.go]:
```suggestion
				// or potentially a pointer (to a pointer...) to a `string`.
```
Nit

File: confmap/internal/decoder.go [hunk 4]
```diff
@@ -95,7 +95,29 @@ func useExpandValue() mapstructure.DecodeHookFuncType {
...
+				pointed := false
+				for baseType.Kind() == reflect.Pointer {
+					baseType = baseType.Elem()
+					pointed = true
+				}
+				useOriginal = baseType.Kind() == reflect.String
+
+				// `exp.Value` should take priority if it can be mapped and has a different value.
+				// If `exp.Value` is a string, `NewRetrievedFromYAML` guarantees they have the same value,
+				// but this leaves the case of a `null` value.
```
Comment (evan-bradley) [inline confmap/internal/decoder.go]:
```suggestion
				// The original value may be a string representation of `nil`, such as
				// `null`, `NULL`, `Null`, or `~` for YAML. For pointer-to-string values,
				// we need to sure we properly parse this as a Go `nil value and not
				// use the original string.
```
Feel free to discard this, or work it in with the existing comment. It took me a few tries to parse the comment as-is to fully understand why we're doing what we're doing here.

I think "`exp.Value` should take priority if it can be mapped and has a different value" should be included in the Godoc on this function to describe the overall approach when `NewExpandedValueSanitizer` is enabled.

Comment (jade-guiton-dd) [reply confmap/internal/decoder.go]: I tried clarifying the comments and moving most of them to the Godoc for `useExpandValue`, tell me if you think it's better.

**Review by evan-bradley — APPROVED** [review]

File: confmap/internal/decoder.go (hunk 4 above)
Comment (evan-bradley) [reply confmap/internal/decoder.go]: Unfortunately now I'm tainted with presently understanding the context of this function, but I think this should be better.

**Comment by jade-guiton-dd** [comment]
Yes, it should be ready to merge, we just need a maintainer to do it.
