### PR TITLE
[exporter/logging] Add `syscall.EBADF` to list of known sync errors

### LINKED ISSUE #4153: loggingexporter: Error: failed to shutdown service: failed to shutdown pipelines: failed to shutdown exporters: sync /dev/stderr: bad file descriptor
**Describe the bug**

When trying to run collector using the following piece of code:

```go
import (
	"net"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/service"
)

func TestConfig(t *testing.T) {
	// components() generated with opentelemetry builder
	factories, err := components()
	require.NoError(t, err)

	t.Log("Creating new app...")
	app, err := service.New(service.CollectorSettings{
		BuildInfo: component.DefaultBuildInfo(),
		Factories: factories,
	})
	require.NoError(t, err)

	app.Command().Root().SetArgs(
		[]string{
			"--config=testdata/filelog.yaml",
			"--metrics-addr=" + GetAvailableLocalAddress(t),
			"--log-level=debug",
		},
	)

	go func() {
		<-time.NewTimer(3 * time.Second).C
		t.Log("Calling .Shutdown() on the app...")
		app.Shutdown()
	}()

	t.Log("Calling .Run() on the app...")
	require.NoError(t, app.Run())
}
```

one can observe the following error:

```
2021-09-30T17:11:41.596+0200    info    service/service.go:152  Stopping extensions...
2021-09-30T17:11:41.596+0200    info    service/collector.go:353        Shutdown complete.
Error: failed to shutdown service: failed to shutdown pipelines: failed to shutdown exporters: sync /dev/stderr: bad file descriptor
```

**Steps to reproduce**

Use the above piece of code

**What did you expect to see?**

No error.

**What did you see instead?**

bad file descriptor error

**What version did you use?**
Version: 2116719e97eb232a692364b51454620712823a89 vel `v0.35.0`

**What config did you use?**

The test load the following config:

```yaml
receivers:
  filelog:
    include: [ "*_dummy.log" ]
    start_at: end

processors:
  attributes/123:
    actions:
      - action: insert
        key: host
        value: 123

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers:
      - filelog
      processors:
      - attributes/123
      exporters:
      - logging
```

**Environment**
OS: mac
Compiler(if manually compiled): "go 1.17.1"

**Additional context**

When debugging the above mentioned piece of code with e.g. delve I do not get the error because the underlying error is 
`unix.ENOTTY` which is in the set of [known sync errors](https://github.com/open-telemetry/opentelemetry-collector/blob/2116719e97eb232a692364b51454620712823a89/exporter/loggingexporter/known_sync_error.go#L35)
```
(dlv) n
> go.opentelemetry.io/collector/exporter/loggingexporter.loggerSync.func1() /Users/pmalek/.gvm/pkgsets/go1.17.1/global/pkg/mod/go.opentelemetry.io/collector@v0.35.0/exporter/loggingexporter/logging_exporter.go:154 (PC: 0x49f37d1)
   149:              // Since these are not actionable ignore them.
   150:              err := logger.Sync()
   151:              if osErr, ok := err.(*os.PathError); ok {
   152:                      wrappedErr := osErr.Unwrap()
   153:                      if knownSyncError(wrappedErr) {
=> 154:                              err = nil
   155:                      }
   156:              }
   157:              return err
   158:      }
   159: }
(dlv) p osErr
*io/fs.PathError {
        Op: "sync",
        Path: "/dev/stderr",
        Err: error(syscall.Errno) golang.org/x/sys/unix.ENOTTY (25),}
```

My proposal for this issue is to add `syscall.EBADF` to `knownSyncError()` (unless there's someone to point out a better way to approach this).

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** Adds `syscall.EBADF` ('bad file descriptor') to the list of known sync errors.

**Link to tracking Issue:** Fixes #4153

**Testing:** I tested that this fixes the test skipped in DataDog/datadog-agent#12502

### CODE REVIEW

**Comment by mx-psi** [comment]
> Is there a performance impact to run through a loop versus the hard-coded OR statement?

@TylerHelmuth AIUI this is only called here https://github.com/open-telemetry/opentelemetry-collector/blob/3b97783db3e8a7f9e14aaf7ee2f231f467cb5e49/exporter/loggingexporter/logging_exporter.go#L146 which in turn is only called when shutting down the exporter, so I would argue readability is more important than performance here.

**Review by TylerHelmuth — APPROVED** [review]

File: exporter/loggingexporter/known_sync_error.go [hunk 1]
```diff
@@ -23,14 +23,24 @@ import (
...
+	var knownSyncErrors = []error{
+		// sync /dev/stdout: invalid argument
+		syscall.EINVAL,
+		// sync /dev/stdout: not supported
+		syscall.ENOTSUP,
+		// sync /dev/stdout: inappropriate ioctl for device
+		syscall.ENOTTY,
+		// sync /dev/stdout: bad file descriptor
+		syscall.EBADF,
+	}
```
Comment (bogdandrutu) [inline exporter/loggingexporter/known_sync_error.go:37]: this can be a "constant" (global var) to avoid initializing every time it is called.

**Review by bogdandrutu — APPROVED** [review]
