### PR TITLE
Avoid the exporter for being stuck when telemetry data is bigger than batch.max_size

### LINKED ISSUE #12893: [exporterhelper] A collector is eventually OOMKilled when one telemetry data is bigger than a batch max_size and the request sizer is bytes
### Component(s)

exporter/exporterhelper

### What happened?

**Describe the bug**

When an exporter has a `sending_queue.sizer=bytes` and `sending_queue.batch.max_size`, and one single telemetry data is bigger than `sending_queue.batch.max_size`, then it starts to consume memory indefinitely, and eventually the collector is OOMKilled.

**Steps to reproduce**

Set up a collector's configuration with an exporter that supports exporterhelper and include the following configuration.

```yml
    sending_queue:
      sizer: bytes
      batch:
        max_size: 10
```

Then run a collector and send telemetry data. For example, send a trace data by `telemetrygen traces --otlp-insecure --traces 1` to OTLP receiver.

**What did you expect to see?**

Telemetry data should be dropped and output error logs.

**What did you see instead?**

I couldn't see anything. But CPU usages and memory usages increase, and the process is eventually OOM Killed.
I saw `otelcol-dev` process was OOMKilled by `dmesg`.

```bash
> sudo dmesg -T | egrep -i 'killed process|oom.kill'
[Fri Apr 18 12:37:16 2025] qemu-system-x86 invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=200
[Fri Apr 18 12:37:16 2025]  oom_kill_process+0x118/0x280
[Fri Apr 18 12:37:16 2025] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-2013.slice/user@2013.service/app.slice/tmux-spawn-281eff27-82db-4b5a-8dd7-c264f1daffe7.scope,task=otelcol-dev,pid=1542808,uid=2013
[Fri Apr 18 12:37:16 2025] Out of memory: Killed process 1542808 (otelcol-dev) total-vm:32036360kB, anon-rss:24105632kB, file-rss:516kB, shmem-rss:0kB, UID:2013 pgtables:55032kB oom_score_adj:100
[Fri Apr 18 13:14:50 2025] code invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=100
[Fri Apr 18 13:14:50 2025]  oom_kill_process+0x118/0x280
[Fri Apr 18 13:14:50 2025] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-2013.slice/user@2013.service/app.slice/tmux-spawn-41f0b67f-58b9-4eab-b419-24031351ed25.scope,task=builder,pid=1663701,uid=2013
[Fri Apr 18 13:14:51 2025] Out of memory: Killed process 1663701 (builder) total-vm:27390444kB, anon-rss:23558260kB, file-rss:1500kB, shmem-rss:0kB, UID:2013 pgtables:49208kB oom_score_adj:100
[Fri Apr 18 13:25:41 2025] wpa_supplicant invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=0
[Fri Apr 18 13:25:41 2025]  oom_kill_process+0x118/0x280
[Fri Apr 18 13:25:41 2025] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=wpa_supplicant.service,mems_allowed=0,global_oom,task_memcg=/user.slice/user-2013.slice/user@2013.service/app.slice/tmux-spawn-1c691201-4657-4fc1-a2fd-746d93188ea9.scope,task=builder,pid=1693988,uid=2013
[Fri Apr 18 13:25:41 2025] Out of memory: Killed process 1693988 (builder) total-vm:39965976kB, anon-rss:24978248kB, file-rss:532kB, shmem-rss:0kB, UID:2013 pgtables:65084kB oom_score_adj:100
```

### Collector version

v0.124.0

## Environment
OS: Ubuntu 24.04
Compiler: go1.24.1, ocb: v0.124.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp:
    endpoint: localhost:14317
    tls:
      insecure: true
    sending_queue:
      sizer: bytes
      queue_size: 10000
      batch:
        flush_timeout: 1s
        max_size: 10

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
  telemetry:
    logs:
      level: debug
```

### Log output

```shell
go run ./otelcol-dev --config otel-collector-config.yaml
2025-04-18T11:52:52.486-0700    info    service@v0.124.0/service.go:199 Setting up own telemetry...
2025-04-18T11:52:52.492-0700    debug   builders/builders.go:24 Stable component.
2025-04-18T11:52:52.496-0700    debug   builders/builders.go:24 Stable component.
2025-04-18T11:52:52.496-0700    debug   otlpreceiver@v0.124.0/otlp.go:58        created signal-agnostic logger
2025-04-18T11:52:52.514-0700    info    service@v0.124.0/service.go:266 Starting otelcol-dev... {"Version": "", "NumCPU": 12}
2025-04-18T11:52:52.514-0700    info    extensions/extensions.go:41     Starting extensions...
2025-04-18T11:52:52.515-0700    info    grpc@v1.71.1/clientconn.go:176  [core] original dial target is: "localhost:14317"       {"grpc_log": true}
2025-04-18T11:52:52.517-0700    info    grpc@v1.71.1/clientconn.go:459  [core] [Channel #1]Channel created      {"grpc_log": true}
2025-04-18T11:52:52.517-0700    info    grpc@v1.71.1/clientconn.go:207  [core] [Channel #1]parsed dial target is: resolver.Target{URL:url.URL{Scheme:"passthrough", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/localhost:14317", RawPath:"", OmitHost:false, ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}}   {"grpc_log": true}
2025-04-18T11:52:52.517-0700    info    grpc@v1.71.1/clientconn.go:208  [core] [Channel #1]Channel authority set to "localhost:14317"   {"grpc_log": true}
2025-04-18T11:52:52.523-0700    info    grpc@v1.71.1/resolver_wrapper.go:210    [core] [Channel #1]Resolver state updated: {
  "Addresses": [
    {
      "Addr": "localhost:14317",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Metadata": null
    }
  ],
  "Endpoints": [
    {
      "Addresses": [
        {
          "Addr": "localhost:14317",
          "ServerName": "",
          "Attributes": null,
          "BalancerAttributes": null,
          "Metadata": null
        }
      ],
      "Attributes": null
    }
  ],
  "ServiceConfig": null,
  "Attributes": null
} (resolver returned new addresses)     {"grpc_log": true}
2025-04-18T11:52:52.525-0700    info    grpc@v1.71.1/balancer_wrapper.go:122    [core] [Channel #1]Channel switches to new LB policy "pick_first"       {"grpc_log": true}
2025-04-18T11:52:52.526-0700    info    gracefulswitch/gracefulswitch.go:194    [pick-first-lb] [pick-first-lb 0xc000139f50] Received new config {
  "shuffleAddressList": false
}, resolver state {
  "Addresses": [
    {
      "Addr": "localhost:14317",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Metadata": null
    }
  ],
  "Endpoints": [
    {
      "Addresses": [
        {
          "Addr": "localhost:14317",
          "ServerName": "",
          "Attributes": null,
          "BalancerAttributes": null,
          "Metadata": null
        }
      ],
      "Attributes": null
    }
  ],
  "ServiceConfig": null,
  "Attributes": null
}       {"grpc_log": true}
2025-04-18T11:52:52.527-0700    info    grpc@v1.71.1/balancer_wrapper.go:195    [core] [Channel #1 SubChannel #2]Subchannel created     {"grpc_log": true}
2025-04-18T11:52:52.528-0700    info    grpc@v1.71.1/clientconn.go:563  [core] [Channel #1]Channel Connectivity change to CONNECTING    {"grpc_log": true}
2025-04-18T11:52:52.529-0700    info    grpc@v1.71.1/clientconn.go:364  [core] [Channel #1]Channel exiting idle mode    {"grpc_log": true}
2025-04-18T11:52:52.530-0700    info    grpc@v1.71.1/server.go:690      [core] [Server #3]Server created        {"grpc_log": true}
2025-04-18T11:52:52.531-0700    info    otlpreceiver@v0.124.0/otlp.go:116       Starting GRPC server    {"endpoint": "0.0.0.0:4317"}
2025-04-18T11:52:52.531-0700    info    service@v0.124.0/service.go:289 Everything is ready. Begin running and processing data.
2025-04-18T11:52:52.532-0700    info    grpc@v1.71.1/clientconn.go:1224 [core] [Channel #1 SubChannel #2]Subchannel Connectivity change to CONNECTING   {"grpc_log": true}
2025-04-18T11:52:52.532-0700    info    grpc@v1.71.1/clientconn.go:1344 [core] [Channel #1 SubChannel #2]Subchannel picks a new address "localhost:14317" to connect    {"grpc_log": true}
2025-04-18T11:52:52.533-0700    info    grpc@v1.71.1/server.go:886      [core] [Server #3 ListenSocket #4]ListenSocket created  {"grpc_log": true}
2025-04-18T11:52:52.533-0700    info    pickfirst/pickfirst.go:184      [pick-first-lb] [pick-first-lb 0xc000139f50] Received SubConn state update: 0xc00027e370, {ConnectivityState:CONNECTING ConnectionError:<nil> connectedAddress:{Addr: ServerName: Attributes:<nil> BalancerAttributes:<nil> Metadata:<nil>}}   {"grpc_log": true}
2025-04-18T11:52:52.548-0700    info    grpc@v1.71.1/clientconn.go:1224 [core] [Channel #1 SubChannel #2]Subchannel Connectivity change to READY        {"grpc_log": true}
2025-04-18T11:52:52.548-0700    info    pickfirst/pickfirst.go:184      [pick-first-lb] [pick-first-lb 0xc000139f50] Received SubConn state update: 0xc00027e370, {ConnectivityState:READY ConnectionError:<nil> connectedAddress:{Addr:localhost:14317 ServerName:localhost:14317 Attributes:<nil> BalancerAttributes:<nil> Metadata:<nil>}}  {"grpc_log": true}
2025-04-18T11:52:52.548-0700    info    grpc@v1.71.1/clientconn.go:563  [core] [Channel #1]Channel Connectivity change to READY {"grpc_log": true}
2025-04-18T11:52:55.995-0700    info    transport/http2_server.go:662   [transport] [server-transport 0xc0000f6000] Closing: read tcp 127.0.0.1:4317->127.0.0.1:46322: read: connection reset by peer  {"grpc_log": true}
2025-04-18T11:52:55.997-0700    info    transport/controlbuf.go:577     [transport] [server-transport 0xc0000f6000] loopyWriter exiting with error: transport closed by client  {"grpc_log": true}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iblancasa**
#### Description
 This change fixes a bug where the exporter would get stuck when the telemetry data is bigger than batch.max_size. The bug was causing the OpenTelemetry Collector to hang and being OOM Killed at some point.

#### Link to tracking issue
Fixes #12893

### CODE REVIEW

File: exporter/exporterhelper/logs_batch.go [hunk 1]
```diff
@@ -49,11 +49,25 @@ func (req *logsRequest) mergeTo(dst *logsRequest, sz sizer.LogsSizer) {
...
+		ld, rmSize = extractLogs(req.ld, maxSize, sz)
+		if ld.LogRecordCount() > 0 {
+			req.setCachedSize(req.size(sz) - rmSize)
+			res = append(res, newLogsRequest(ld))
+		}
 	}
+
+	if req.size(sz) == previousSize && req.size(sz) > maxSize {
+		// This means we cannot split the log and is not possible
+		// to fit it into the max size.
```
Comment (jmacd) [inline exporter/exporterhelper/logs_batch.go:67]: Should there be an error, somehow? I'm not following what will happen to the too-large data.

Comment (iblancasa) [reply exporter/exporterhelper/logs_batch.go:67]: In this PR, I drop the data that can not be splitted. If we return an error, the full batch will be dropped. But with this approach, we only drop what can not be splitted.
Maybe is not the best. I’m open to change it :)

Comment (jmacd) [reply exporter/exporterhelper/logs_batch.go:67]: I like the behavior and the outcome (i.e., drop the data, return success eventually). This is the sort of failure I would place into the `rejected` count in the PartialSuccess message that the OTLP receiver will send on the return path (if synchronous). I realize that not all receivers are OTLP (or synchronous) and that we're talking about _exporter_ behavior here, so it would be simpler to log a warning, like `logger.Warn("individual item larger than size limit", zap.Int("requested", item.Size), zap.Int("limit", config.Limit))`.

I suspect most will agree to a noisy log under the circumstances--otherwise aren't we silently dropping data? Sorry if I've misunderstood, thanks.

Comment (iblancasa) [reply exporter/exporterhelper/logs_batch.go:67]: You understood properly.

Comment (iblancasa) [reply exporter/exporterhelper/logs_batch.go:69]: Done

**Comment by iblancasa** [comment]
@dmitryax @bogdandrutu can you take a look to this PR?

**Comment by iblancasa** [comment]
> @iblancasa can you please split the PR in two? One fixes the bug, another adds the telemetry

Sure :)

File: exporter/exporterhelper/traces_batch.go [hunk 2]
```diff
@@ -7,13 +7,15 @@ import (
...
+	"go.uber.org/zap"
+
 	"go.opentelemetry.io/collector/exporter/exporterhelper/internal/sizer"
 	"go.opentelemetry.io/collector/pdata/ptrace"
 )
 
 // MergeSplit splits and/or merges the provided traces request and the current request into one or more requests
 // conforming with the MaxSizeConfig.
-func (req *tracesRequest) MergeSplit(_ context.Context, maxSize int, szt RequestSizerType, r2 Request) ([]Request, error) {
+func (req *tracesRequest) MergeSplit(_ context.Context, maxSize int, szt RequestSizerType, r2 Request, logger *zap.Logger) ([]Request, error) {
```
Comment (dmitryax) [inline exporter/exporterhelper/traces_batch.go:18]: Adding the argument breaks the public API. Why can't we return the error and log it in the `Consume` method?

If we don't want to drop the whole batch, we can introduce new type of errors that would represent the OTLP PartialSuccess.

Comment (iblancasa) [reply exporter/exporterhelper/traces_batch.go]: Mmmm good idea! Let me take a look.
Thanks!

**Comment by iblancasa** [comment]
@dmitryax the PR is ready to go.

**Comment by iblancasa** [comment]
@bogdandrutu @jmacd @dmathieu @mx-psi

File: exporter/exporterhelper/internal/queuebatch/partition_batcher.go [hunk 3]
```diff
@@ -101,7 +124,24 @@ func (qb *partitionBatcher) Consume(ctx context.Context, req request.Request, do
...
+		if !errors.As(mergeSplitErr, &partialSuccessErr) {
+			done.OnDone(mergeSplitErr)
+			qb.currentBatchMu.Unlock()
+			return
+		}
+		qb.logger.Warn(
+			"failed to split request",
+			zap.Int("failure_count", partialSuccessErr.FailureCount),
+			zap.String("reason", partialSuccessErr.Reason),
+		)
```
Comment (bogdandrutu) [inline exporter/exporterhelper/internal/queuebatch/partition_batcher.go]: I don't see any good reason to have `partialsuccess.PartialSuccessError` since action is exactly the same and only log something else. 

You can just change this to log the error (and put the information in the error text).

Comment (iblancasa) [reply exporter/exporterhelper/internal/queuebatch/partition_batcher.go]: When I created this PR, it was doing more stuff like exposing metrics about the partial success errors (those that happen in the batching algorithm). Here (https://github.com/open-telemetry/opentelemetry-collector/pull/12982#issuecomment-2910946391) I was asked to split the PR. I'm waiting to have this PR approved and merge to create the other one.

So, I think it makes sense to keep the partial success. Also, I think it can be interesting for other future partial errors that we can find in the future. But I don't have a strong opinion about that.

If you still think it doesn't make sense to keep the custom error, I'm open to change it.

Comment (sfc-gh-bdrutu) [reply exporter/exporterhelper/internal/queuebatch/partition_batcher.go]: Let's not have that until we have a strong understanding of the need.

Comment (iblancasa) [reply exporter/exporterhelper/internal/queuebatch/partition_batcher.go]: Ok, I will simplify. Thanks again!

File: exporter/exporterhelper/internal/queuebatch/partition_batcher.go [hunk 4]
```diff
@@ -66,7 +71,19 @@ func (qb *partitionBatcher) Consume(ctx context.Context, req request.Request, do
...
+		if mergeSplitErr != nil {
+			if !strings.Contains(mergeSplitErr.Error(), "partial success") {
+				done.OnDone(mergeSplitErr)
+				qb.currentBatchMu.Unlock()
+				return
+			}
+			qb.logger.Warn(mergeSplitErr.Error())
+			done.OnDone(mergeSplitErr)
+			qb.currentBatchMu.Unlock()
+			return
```
Comment (bogdandrutu) [inline exporter/exporterhelper/internal/queuebatch/partition_batcher.go]: Should we not always add the warning?

File: exporter/exporterhelper/internal/queuebatch/partition_batcher.go [hunk 5]
```diff
@@ -66,7 +71,16 @@ func (qb *partitionBatcher) Consume(ctx context.Context, req request.Request, do
 
 	if qb.currentBatch == nil {
 		reqList, mergeSplitErr := req.MergeSplit(ctx, int(qb.cfg.MaxSize), qb.sizerType, nil)
-		if mergeSplitErr != nil || len(reqList) == 0 {
+		if mergeSplitErr != nil {
+			qb.logger.Warn(mergeSplitErr.Error())
+			if !strings.Contains(mergeSplitErr.Error(), "partial success") {
```
Comment (bogdandrutu) [inline exporter/exporterhelper/internal/queuebatch/partition_batcher.go:73]: I think we should remove this?

File: exporter/exporterhelper/internal/queuebatch/partition_batcher.go [hunk 6]
```diff
@@ -101,7 +115,15 @@ func (qb *partitionBatcher) Consume(ctx context.Context, req request.Request, do
 
 	reqList, mergeSplitErr := qb.currentBatch.req.MergeSplit(ctx, int(qb.cfg.MaxSize), qb.sizerType, req)
 	// If failed to merge signal all Done callbacks from the current batch as well as the current request and reset the current batch.
-	if mergeSplitErr != nil || len(reqList) == 0 {
+	if mergeSplitErr != nil {
+		qb.logger.Warn(mergeSplitErr.Error())
```
Comment (bogdandrutu) [inline exporter/exporterhelper/internal/queuebatch/partition_batcher.go:116]:
```suggestion
		qb.logger.Warn("failed to merge split the request.", zap.Error(mergeSplitErr))
```

**Review by dmathieu — APPROVED** [review]

**Comment by iblancasa** [comment]
@open-telemetry/collector-approvers could we move forward with this PR? I have been just fixing conflicts during the last 3 or 4 pushes.

**Comment by bogdandrutu** [comment]
@iblancasa I will do all the comments I asked you and did not do... In the followup

**Comment by iblancasa** [comment]
> @iblancasa I will do all the comments I asked you and did not do... In the followup

I replied to your comments explaining why I think we should keep the code as it is right now: when the problem is that the telemetry data is bigger than `batch.max_size`, we don't want to send the "offending" data but the rest of telemetry data.

https://github.com/open-telemetry/opentelemetry-collector/pull/12982#discussion_r2188229226

If you refer to something else, please let me know and I will be more than happy to implement.

**Comment by iblancasa** [comment]
Link to follow up pr for reference https://github.com/open-telemetry/opentelemetry-collector/pull/13419
