### PR TITLE
[fips140][`configurablehttpprovider.TestFunctionalityDownloadFileHTTPS`] Skip test if `GODEBUG=fips140=only` is set

### LINKED ISSUE #13998: [fips140] `confmap/provider/internal/configurablehttpprovider.TestFunctionalityDownloadFileHTTPS` unit test fails with `GODEBUG=fips140=only`
### Component(s)

_No response_

### Describe the issue you're reporting

Running the `confmap/provider/internal/configurablehttpprovider.TestFunctionalityDownloadFileHTTPS` unit test with `GODEBUG=fips140=only` exposes any calls (direct or indirect) to non-FIPS140-compliant algorithms.  

Such calls may be made by the test's code or from collector code exercised by the test. Also, the calls may be true positives or false positives (e.g. using `md5`, which is not FIPS140-compliant for cryptographic uses, in a non-cryptographic context, e.g. hashing for checksums).  Depending on where the calls are being made from (test code or collector code) and whether they're true or false positives, we may need to either a) provide an alternative implementation — using the `requirefips` build tag — for the calls with ones to FIPS-compliant algorithms, b) skip the test when `GODEBUG=fips140=only` (should be done only if the calls are being made from the test code itself), or c) disable the code paths leading to the calls when the module is built with the `requirefips` build tag and document this (least preferred option).

Related to https://github.com/open-telemetry/opentelemetry-collector/issues/13925 and https://github.com/open-telemetry/opentelemetry-collector/pull/13926.

### Steps to reproduce

Run the `configurablehttpprovider.TestFunctionalityDownloadFileHTTPS` unit test with `GODEBUG=fips140=only`.
   ```
   $ cd confmap/
   $ GODEBUG=fips140=only go test ./provider/internal/configurablehttpprovider/... -test.v -test.run TestFunctionalityDownloadFileHTTPS -count 1
   ```

### Observed output

```
=== RUN   TestFunctionalityDownloadFileHTTPS
--- FAIL: TestFunctionalityDownloadFileHTTPS (0.11s)
panic: crypto/sha1: use of SHA-1 is not allowed in FIPS 140-only mode [recovered, repanicked]

goroutine 19 [running]:
testing.tRunner.func1.2({0x1052cfc60, 0x1053613a0})
	/Users/shaunak/.gvm/gos/go1.25.1/src/testing/testing.go:1872 +0x190
testing.tRunner.func1()
	/Users/shaunak/.gvm/gos/go1.25.1/src/testing/testing.go:1875 +0x31c
panic({0x1052cfc60?, 0x1053613a0?})
	/Users/shaunak/.gvm/gos/go1.25.1/src/runtime/panic.go:783 +0x120
crypto/sha1.Sum({0x1400033c240?, 0x1400033ad28?, 0x1400033a850?})
	/Users/shaunak/.gvm/gos/go1.25.1/src/crypto/sha1/sha1.go:278 +0x104
crypto/x509.CreateCertificate({0x105363800, 0x140000981c0}, 0x1400033afc0, 0x1400033afc0, {0x1052f0c80, 0x14000229f10}, {0x105333160?, 0x14000229f10})
	/Users/shaunak/.gvm/gos/go1.25.1/src/crypto/x509/x509.go:1738 +0x424
go.opentelemetry.io/collector/confmap/provider/internal/configurablehttpprovider.generateCertificate(0x14000082fc0, {0x10520103c, 0x9})
	/Users/shaunak/development/github/opentelemetry-collector/confmap/provider/internal/configurablehttpprovider/provider_test.go:82 +0x358
go.opentelemetry.io/collector/confmap/provider/internal/configurablehttpprovider.TestFunctionalityDownloadFileHTTPS(0x14000082fc0)
	/Users/shaunak/development/github/opentelemetry-collector/confmap/provider/internal/configurablehttpprovider/provider_test.go:127 +0x40
testing.tRunner(0x14000082fc0, 0x10535e670)
	/Users/shaunak/.gvm/gos/go1.25.1/src/testing/testing.go:1934 +0xc8
created by testing.(*T).Run in goroutine 1
	/Users/shaunak/.gvm/gos/go1.25.1/src/testing/testing.go:1997 +0x364
FAIL	go.opentelemetry.io/collector/confmap/provider/internal/configurablehttpprovider	0.473s
FAIL
```

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by ycombinator**
#### Description

When https://github.com/open-telemetry/opentelemetry-collector/pull/13926 is merged, all unit tests in this repository will be run with `GODEBUG=fips140=only` to help surface any FIPS-140 violations in all the Go modules in this repository.

One such unit test that fails in these circumstances is `confmap/provider/internal/configurablehttpprovider.TestFunctionalityDownloadFileHTTPS`.  However, the FIPS violation surfaced by this test is from the test code itself (as opposed to from OpenTelemetry Collector core code that the test is exercising), specifically when this call is made: https://github.com/open-telemetry/opentelemetry-collector/blob/0f3b0c974e235da85282c6d6ff5734e55e8f4fbc/confmap/provider/internal/configurablehttpprovider/provider_test.go#L81

As such, this is not a FIPS violation we need to worry about when running the OpenTelemetry Collector.  To prevent the unit test from failing when it's run with `GODEBUG=fips140=only`, we skip it.

#### Link to tracking issue
Fixes #13998

#### Testing

Run the `configurablehttpprovider.TestFunctionalityDownloadFileHTTPS` unit test with `GODEBUG=fips140=only`.
   ```
   $ cd confmap/
   $ GODEBUG=fips140=only go test ./provider/internal/configurablehttpprovider/... -test.v -test.run TestFunctionalityDownloadFileHTTPS -count 1
   ```

### CODE REVIEW

File: internal/testutil/fips.go [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+	"os"
+	"strings"
+	"testing"
+)
+
+// SkipIfFIPSOnly will mark the passed test as skipped if GODEBUG=fips140=only is detected.
+// If GODEBUG=fips140=on, go may call non-compliant algorithms and the test does not need to be skipped.
+func SkipIfFIPSOnly(t *testing.T, msg string) {
+	// NOTE: This only checks env var; at the time of writing fips140 can only be set via env
+	// other GODEBUG settings can be set via embedded comments or in go.mod, we may need to account for this in the future.
```
Comment (mx-psi) [inline internal/testutil/fips.go:16]: For my own education: is the [`GOFIPS140`](https://go.dev/doc/security/fips140#the-gofips140-environment-variable) env variable only used for deciding the version but not for enabling/disabling then?

Comment (ycombinator) [reply internal/testutil/fips.go:16]: My understanding is that the `GOFIPS140` environment variable is used to select the version of the Go Cryptographic Module to use but, as of now, none of these versions are validated as being FIPS-compliant (mentioned further down in the same doc).  So, IMO, there is no benefit to setting this variable, again, as of now.

**Comment by ycombinator** [comment]
> Can you move the test util to `confmap/provider/internal`? That way we avoid creating more public API. Another alternative is to create a module for testing utils

Thanks for the suggestion, @mx-psi.  I decided to make a new module for testing utilities; see 87349a77abed80d4dde4776ead96ecbdf357d6c3.

However, now CI is failing on this PR like so:

```
go: finding module for package go.opentelemetry.io/collector/testutils
go: downloading go.opentelemetry.io v0.1.0
go: go.opentelemetry.io/collector/cmd/otelcorecol imports
	go.opentelemetry.io/collector/confmap/provider/httpprovider imports
	go.opentelemetry.io/collector/confmap/provider/internal/configurablehttpprovider tested by
	go.opentelemetry.io/collector/confmap/provider/internal/configurablehttpprovider.test imports
	go.opentelemetry.io/collector/testutils: module go.opentelemetry.io/collector@latest found (v0.138.0, replaced by ../../), but does not contain package go.opentelemetry.io/collector/testutils
make[2]: *** [../../Makefile.Common:67: tidy] Error 1
make[2]: Leaving directory '/home/runner/work/opentelemetry-collector/opentelemetry-collector/cmd/otelcorecol'
make[1]: *** [Makefile:148: cmd/otelcorecol] Error 2
make[1]: Leaving directory '/home/runner/work/opentelemetry-collector/opentelemetry-collector'
make: *** [Makefile:95: gotidy] Error 2
Error: Process completed with exit code 2.
```

I'm guessing I need to make a separate PR first that introduces the `go.opentelemetry.io/collector/testutils` module?

**Comment by dmathieu** [comment]
This shouldn't be a public module. If we expect there will be more tests skipped on FIPS, it makes sense to have this as a module global to the collector. But it should be under `internal/`.

**Comment by ycombinator** [comment]
@dmathieu Thanks for the suggestion and discussion (off-PR).  Please take a look at d5722571da3ae79aee8ba8c1ebec064d2ad44f08 and 3aba4a903977d24ce9c3e646df9b1b52be2365ae.  Is this in line with what you were suggesting?

**Comment by dmathieu** [comment]
It is. I think to fix the linter, you need to run `make gotidy`.

**Comment by ycombinator** [comment]
> It is. I think to fix the linter, you need to run `make gotidy`.

Thanks.  I ran `make gotidy` and am getting this error:

```
go: go.opentelemetry.io/collector/cmd/otelcorecol imports
	go.opentelemetry.io/collector/exporter/otlpexporter tested by
	go.opentelemetry.io/collector/exporter/otlpexporter.test imports
	go.opentelemetry.io/collector/internal/testutil: module go.opentelemetry.io/collector@latest found (v0.138.0, replaced by ../../), but does not contain package go.opentelemetry.io/collector/internal/testutil
make[2]: *** [tidy] Error 1
make[1]: *** [cmd/otelcorecol] Error 2
make: *** [gotidy] Error 2
```

Do you think I need to publish the `go.opentelemetry.io/collector/internal/testutil` module first via a separate PR?

**Comment by dmathieu** [comment]
You need a replace statement so the testutil package properly points to the local path, not to a released package.

```diff
diff --git a/confmap/go.mod b/confmap/go.mod
index 35d3f3f81..426bbf6ba 100644
--- a/confmap/go.mod
+++ b/confmap/go.mod
@@ -10,6 +10,7 @@ require (
        github.com/knadh/koanf/v2 v2.3.0
        github.com/stretchr/testify v1.11.1
        go.opentelemetry.io/collector/featuregate v1.44.0
+       go.opentelemetry.io/collector/internal/testutil v0.0.0-00010101000000-000000000000
        go.uber.org/goleak v1.3.0
        go.uber.org/multierr v1.11.0
        go.uber.org/zap v1.27.0
@@ -30,4 +31,6 @@ retract (
        v0.69.0 // Release failed, use v0.69.1
 )

+replace go.opentelemetry.io/collector/internal/testutil => ../internal/testutil
+
```

**Review by dmathieu — APPROVED** [review]

**Comment by mx-psi** [comment]
@ycombinator Thanks for the PR! Once the PR is merged (in about 20 minutes if everything goes well), I would appreciate if you file a follow up PR with step 5 of the "when adding a new module" instructions listed on the coding guidelines: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/coding-guidelines.md#module-organization

**Comment by ycombinator** [comment]
> @ycombinator Thanks for the PR! Once the PR is merged (in about 20 minutes if everything goes well), I would appreciate if you file a follow up PR with step 5 of the "when adding a new module" instructions listed on the coding guidelines: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/coding-guidelines.md#module-organization

Hi @mx-psi, I believe this pertains to the use of the `internal/testutil` module? If so, I've created https://github.com/open-telemetry/opentelemetry-collector/pull/14219.
