### PR TITLE
[otelcol] Fix missing defaults in unredacted print-config

### LINKED ISSUE #14750: Bug: `otelcol print-config` mode=unredacted output omits default values, making results very different from redacted mode
### Component(s)

_No response_

### What happened?

**Describe the bug**
When running `otelcol print-config` (or equivalent) with `--mode=unredacted`, the output YAML shows all unredacted sensitive values, but ONLY includes fields that are explicitly set in the config or passed in by env vars. All default values that would normally be filled by the Collector for missing fields are completely omitted in the output. This means the unredacted output is very sparse for any minimal configs.

Meanwhile, `mode=redacted` produces output that looks like the fully merged/parsed config with all defaults filled in (but with secrets redacted), so the outputs are drastically different in content.

**Steps to reproduce**
1. Create a minimal config file that uses env variables for some sensitive fields (e.g. passwords, keys).
2. Run print-config with `--mode=redacted` and note that all config options (including those not in the file, i.e. defaults) are present (but with secrets redacted).
3. Run print-config with `--mode=unredacted`; the output now includes actual/unredacted secrets, but many keys/sections present in the redacted output are missing entirely (all that weren't explicitly set).
4. This makes the output structurally very different between modes.

**What did you expect to see?**
I expected that the only difference between redacted and unredacted modes would be that masks are removed and sensitive values would be printed in plaintext. Instead, the unredacted output is much more incomplete due to missing defaults, making it hard to compare, parse, or use for CI purposes.

**Use case / rationale**
We use print-config in unredacted mode in CI to validate that env var substitution works for sensitive values (secrets, keys, etc). But the unredacted output then omits all default-valued options, so the config looks incomplete and it's not possible to compare full/merged configs between redacted/unredacted modes accurately. This (1) increases risk of missing changes, (2) makes QA harder, (3) breaks downstream tools that consume the print-config results. Ideally, unredacted mode would be identical to redacted except for showing actual unredacted data.

**Suggested fix**
Have the unredacted mode also print the fully merged, default-filled configuration, just without masking sensitive data (i.e., same as redacted, but w/o masking), so both modes are structurally the same except for the secrets.

### Collector version

v0.147.0

### Environment information

CI context: using print-config to check env var interpolation + validate effective config (with secrets visible)
OS: multiple

### OpenTelemetry Collector configuration

```yaml
Minimal config example:


receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${MY_OTLP_ENDPOINT}
exporters:
  otlp:
    endpoint: ${OTLP_EXPORTER_ENDPOINT}
    headers:
      "x-api-key": ${API_KEY}


env vars are set for all referenced fields.
```

### Log output

```shell
No errors; the issue is with what output appears vs. expected.
```

### Additional context

_No response_

### Tip

_No response_

### PR DESCRIPTION
**Pull request by EdgeN8v**
**Description**

Fixes an issue where `otelcol print-config --mode=unredacted` omits default values, causing its output structure to differ significantly from `redacted` mode.

*Implementation details:*
This PR introduces a new `confmap.WithUnredacted()` `MarshalOption` and an `unredactedStringer` interface within the `mapstructure` encoder. This allows the configuration to be marshaled natively without redaction, preserving all default values while cleanly decoupling the encoder from `configopaque`. The previous recursive post-processing workaround has been entirely removed.

**Link to tracking issue**

Fixes #14750

**Testing**

* Removed obsolete tests related to the recursive workaround.
* Updated `TestPrintCommand` in `command_print_test.go` to assert default values are correctly handled natively in `unredacted` mode.
* Passed `make test` locally.

**Documentation**

* Added `.chloggen` entry.

### CODE REVIEW

**Comment by EdgeN8v** [comment]
Hi @axw, the slight coverage drop is just the basic `err != nil` branches for the config setup (`getPrintableConfig`, `Marshal`, `NewResolver`). 

The core `restoreSecrets` logic is fully covered. I skipped mocking those framework errors to keep the tests clean.

File: otelcol/command_print_test.go [hunk 1]
```diff
@@ -132,12 +128,8 @@ func TestPrintCommand(t *testing.T) {
...
 			path: defaultConfig,
 			outString: map[string]string{
-				"redacted": `opaque: '[REDACTED]'`,
-
-				// Note: the default opaque value does not print,
-				// the other value is set in defaultConfig so that
-				// the whole component config is not defaulted.
-				"unredacted": `other: lala`,
+				"redacted":   `opaque: '[REDACTED]'`,
+				"unredacted": `opaque: '[REDACTED]'`,
```
Comment (codeboten) [inline otelcol/command_print_test.go]: is this value not expected to be unredacted as well?

File: otelcol/command_print_test.go [hunk 2]
```diff
@@ -72,10 +72,9 @@ func TestPrintCommand(t *testing.T) {
 			path: validConfig,
 		},
 		{
-			name:            "invalid syntax without validate",
-			path:            invalidConfig1,
-			errString:       "'timeout' time: invalid duration",
-			errOnlyRedacted: true,
```
Comment (codeboten) [inline otelcol/command_print_test.go:78]: can this field in the struct be removed as well? it doesn't look like it's used anywhere else

File: otelcol/command_print_test.go (hunk 1 above)
Comment (EdgeN8v) [reply otelcol/command_print_test.go]: Since default values aren't in the user's raw input, we don't have a cleartext source to restore them from. So it stays as `[REDACTED]`.

Comment (axw) [reply otelcol/command_print_test.go]: I'm unresolving this as I think there may be another option. We can choose not to go with it, but we should still discuss whether this is acceptable.

**Comment by dmathieu** [comment]
I haven't looked deeply into this, but I agree that the current approach (relying on the `[REDACTED]` value to unredact) isn't the most readable/clean approach. We can do better.

File: confmap/internal/mapstructure/encoder.go [hunk 3]
```diff
@@ -268,3 +268,14 @@ func YamlMarshalerHookFunc() mapstructure.DecodeHookFuncValue {
 		return from.Interface(), nil
 	}
 }
+
+func StringTextUnredactedHookFunc() mapstructure.DecodeHookFuncValue {
+	return func(from, _ reflect.Value) (any, error) {
+		if from.Kind() == reflect.String {
+			if _, ok := from.Interface().(encoding.TextMarshaler); ok {
+				return from.String(), nil
+			}
```
Comment (axw) [inline confmap/internal/mapstructure/encoder.go:282]: This feels like quite a subtle tight coupling to `configopaque.Opaque`. Instead, perhaps we should introduce an interface like

```go
type UnredactedStringer interface {
    UnredactedString() string
}
```

and have `configopaque.Opaque` implement it.

**Comment by mx-psi** [comment]
I would rather avoid adding public API to a stable module like `configopaque` for experimental functionality like `print-config`. While I think the solution proposed on this PR is clean, given that `print-config` is not still stable, I would like to explore what alternatives we have that don't require this new public API method (`UnredactedString` mehtod)

File: confmap/internal/marshaloption.go [hunk 4]
```diff
@@ -9,7 +9,10 @@ type MarshalOption interface {
 
 // MarshalOptions is used by (*Conf).Marshal to toggle unmarshaling settings.
 // It is in the `internal` package so experimental options can be added in xconfmap.
-type MarshalOptions struct{}
+type MarshalOptions struct {
+	// OpaqueUnredacted specifies whether opaque strings should be marshaled unredacted.
+	OpaqueUnredacted bool
```
Comment (dmathieu) [inline confmap/internal/marshaloption.go:14]: Could `OpaqueUnredacted` be private?

File: confmap/internal/mapstructure/encoder.go (hunk 3 above)
Comment (VihasMakwana) [reply confmap/internal/mapstructure/encoder.go:282]: ++

File: otelcol/command_print.go [hunk 5]
```diff
@@ -186,5 +181,6 @@ func (pctx *printContext) printRedactedConfig() error {
 	if err := confMap.Marshal(cfg); err != nil {
 		return fmt.Errorf("failed to marshal config: %w", err)
 	}
+
```
Comment (VihasMakwana) [inline otelcol/command_print.go]:
```suggestion
```

**Review by axw — APPROVED** [review]
Given that the new option is in xconfmap, and therefore unstable, I think we can go ahead with this and look into adding another interface later.

File: confmap/internal/marshaloption.go (hunk 4 above)
Comment (EdgeN8v) [reply confmap/internal/marshaloption.go:14]: Making it private breaks access from `xconfmap` unless we add a public setter in `internal`.
