### PR TITLE
[service] Share log sampler core allocations with reflect magic

### LINKED ISSUE #13014: Collector memory increases by about ~20 MB after v0.125.0 release
### Component(s)

service

### What happened?

**Describe the bug**

We noticed that the collector memory increases by about ~20 MB after the latest release. Here's a graph (plotted using `otelcol_process_memory_rss` metric) showing  the memory of the collector running an older version (v0.120.0) and the newer version:

Image

**Steps to reproduce**

Upgrade the collector to the latest version

**What did you expect to see?**

Very minimal increase in memory used by the collector.

**What did you see instead?**

The memory increased by about ~20 MB. 

### Collector version

v0.125.0

## Environment
OS: Centos7
Compiler(if manually compiled): go 1.23.7

### Additional context

We collected heap profiles from both old and new versions of the collector. Here's the heap profile from old version:

Image

Here's the heap profile from the new version of the collector:

Image

It looks like the memory increase is because of a new usage of zap somewhere (`go.uber.org/zap/zapcore.newCounters`). Drilling down using the flamegraph shows the call stack:

Image

The call to the `zapcore.NewSamplerWithOptions` seems to be added here: https://github.com/open-telemetry/opentelemetry-collector/pull/12617. The ~20 MB increase seems excessive just to maintains some logging related counters.

### PR DESCRIPTION
**Pull request by jade-guiton-dd**
#### Context

PR #12617, which implemented the injection of component-identifying attributes into the `zap.Logger` provided to components, introduced significant additional memory use when the Collector's pipelines contain many components (#13014). This was because we would call `zapcore.NewSamplerWithOptions` to wrap the specialized logger core of each Collector component, which allocates half a megabyte's worth of sampling counters.

This problem was mitigated in #13015 by moving the sampling layer to a different location in the logger core hierarchy. This meant that Collector users that do not export their logs through OTLP and only use stdout-based logs no longer saw the memory increase.

#### Description

This PR aims to provide a better solution to this issue, by using the `reflect` library to clone zap's sampler core and set a new inner core, while reusing the counter allocation.

(This may also be "more correct" from a sampling point of view, ie. we only have one global instance of the counters instead of one for console logs and one for each component's OTLP-exported logs, but I'm not sure if anyone noticed the difference anyway).

#### Link to tracking issue
Fixes #13014

#### Testing
A new test was added which checks that the log counters are shared between two sampler cores with different attributes.

### CODE REVIEW

**Comment by mx-psi** [comment]
My comment from today's 1.0 meeting: I think we want to avoid the following situations:
1. Somebody uses an incompatible zap version and the error message they get regarding this is too cryptic. Ideally the message links to somewhere where they can complain and say "hey, you broke me".
2. We upgrade zap, this solution stops working but we don't realize

**Comment by jade-guiton-dd** [comment]
@mx-psi 
1. I added a panic message when our assumptions on the sampler type fail with a link to this PR, hopefully that should work.
2. I can't think of a way that Zap could make this stop working without either a panic on startup (eg. the `Core` field no longer exists) or the test failing (eg. they inline the `counters` inside the struct, so no more sharing).

**Review by mx-psi — APPROVED** [review]

File: internal/telemetry/componentattribute/logger_zap.go [hunk 1]
```diff
@@ -96,17 +98,68 @@ func NewOTelTeeCoreWithAttributes(consoleCore zapcore.Core, lp log.LoggerProvide
...
+}
+
+func (ssc *samplerCoreWithAttributes) withAttributeSet(attrs attribute.Set) zapcore.Core {
+	newInner := tryWithAttributeSet(ssc.from, attrs)
+
+	// https://github.com/uber-go/zap/blob/fcf8ee58669e358bbd6460bef5c2ee7a53c0803a/zapcore/sampler.go#L168
+	// We need to create a new Zap sampler core with the same settings but with a new inner core,
+	// while reusing the very RAM-intensive `counters` data structure.
+	// The `With` method does something similar, but it's not quite what we want, so we use `reflect`.
+	// This hack can be removed once Zap supports this use case.
```
Comment (jmacd) [inline internal/telemetry/componentattribute/logger_zap.go]: Thanks for the detailed comment.

**Review by jmacd — APPROVED** [review]

File: internal/telemetry/componentattribute/logger_zap.go (hunk 1 above)
Comment (bogdandrutu) [reply internal/telemetry/componentattribute/logger_zap.go]: @jade-guiton-dd would be good if we can file an issue for this on their side and link it here.

Comment (jade-guiton-dd) [reply internal/telemetry/componentattribute/logger_zap.go]: I filed an issue a while back, added it to the comment.
