### PR TITLE
Fix overflowing batch size

### LINKED ISSUE #1140: Batch processor returns a bigger batch than configured
**Describe the bug**

The Batch processor can send a bigger batch than it is configured. For example `send_batch_size` is sed to `500` but the returned batches are `~800`. 

**Steps to reproduce**
Configure `send_batch_size` = N and send either bigger batches to the receiver or smaller but in very high frequency.

**What did you expect to see?**

The returned batch size always be <= configured size in `send_batch_size`.

**What did you see instead?**

Batch sizes >= `send_batch_size`.

**What version did you use?**
`master`

**What config did you use?**
```yaml
processors:
  batch:
    send_batch_size: 1000
    timeout: 200ms
```

**Environment**
Linux

**Additional context**

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

**Description:** <Describe what has changed. 

This PR adds configuration property `enfoce_batch_size` to batch processor that ensures that batch size does not overflow the configured `max_batch_size`. The default value is `false` hence it does not change the default behavior. 

If the incoming batch size is bigger than available space in cached traces then the incoming batch is split into reaming size and size of the maximum batch size. The spans that would overflow the buffer are sent again in trace data over the channel. 

**Link to tracking Issue:** <Issue number if applicable>

Resolves #1140
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/1020

**Testing:** < Describe what testing was performed and which tests were added.>

**Documentation:** < Describe the documentation added.>

`enfoce_batch_size` has been added to the readme.

### CODE REVIEW

File: processor/batchprocessor/batch_processor.go [hunk 1]
```diff
@@ -327,3 +336,61 @@ func (bm *batchMetrics) add(pm pdata.Metrics) {
...
+
+		for j := rs.InstrumentationLibrarySpans().Len() - 1; j >= 0; j-- {
+			instSpans := rs.InstrumentationLibrarySpans().At(j)
+			copiedInstSpans := pdata.NewInstrumentationLibrarySpans()
+			copiedInstSpans.InitEmpty()
+			instSpans.InstrumentationLibrary().CopyTo(copiedInstSpans.InstrumentationLibrary())
+			copiedRs.InstrumentationLibrarySpans().Append(&copiedInstSpans)
+			for k := instSpans.Spans().Len() - 1; k >= 0 && copied < size; k-- {
+				span := instSpans.Spans().At(k)
+				copiedInstSpans.Spans().Append(&span)
```
Comment (pavolloffay) [inline processor/batchprocessor/batch_processor.go:379]: This might not be ideal in terms of resizing the array. The size could be initialized before the loop.

**Comment by dmitryax** [comment]
The original idea of the batcher is to batch traces together and do it as performant as possible. That why it doesn't enforce any hard limit on the batch size. It might be not clearly described in docs, but we have this:
```
- `send_batch_size` (default = 8192): Number of spans or metrics after which a batch will be sent.
``` 

I don't think we should add the complexity to enforce the hard limit by default. This behavior might not be what the users want, but can degrade performance.

What do you think if we keep existing behavior for `send_batch_size` parameter? May be to make it more clear in docs that it's not a hard limit. And add another config parameter that would enforce the hard limit and split traces?

**Comment by pavolloffay** [comment]
> What do you think if we keep existing behavior for send_batch_size parameter (may be to make it more clear in docs that it's not a hard limit) and add another config parameter that would enforce the hard limit and cause splitting traces?

It looks good to me

File: processor/batchprocessor/batch_processor.go (hunk 1 above)
Comment (pavolloffay) [reply processor/batchprocessor/batch_processor.go]: fixed the size is set before the loop

**Comment by pavolloffay** [comment]
@dmitryax thanks for the feedback. I have made the changes and made the splitting configurable.

File: processor/batchprocessor/batch_processor.go [hunk 2]
```diff
@@ -141,6 +143,16 @@ func (bp *batchTraceProcessor) startProcessingCycle() {
 	for {
 		select {
 		case td := <-bp.newTraceItem:
+			if bp.enforceBatchSize {
+				if bp.batchTraces.getSpanCount()+uint32(td.SpanCount()) > bp.sendBatchSize {
+					tds := splitTraces(int(bp.sendBatchSize-bp.batchTraces.getSpanCount()), int(bp.sendBatchSize), td)
+					for i := 1; i < len(tds); i++ {
+						go bp.ConsumeTraces(context.Background(), tds[i])
```
Comment (dmitryax) [inline processor/batchprocessor/batch_processor.go:150]: It should go through `bp.sendItems` otherwise we lose self-reporting metrics about number of processed spans if I don't miss anything

File: processor/batchprocessor/batch_processor.go [hunk 3]
```diff
@@ -141,6 +143,16 @@ func (bp *batchTraceProcessor) startProcessingCycle() {
 	for {
 		select {
 		case td := <-bp.newTraceItem:
+			if bp.enforceBatchSize {
```
Comment (bogdandrutu) [inline processor/batchprocessor/batch_processor.go:146]: What about some simpler approach. Add items as normal to the batch, then do a simple split not by max size. It is a bit more work maybe but simpler logic I feel.

Comment (pavolloffay) [reply processor/batchprocessor/batch_processor.go:108]: That might be even better from the perf standpoint. The buckets of max size would have to be probably split also bc there can be other items arriving in the meantime (unless we push them directly).

**Comment by pavolloffay** [comment]
@bogdandrutu I have rebased the PR and simplified it to do only a single split per consume.

File: processor/batchprocessor/README.md [hunk 4]
```diff
@@ -19,6 +19,9 @@ The following configuration options can be modified:
 batch will be sent.
 - `timeout` (default = 200ms): Time duration after which a batch will be sent
 regardless of size.
+- `enfoce_batch_size` (default = false): Ensures that batch size does not overflow `send_batch_size`.
```
Comment (bogdandrutu) [inline processor/batchprocessor/README.md:22]: What do you think about https://github.com/open-telemetry/opentelemetry-collector/issues/1020, which proposes to have a hard limit instead of the boolean.

Comment (dmitryax) [reply processor/batchprocessor/README.md:22]: I'd suggest this approach as well

Comment (pavolloffay) [reply processor/batchprocessor/README.md:22]: Having the hard upper limit (from #1020) is more flexible. Batches bigger just by a small number will pass whereas the very large ones will be split. 

I will make the change.

Comment (pavolloffay) [reply processor/batchprocessor/README.md]: Done, the last commit introduces `send_batch_max_size`
