### PR TITLE
[service/extensions] extension lifecycle order

### LINKED ISSUE #8732: Start order of extensions is not guaranteed?
**Describe the bug**
Maybe I am misreading the situation, but this code iterates over map when starting extensions, so it cannot guarantee in which order they are started: https://github.com/open-telemetry/opentelemetry-collector/blob/e97ceca47f9eacf50688a5b2e40c0ad22261579b/service/extensions/extensions.go#L34

Even though the documentation implies that the order is define by the declaration order: https://github.com/open-telemetry/opentelemetry-collector/blob/e97ceca47f9eacf50688a5b2e40c0ad22261579b/docs/service-extensions.md?plain=1#L63-L66

I observed some spontaneous failures in my experiments with JaegerV2 which declares extensions with an order expectation: `extensions: [jaeger_storage, jaeger_query]` but the logs show differently:
```
2023-10-24T01:17:01.143Z	info	extensions/extensions.go:33	Starting extensions...
2023-10-24T01:17:01.143Z	info	extensions/extensions.go:36	Extension is starting...	{"kind": "extension", "name": "jaeger_query"}
```

**Steps to reproduce**
It's random behavior, hard to reproduce reliably.

**What did you expect to see?**
Extensions should be starting in the order defined in the config.

**What did you see instead?**
Seeing different order.

**What version did you use?**
Version: `v0.87.0`

**What config did you use?**
https://github.com/jaegertracing/jaeger/blob/28520b31471b36d9e949de4ffaa016c2640a3be7/cmd/jaeger-v2/internal/all-in-one.yaml#L1

**Environment**
OS: MacOS, Linux
Compiler(if manually compiled): go 1.20.x

### PR DESCRIPTION
**Pull request by yurishkuro**
**Description**:
Enforce order of start and shutdown of extensions according to their internally declared dependencies

**Link to tracking Issue**:
Resolves #8732

**Motivation**:
This is an alternative approach to #8733 which uses declaration order in the config to start extensions. That approach (a) enforces order when it's not always necessary to enforce, and (b) exposes unnecessary complexity to the user by making them responsible for the order.

This PR instead derives the desired order of extensions based on the dependencies they declare by implementing a `DependentExtension` interface. That means that extensions that must depend on others can expose this interface and be guaranteed to start after their dependencies, while other extensions can be started in arbitrary order (same as happens today because of iterating over a map).

The extensions that have dependencies have two options to expose them:
  1. if the dependency is always static (e.g. `jaeger_query` extension depending on `jaeger_storage` as in the OP), the extension can express this statically as well, by returning a predefined ID of the dependent extension
  2. in cases where dependencies are dynamic, the extension can read the names of the dependencies from its configuration.

The 2nd scenario is illustrated by the following configuration. Here each complex extension knows that it needs  dependencies that implement `storage` and `encoding` interfaces  (both existing APIs in collector & contrib), but does not know statically which instances of those, the actual names are supplied by the user in the configuration.

```yaml
extensions:
  complex_extension_1:
    storage: filestorage
    encoding: otlpencoding
  complex_extension_2:
    storage: dbstorage
    encoding: jsonencoding
  filestorage:
    ...
  dbstorage:
    ...
  otlpencoding:
  jsonencoding:
```

**Changes**:
* Introduce `DependentExtension` optional interface 
* Change `Extensions` constructor to derive the required order using a directed graph (similar to pipelines)
* Inherited from #8733 - use new ordered list of IDs to start/stop/notify extensions in the desired order (previously a map was used to iterate over, which resulted in random order).
* Tests

**Testing**:
Unit tests

### CODE REVIEW

File: extension/extension.go [hunk 1]
```diff
@@ -16,6 +16,11 @@ import (
 // to the service, examples: health check endpoint, z-pages, etc.
 type Extension = component.Component
 
+// TODO this can even be DependentComponent, but not sure if there's a use case for that.
+type DependentExtension interface {
+	Dependencies() []component.ID
```
Comment (dmitryax) [inline extension/extension.go:21]: As I mentioned in https://github.com/open-telemetry/opentelemetry-collector/pull/8733#issuecomment-1783637186, this capability is only applicable for the Jager-specific use case. It doesn't cover the way components depend on extensions in the Collector core/contrib repos.

Comment (yurishkuro) [reply extension/extension.go:21]: Sorry but I don't understand how you see the duck-typing solution work when you have more than one dependency implementing the same interface.

With this PR you can use this config:
```
extensions:
  complex_extension_1:
    storage: filestorage
  complex_extension_2:
    storage: dbstorage
  filestorage:
    ...
  dbstorage:
    ...
```
The "complex" extensions here will implement DependentExtension and return an ID of the other extension they depend on, which they can read from their user-provided config.

Comment (dmitryax) [reply extension/extension.go:21]: > The "complex" extensions here will implement DependentExtension and return an ID of the other extension they depend on, which they can read from their user-provided config.

After this change, the `complex` extensions have to know about every implementation of the storage extension interface: `filestorage` and `dbstorage`. If I have another storage extension in my own distribution of OTel collector, the `complex` won't be able to work with it.

Comment (dmitryax) [reply extension/extension.go:21]: Another simple option is to introduce some kind of priority class for the extensions that would be considered in the order of initialization

Comment (yurishkuro) [reply extension/extension.go:21]: > After this change, the complex extensions have to know about every implementation of the storage extension interface: filestorage and dbstorage. If I have another storage extension in my own distribution of OTel collector, the complex won't be able to work with it.

On the contrary, it does not need to know anything about implementations at all, only the interface they implement. The actual IDs of the dependent extensions are provide by the user in the configuration.

Comment (dmitryax) [reply extension/extension.go:21]: I see what you mean. I missed the fact that user config is already available at this point. Sorry for the confusion. This approach looks good to me.

**Comment by yurishkuro** [comment]
@atoulme @dmitryax can we agree/confirm that we can take the approach in this PR? I am happy to finish it off. Without a resolution for the ordering we're blocked on jaeger-v2 work.

**Comment by atoulme** [comment]
Are we blocked on this comment?  https://github.com/open-telemetry/opentelemetry-collector/pull/8733#discussion_r1378241672

**Comment by yurishkuro** [comment]
a) I don't know if the comment right or not or if the order even matters for notify
b) that comment is a minor issue, the main question is about the approach itself: https://github.com/open-telemetry/opentelemetry-collector/pull/8733#issuecomment-1784329406

**Comment by atoulme** [comment]
OK so let's keep ourselves nimble and ready for merge - I'll remove the comment. You can do the same in your PR. Dmitrii and other maintainers can make a call on the approach.

**Comment by atoulme** [comment]
Feel free to pick up my commit 84826a34f or apply the diff on top, either works. If you want this PR to be considered for merge, can you up the coverage enough to pass coverage? Remove WIP and draft and let's make this convincing so maintainers can weigh in.

**Comment by atoulme** [comment]
There is a `discussion-needed` label on this PR - do you want to talk it out tomorrow during the SIG meeting?

**Comment by yurishkuro** [comment]
> do you want to talk it out tomorrow during the SIG meeting?

@atoulme I won't be able to make it. I updated the description with details and motivation.

File: docs/service-extensions.md [hunk 2]
```diff
@@ -61,17 +61,18 @@ extensions:
 # The service lists extensions not directly related to data pipelines, but used
 # by the service.
 service:
-  # extensions lists the extensions added to the service. They are started
-  # in the order presented below and stopped in the reverse order.
+  # extensions lists the extensions added to the service. The start-up order respects
+  # any internal dependencies between extensions, but otherwise is arbitrary.
+  # The stop order is always the reverse of the start-up order.
   extensions: [health_check, pprof, zpages]
```
Comment (yurishkuro) [inline docs/service-extensions.md:67]: here is the actual change, ignore whitespace auto-fixes

**Comment by dmitryax** [comment]
I'm good with this approach 👍

File: extension/extension.go [hunk 3]
```diff
@@ -16,6 +16,13 @@ import (
 // to the service, examples: health check endpoint, z-pages, etc.
 type Extension = component.Component
 
+// DependentExtension is an optional interface that can be implemented by extensions
+// that depend on other extensions and must be started only after their dependencies.
+// See https://github.com/open-telemetry/opentelemetry-collector/pull/8768 for examples.
+type DependentExtension interface {
```
Comment (dmitryax) [inline extension/extension.go:22]: I don't think we need `Extension` suffix with the given package name, `extension.Dependent` should be enough. We usually follow this practice in this codebase. Also, we should include `extension.Extension` to avoid misusing it by the clients.

**Review by djaglowski — COMMENTED** [review]
I think this is a great solution. The optional interface is an elegant way to manage ordering concerns.

File: service/extensions/graph.go [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+					graph.SetEdge(graph.NewEdge(d, n))
+				} else {
+					return nil, fmt.Errorf("unable to find extension %s on which extension %s depends", depID, extID)
+				}
+			}
+		}
+	}
+	orderedNodes, err := topo.Sort(graph)
+	if err != nil {
+		return nil, fmt.Errorf("unable to sort the extenions dependency graph: %w", err)
```
[the remark this answers is not in the document]
Comment (yurishkuro) [reply service/extensions/graph.go:50]: That's a lot of code to copy - is there a good place to share it?

[the remark this answers is not in the document]
Comment (djaglowski) [reply service/extensions/graph.go:50]: Export a shared function in `service/internal/graph` would make sense

[the remark this answers is not in the document]
Comment (yurishkuro) [reply service/extensions/graph.go:50]: turns out that function depends on private struct as a type of node, so I add a simpler version here.

File: extension/extension.go [hunk 5]
```diff
@@ -16,6 +16,13 @@ import (
 // to the service, examples: health check endpoint, z-pages, etc.
 type Extension = component.Component
 
+// Dependent is an optional interface that can be implemented by extensions
+// that depend on other extensions and must be started only after their dependencies.
+// See https://github.com/open-telemetry/opentelemetry-collector/pull/8768 for examples.
+type Dependent interface {
+	Dependencies() []component.ID
```
Comment (dmitryax) [inline extension/extension.go:23]: As I mentioned in another comment, I think we should add the `Extension` interface to avoid misuse. We do this for other extension types
```suggestion
	Extension
	Dependencies() []component.ID
```

Comment (yurishkuro) [reply extension/extension.go:24]: Sorry, I forgot to add it. Done

**Review by dmitryax — APPROVED** [review]
LGTM

**Comment by yurishkuro** [comment]
🎉
