### PR TITLE
[scraper/scraperhelper/xscraperhelper] fix the merge of profiles in the profiling scraper helpers

### LINKED ISSUE #14790: [scraper/scraperhelper/xscraperhelper] merging of profiles does not merge dictionaries
### Component(s)

scraper/scraperhelper/xscraperhelper

### What happened?

**Describe the bug**
Running the pprof receiver pointing to an http endpoint panics with index out of range
from trying to debug i think the root issue is [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/scraper/scraperhelper/xscraperhelper/controller.go#L120)
where the resource profiles are copied over from the iterated profiles, but not the the Dictionary
that causes the debugexporter to search the index in the dictionary and it can't find it
This is an issue for the xscraperhelper component, but i think the exporters (debug/otel) should also be able to handle indices not being found more gracefully instead of panicking, i can open a different issue on that if needed

**Steps to reproduce**
running the collector with pprof receiver and debug exporter (configuration below)
where port 6060 has a pprof server

**What did you expect to see?**

Profiles being scraped and exported

**What did you see instead?**
error logs (provided below)

### Collector version

v0.147.1-0.20260313183754-7cd8f588399b

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
    pprof:
      endpoint: http://localhost:6060/debug/pprof/heap
      collection_interval: 10s

  exporters:
    debug:
      verbosity: detailed

  service:
    pipelines:
      profiles:
        receivers: [pprof]
        exporters: [debug]
```

### Log output

```shell
panic: runtime error: index out of range [4] with length 0

goroutine 59 [running]:
go.opentelemetry.io/collector/pdata/pprofile.KeyValueAndUnitSlice.At(...)
	/go/pkg/mod/go.opentelemetry.io/collector/pdata/pprofile@v0.147.1-0.20260313183754-7cd8f588399b/generated_keyvalueandunitslice.go:55
go.opentelemetry.io/collector/exporter/debugexporter/internal/normal.normalProfilesMarshaler.MarshalProfiles({}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/debugexporter@v0.147.1-0.20260313183754-7cd8f588399b/internal/normal/profiles.go:50 +0x81c
go.opentelemetry.io/collector/exporter/debugexporter.(*debugExporter).pushProfiles(0x40001e8870, {0x0?, 0x0?}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/debugexporter@v0.147.1-0.20260313183754-7cd8f588399b/exporter.go:114 +0x170
go.opentelemetry.io/collector/consumer/xconsumer.ConsumeProfilesFunc.ConsumeProfiles(0x40002063c0?, {0x233c8d8?, 0x4000726d20?}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/consumer/xconsumer@v0.147.1-0.20260313183754-7cd8f588399b/profiles.go:31 +0x44
go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper.NewProfiles.requestConsumeFromProfiles.func2({0x233c8d8?, 0x4000726d20?}, {0x2333ed0?, 0x400042abb8?})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper@v0.147.0/profiles.go:156 +0x50
go.opentelemetry.io/collector/exporter/exporterhelper/internal/sender.(*sender[...]).Send(...)
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper@v0.147.0/internal/sender/sender.go:31
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*obsReportSender[...]).Send(0x2334c60, {0x233c910, 0x40002063c0?}, {0x2333ed0?, 0x400042abb8})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper@v0.147.0/internal/obs_report_sender.go:105 +0x7c
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Send(0x4000438248, {0x233c910, 0x40002063c0}, {0x2333ed0, 0x400042abb8})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper@v0.147.0/internal/base_exporter.go:113 +0x68
go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper.NewProfilesRequest.newConsumeProfiles.func1({0x233c910, 0x40002063c0}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper@v0.147.0/profiles.go:211 +0x1d4
go.opentelemetry.io/collector/consumer/xconsumer.ConsumeProfilesFunc.ConsumeProfiles(...)
	/go/pkg/mod/go.opentelemetry.io/collector/consumer/xconsumer@v0.147.1-0.20260313183754-7cd8f588399b/profiles.go:31
go.opentelemetry.io/collector/service/internal/refconsumer.refProfiles.ConsumeProfiles({{0xffff74166028?, 0x40001f4c60?}}, {0x233c910?, 0x40002063c0?}, {0x40000c5200?, 0x40001be0e8?})
	/go/pkg/mod/go.opentelemetry.io/collector/service@v0.147.1-0.20260313183754-7cd8f588399b/internal/refconsumer/profiles.go:30 +0x94
go.opentelemetry.io/collector/consumer/xconsumer.ConsumeProfilesFunc.ConsumeProfiles(...)
	/go/pkg/mod/go.opentelemetry.io/collector/consumer/xconsumer@v0.147.1-0.20260313183754-7cd8f588399b/profiles.go:31
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/receivercreator.(*enhancingConsumer).ConsumeProfiles(0x40000eab90, {0x233c910, 0x40002063c0}, {0x40000c5200?, 0x40001be0e8?})
	/src/receiver/receivercreator/consumer.go:137 +0xd4
go.opentelemetry.io/collector/scraper/scraperhelper/xscraperhelper.scrapeProfiles(0x400049eba0, {0x232a620, 0x40000eab90})
	/go/pkg/mod/go.opentelemetry.io/collector/scraper/scraperhelper/xscraperhelper@v0.147.1-0.20260313183754-7cd8f588399b/controller.go:135 +0x28c
go.opentelemetry.io/collector/scraper/scraperhelper/xscraperhelper.NewProfilesController.func1(0x6fc23ac00?)
	/go/pkg/mod/go.opentelemetry.io/collector/scraper/scraperhelper/xscraperhelper@v0.147.1-0.20260313183754-7cd8f588399b/controller.go:109 +0x20
go.opentelemetry.io/collector/scraper/scraperhelper/internal/controller.(*Controller[...]).startScraping.func1()
	/go/pkg/mod/go.opentelemetry.io/collector/scraper/scraperhelper@v0.147.1-0.20260313183754-7cd8f588399b/internal/controller/controller.go:113 +0xe4
sync.(*WaitGroup).Go.func1()
	/usr/local/go/src/sync/waitgroup.go:239 +0x4c
created by sync.(*WaitGroup).Go in goroutine 53
	/usr/local/go/src/sync/waitgroup.go:237 +0x70
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by NimrodAvni78**
#### Description
Profiles combining from scraper omits merging the dictionary, use `mergeTo` instead of `MoveAndAppendTo` of ResourceProfiles

#### Link to tracking issue
Fixes #14790

### CODE REVIEW

File: scraper/scraperhelper/xscraperhelper/controller_test.go [hunk 1]
```diff
@@ -409,6 +409,184 @@ func assertProfilesScraperObsMetrics(t *testing.T, tel *componenttest.Telemetry,
 		}, metricdatatest.IgnoreTimestamp(), metricdatatest.IgnoreExemplars())
 }
 
+// TestScrapeProfilesPreservesDictionary verifies that the scraper controller
+// preserves the dictionary (string table, attribute table, etc.) when passing
+// scraped profiles to the next consumer.
+func TestScrapeProfilesPreservesDictionary(t *testing.T) {
```
Comment (dmathieu) [inline scraper/scraperhelper/xscraperhelper/controller_test.go]: I'm not sure about this test. This behavior is part of `MergeTo`, and is already tested there. We don't need to retest it every time we use the method.

Comment (NimrodAvni78) [reply scraper/scraperhelper/xscraperhelper/controller_test.go]: ok i can delete it, just wanted to have a test case to test regression
should i delete both tests?

Comment (dmathieu) [reply scraper/scraperhelper/xscraperhelper/controller_test.go]: No, The second test actually ensures that we run merge and not just move the resource profiles, as we did before.

**Comment by NimrodAvni78** [comment]
I believe there is the same issue in the [pprofreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/pprofreceiver/internal/file_scraper.go#L55) which causes these tests to fail
i will open an issue and fix it in the contrib repo before merging this

**Comment by NimrodAvni78** [comment]
Opened a collector-contrib pr
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/46992

**Review by dmathieu — APPROVED** [review]

**Review by florianl — APPROVED** [review]
Thanks for the fix!

**Review by rogercoll — APPROVED** [review]

**Comment by NimrodAvni78** [comment]
@dmathieu @dmitryax is it fine that codecov is failing, it only fails on the case where we have an error in merging profiles
anything more i need to do to get this merged?

**Comment by dmathieu** [comment]
Yes, it is fine.
We only need a maintainer to take a look at this PR.

**Review by codeboten — APPROVED** [review]
