### PR TITLE
[configoptional] Fix inner Unmarshaler method not being called

### LINKED ISSUE #14500: Batcher sizer is set to items even though the queue sizer is bytes
### Component(s)

pkg/exporter/exporterhelper

### What happened?

**Describe the bug**

Batcher sizer is set to **items** even though the queue sizer is **bytes**.

**Steps to reproduce**

```
    sending_queue:
      queue_size: 62914560  # 60MiB
      sizer: bytes
      block_on_overflow: true
      num_consumers: 64
      batch:
        min_size: 1048576   # 1MiB
        max_size: 16777216  # 16MiB
        flush_timeout: 1s
```

**What did you expect to see?**

The sent messages to not be larger than 16MB

**What did you see instead?**

The sent messages larger than 100MB

### Collector version

v0.142.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by jade-guiton-dd**
#### Description

When a config struct is wrapper inside `configoptional.Optional`, the `Unmarshal` method on the struct will never be called. This is because `confmap` deliberately skips the top-level Unmarshaler when unmarshaling a `Conf` which was passed as a parameter of an `Unmarshal` hook, in order to avoid infinite recursion.

This PR attempts to fix this bug by introducing a new `confmap` option, which allows forcing the use of top-level Unmarshalers in cases where we know this does not cause infinite recursion (ie. when we're unmarshaling into a different config struct type).

I've listed two other possible solutions to the problem in the tracking issue.

#### Link to tracking issue
Fixes #14500

#### Testing
I modified the test that was supposed to check the situation described in #14500 to use `Conf.Unmarshal` instead of calling `Optional.Unmarshal` directly. This makes sure the test fails before the fix is applied.

I also added a simple unit test for the new `confmap.WithForceUnmarshaler` option, showing that it allows a recursive call of top-level `Unmarshal`.

### CODE REVIEW

File: confmap/confmap.go [hunk 1]
```diff
@@ -39,6 +39,13 @@ func WithIgnoreUnused() UnmarshalOption {
 	return internal.WithIgnoreUnused()
 }
 
+// WithForceUnmarshaler sets an option to run a potential top-level Unmarshal method
+// even if the provided config is already a parameter from an Unmarshal hook.
+// If used on the wrong config type, this may cause infinite recursion!
```
Comment (iblancasa) [inline confmap/confmap.go]: I think it would be good to add when it is a good idea to use this. Something like:
```
  // Use this option when unmarshaling into a different type than the
  current receiver.
  // For example: wrapper types like configoptional.Optional use
  this to ensure
  // the inner type's Unmarshal method is called.
```

File: confmap/confmap.go [hunk 2]
```diff
@@ -39,6 +39,13 @@ func WithIgnoreUnused() UnmarshalOption {
...
+func WithForceUnmarshaler() UnmarshalOption {
```
Comment (mx-psi) [inline confmap/confmap.go]: I'd rather export this in `xconfmap` since we have the potentially cleaner option of doing option (1) from https://github.com/open-telemetry/opentelemetry-collector/issues/14500#issuecomment-3817223534

File: .chloggen/fix-optional-unmarshal-recursive.yaml [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+note: Fix `Unmarshal` methods not being called when config is wrapped inside `Optional`
+
+# One or more tracking issues or pull requests related to the change
+issues: [14500]
+
+# (Optional) One or more lines of additional information to render under the primary note.
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext: |
+  This bug notably manifested in the fact that `sending_queue::batch::sizer` stopped defaulting to `sending_queue::sizer`,
```
Comment (mx-psi) [inline .chloggen/fix-optional-unmarshal-recursive.yaml]: I think it doesn't hurt to be a bit more explicit on the fact that this is about exporters
```suggestion
  This bug notably manifested in exporters in the fact that `sending_queue::batch::sizer` stopped defaulting to `sending_queue::sizer`,
```

File: confmap/confmap.go (hunk 2 above)
Comment (jade-guiton-dd) [reply confmap/confmap.go]: Makes sense, moved it to `xconfmap`.

File: confmap/xconfmap/config.go [hunk 4]
```diff
@@ -194,3 +195,13 @@ func stringifyMapKey(val reflect.Value) string {
...
 	}
 }
+
+// WithForceUnmarshaler sets an option to run a top-level Unmarshal method,
+// even if the Conf being unmarshaled is already a parameter from an Unmarshal method.
+// To avoid infinite recursion, this should only be used when unmarshaling into
+// a different type from the current Unmarshaler.
+// For instance, this should be used in wrapper types such as configoptional.Optional
+// to ensure the inner type's Unmarshal method is called.
+func WithForceUnmarshaler() confmap.UnmarshalOption {
```
Comment (bogdandrutu) [inline confmap/xconfmap/config.go:205]: Nit (can be solved after release as well): WithForceUnmarshalTopElement?
