### PR TITLE
fix: update sortFactoriesByType to remove alias

### LINKED ISSUE #14682: [otelcol] components command hides components that have deprecated type aliases
### Component(s)

otelcol

### What happened?

**Describe the bug**  
`otelcol components` omits *canonical* component types when the component factory exposes a deprecated type alias (e.g., snake_case rename with legacy alias). This makes the command misleading: the component works in config, but it doesn’t appear in the `components` output. This seems related to the alias handling used/introduced around PR #14493

**Steps to reproduce**  
1. <your-otelcol-binary> components | grep -nE 'k8s_attributes|k8sattributes'
2.  nothing comes out of the output while it did until version 0.145.0

**What did you expect to see?**  
The canonical component (`k8s_attributes`) should still be present in `otelcol components` output. (Aliases can be shown separately/as metadata, but canonical should not disappear.)

**What did you see instead?**  
The canonical factory is filtered out because `sortFactoriesByType` excludes anything for which `isComponentAlias(...)` returns true, and `isComponentAlias` currently returns true whenever `DeprecatedAlias() != ""`. As a result, `otelcol components` output can miss canonical components that have deprecated aliases.

### Collector version

0.146.0/0.146.1/0.147.0

### PR DESCRIPTION
**Pull request by RealAnna**
#### Description
My understanding of MakeFactoryMap behavior is that alias entries are not separate alias factories. Instead, the alias key points to the same canonical factory so fixing the sorting to reflect that.

#### Link to tracking issue
Fixes #14682

#### Testing
Added unittest 

To manual test 

1. Add k8sattributesprocessor to otelcorecol
    `- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.147.0`

2. regenerate it  `make genotelcorecol `
3.  create binary  `make otelcorecol`
4. verify output  `./bin/otelcorecol components | grep -nE 'k8s_attributes|k8sattributes|otlp_http|otlphttp' `
```
25:    - name: k8s_attributes
26:      module: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.147.0
56:    - name: otlp_http
57:      module: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.147.0
```

### CODE REVIEW

File: otelcol/command_components_test.go [hunk 1]
```diff
@@ -260,54 +260,74 @@ func TestSortFactoriesByType(t *testing.T) {
...
-				newMockFactory("receiver_factory"),
+				// IMPORTANT: keys must match factory.Type() (this mirrors MakeFactoryMap output).
+				component.MustNewType("processor"): newMockFactory("processor"),
+				component.MustNewType("exporter"):  newMockFactory("exporter"),
+				component.MustNewType("receiver"):  newMockFactory("receiver"),
 			},
+			wantTypes: []string{"exporter", "processor", "receiver"},
 		},
 		{
-			name: "with multiple factories",
```
Comment (dmathieu) [inline otelcol/command_components_test.go:280]: Why is this test removed?

File: otelcol/command_components.go [hunk 2]
```diff
@@ -136,26 +136,27 @@ func newComponentsCommand(set CollectorSettings) *cobra.Command {
...
+	componentTypes := canonicalFactoryKeys(factories)
 	sort.Slice(componentTypes, func(i, j int) bool {
 		return componentTypes[i].String() < componentTypes[j].String()
 	})
 
-	// Build and return list of factories, sorted by component types
-	sortedFactories := make([]T, 0, len(factories))
+	sortedFactories := make([]T, 0, len(componentTypes))
 	for _, componentType := range componentTypes {
-		if !isComponentAlias(factories[componentType]) {
```
Comment (dmathieu) [inline otelcol/command_components.go:154]: The `isComponentAlias` method should be removed, as it's not used anymore.

File: otelcol/command_components_test.go (hunk 1 above)
Comment (RealAnna) [reply otelcol/command_components_test.go:280]: since MakeFactoryMap behavior is that alias entries are not separate alias factories but gets remapped to canonical types I adapted the testcase and renamed it ["with canonical factories only (sorted by type)"](https://github.com/open-telemetry/opentelemetry-collector/pull/14690/changes/BASE..580afd2f9b4fcbdbb1f5d2d2beb0bd355c39d7c5#diff-7f4fb85c9fa3f665a6cb555eac9f0a8e20d5da50b63a8c2a92ac0dd6216ac2beR271)

File: otelcol/command_components.go (hunk 2 above)
Comment (RealAnna) [reply otelcol/command_components.go:154]: Indeed it was used in sortProvidersByScheme but it actually did nothing there since Providers do not have the concept of type alias .. so I just deleted it

**Review by dmathieu — APPROVED** [review]

File: .chloggen/fix-alias-printing.yaml
Comment (evan-bradley) [inline .chloggen/fix-alias-printing.yaml]:
```suggestion
subtext: This resolves an issue where aliased components were skipped.
```
I think we should add some context, since the current note makes me think some components were instead duplicated.

**Review by evan-bradley — APPROVED** [review]
Nice logic cleanup, thanks.

**Comment by RealAnna** [comment]
@evan-bradley has this one been forgotten 😢 ?

**Review by mx-psi — APPROVED** [review]
